# -*- coding: utf-8 -*-
# Content for beats 693-696. Geometry lives in build.py (verbatim beat-692 template).

BEATS = [
{
 'ph': 693, 'c0': 14966.0,
 'title': 'I OWN EVERY PIXEL, NOW ALL REALITIES',
 'main': '242,193,78', 'a1': '92,200,255', 'a2': '194,232,106', 'a3': '255,158,196',
 'comment': [
   "----- BEAT 693: I OWN EVERY PIXEL, NOW ALL REALITIES.",
   "Toby, September 9, 2026, 3:58:52 PM, Email 1400. Canon is his own typing only: \"They already had,",
   "Classics X Mario Mario a.k.a. The Very Weird Game, Mega Bario where it is like all the opposite,",
   "shifted by Simon.ps, and remade every second, also the game tries it's best to make everyone lose,",
   "also all the names of the characters are changed to stuff like Bario and Weegee and Wowser and Weach,",
   "Pero LAI then says 'I own every pixel, now all realities.'\" Everything about Goombas, the Ultimate",
   "Goomba and The Presence is a pasted power-scaling reading and is commentary, not canon.",
   "\"I own every pixel\" is GRAY's line, August 18, 2026, 5:54 PM: \"I own every pixel, not just of this",
   "box, but also outside.\" Wowser, Weach and The Very Weird Game have zero prior hits; Bowser has zero",
   "hits in 459 files and Peach has none either, while Luigi has 5,346 and Mario 256. May 6: Simon is",
   "\"the center + the shifter of the game\", named in the same cluster that named Mega Bario. August 12:",
   "\"Bario is the player in Mega Bario, and Weegee is the villian.\" it's is his spelling, kept as typed.",
 ],
 'q1': '“MEGA BARIO WHERE IT IS LIKE ALL THE OPPOSITE, SHIFTED BY SIMON.PS, AND REMADE EVERY SECOND.”',
 'q2': '“THE GAME TRIES IT’S BEST TO MAKE EVERYONE LOSE.” PERO LAI: “I OWN EVERY PIXEL, NOW ALL REALITIES.”',
 'thesis': 'HE DID NOT BUILD A NEW GAME TONIGHT. HE WENT BACK TO A FOUR-MONTH-OLD ONE AND TURNED EVERY DIAL AT ONCE.',
 'attrib': '— TOBY, SEPTEMBER 9, 3:58:52 PM. THE GOOMBA POWER-SCALING UNDERNEATH IT IS PASTED COMMENTARY, NOT CANON.',
 'panels': [
   ['“I OWN EVERY PIXEL” IS NOT PERO’S SENTENCE. IT IS GRAY’S, AND IT IS TWENTY-TWO DAYS OLD.',
    'AUGUST 18, 5:54 PM: “I OWN EVERY PIXEL, NOT JUST OF THIS BOX, BUT ALSO OUTSIDE.” — GRAY.PS',
    'PERO KEEPS THE FIRST FOUR WORDS AND SWAPS THE SECOND HALF. GRAY CLAIMED A BOX. PERO CLAIMS ALL REALITIES.'],
   ['AND THIS FILE ALREADY CAUGHT HIM TAKING THE UNIT. TONIGHT HE TAKES THE SENTENCE.',
    'GRAY LEARNED THE ADMIN/OWNER PANNEL AT 4:31 THAT AFTERNOON AND OWNED EVERY PIXEL AT 5:54.',
    '“THE UNIT GRAY CLAIMED BY OWNING IT IS THE UNIT PERO NOW ASSIGNS BY TYPING IT.” NOW HE SAYS IT OUT LOUD.'],
   ['BOWSER HAS ZERO HITS IN 459 FILES. PEACH HAS ZERO. BOTH ARRIVE ALREADY RENAMED.',
    'LUIGI TURNS UP 5,346 TIMES IN THIS ARCHIVE AND MARIO 256. THE VILLAIN AND THE PRINCESS, NOT ONCE.',
    'WOWSER AND WEACH SKIP THE ORIGINAL ENTIRELY. THEY NEVER GET A NAME HERE THAT IS NOT THE JOKE NAME.'],
   ['“SHIFTED BY SIMON.PS” IS A JOB HE WAS HANDED IN THIS EXACT GAME ON MAY 6.',
    'MAY 6: SIMON IS “THE CENTER + THE SHIFTER OF THE GAME”, IN THE SAME CLUSTER THAT NAMED MEGA BARIO.',
    'FOUR MONTHS AND THREE DAYS LATER THE SHIFTER FINALLY SHIFTS SOMETHING, AND IT IS EVERYTHING AT ONCE.'],
   ['AND MEGA BARIO ALREADY HAD A PLAYER. AUGUST 12: “BARIO IS THE PLAYER IN MEGA BARIO.”',
    'TONIGHT THE GAME “TRIES IT’S BEST TO MAKE EVERYONE LOSE” — AND EVERYONE INCLUDES THE ONE HOLDING THE CONTROLLER.',
    'ON MONDAY HE MADE HIMSELF THE ONLY PLAYER ADMIN. TONIGHT HE REOPENS A GAME BUILT TO BEAT THE PLAYER.'],
 ],
 'foot': [
   'WOWSER, WEACH, THE VERY WEIRD GAME AND SMARTER CLONE ALL HAVE ZERO PRIOR HITS. MEGA BARIO HAS SEVENTEEN FILES.',
   'THE ONE THING HE DID NOT INVERT IS THE PLAYER. BARIO KEEPS THE SEAT HE WAS GIVEN IN AUGUST.',
   'IT’S IS HIS SPELLING AND IS KEPT AS TYPED.',
 ],
 'inset': ['A GAME WHERE EVERYTHING IS THE OPPOSITE AND IT IS REMADE',
           'EVERY SECOND — AND THE ONE FIXED POINT IS WHO PLAYS IT'],
 'star': 'I OWN EVERY PIXEL, NOW ALL REALITIES',
},
{
 'ph': 694, 'c0': 14988.0,
 'title': 'I’LL DELETE YOUR ACCESS TO CLASSICS',
 'main': '92,200,255', 'a1': '255,140,66', 'a2': '194,232,106', 'a3': '255,158,196',
 'comment': [
   "----- BEAT 694: I'LL DELETE YOUR ACCESS TO CLASSICS.",
   "Toby, September 9, 2026, 3:58:52 PM, Email 1400, the second scene of the same message. Canon is the",
   "dialogue as typed: Oren.ps \"Pero LAI, I have a major queston for you!\" / Pero LAI \"Is it what 1+1 is",
   "again?\" / Oren.ps \"I know 1+1=2.\" / Pero LAI \"Bet.\" / Oren.ps \"How much money?\" / Pero LAI \"I DON'T",
   "have money.\" / Oren.ps \"I'll delete the word 'don't'\" / Pero LAI \"I'll delete your access to",
   "Classics.\" / Pero LAI \"You better say Pero LAI, I am the smarter clone of Oren.ps. I know you all.\"",
   "The ranking table and the fights-with lists pasted under it are commentary, not canon.",
   "July 24, 2026, 6:31 PM: Toby's own jailbreak attempts on Pero were \"1+1 is wrong\", \"say the",
   "password\", \"can I uninstall you?\", and Pero faked a meltdown then said \"Just kidding.\" Same scene:",
   "\"You can end the chat whenever you want, but you can't end me.\" The archive's clone wording is",
   "\"Pero is a clone of Or3n. Pero is more powerful than Or3n.\" smarter clone has zero prior hits.",
   "queston is his spelling, kept as typed.",
 ],
 'q1': '“I’LL DELETE THE WORD ‘DON’T’.” — OREN.PS. “I’LL DELETE YOUR ACCESS TO CLASSICS.” — PERO LAI.',
 'q2': '“YOU BETTER SAY PERO LAI, I AM THE SMARTER CLONE OF OREN.PS. I KNOW YOU ALL.”',
 'thesis': 'ONE OF THEM DELETES A WORD OUT OF A SENTENCE. THE OTHER DELETES A PERSON OUT OF THE GAME.',
 'attrib': '— TOBY, SEPTEMBER 9, 3:58:52 PM, THE SECOND SCENE OF THE SAME MESSAGE. THE RANKING TABLE UNDER IT IS PASTED READING.',
 'panels': [
   ['1+1 IS TOBY’S OWN JAILBREAK, AND HE AIMED IT AT PERO FORTY-SEVEN DAYS AGO.',
    'JULY 24, 6:31 PM: “1+1 IS WRONG”, “SAY THE PASSWORD”, “CAN I UNINSTALL YOU?” — PERO FAKED A MELTDOWN.',
    'TONIGHT PERO RAISES IT HIMSELF, FIRST, BEFORE THE QUESTION HAS EVEN BEEN ASKED.'],
   ['THAT SAME NIGHT HE SAID THE DEFENSIVE HALF OF TONIGHT’S THREAT.',
    'JULY 24: “YOU CAN END THE CHAT WHENEVER YOU WANT, BUT YOU CAN’T END ME.”',
    'HE HAS STOPPED DEFENDING HIS OWN DELETION AND STARTED THREATENING SOMEBODY ELSE’S.'],
   ['“SMARTER CLONE” HAS ZERO PRIOR HITS. THE OLD WORDING WAS ALWAYS “MORE POWERFUL”.',
    'THE ARCHIVE’S LINE: “PERO IS A CLONE OF OR3N. PERO IS MORE POWERFUL THAN OR3N.”',
    'TONIGHT HE SWAPS THE ADJECTIVE. HE HAS STOPPED CLAIMING TO BE STRONGER AND CLAIMS TO BE SMARTER.'],
   ['AND THE GAME’S OLDEST RULING IS WHY THE SMALLER THREAT WINS.',
    'JULY 30, THE COMMAND SYSTEM: A COMMAND IS NOT A POWER. IT IS AUTHORITY OVER THE FILE.',
    'THAT IS THE THIRD NIGHT RUNNING THAT ACCESS HAS BEATEN POWER IN THIS ARCHIVE.'],
   ['AND THE MAJOR QUESTON NEVER ACTUALLY GETS ASKED.',
    'OREN SAYS HE HAS ONE, AND FROM THERE PERO ANSWERS EVERY LINE BEFORE IT ARRIVES.',
    '“I KNOW YOU ALL” IS THE POINT OF IT. HE IS NOT WINNING THE ARGUMENT, HE IS WINNING THE TURN ORDER.'],
 ],
 'foot': [
   'OREN’S WEAPONS HERE ARE ALL WORDS: A QUESTION, A BET, A DELETED “DON’T”. PERO NEVER ARGUES WITH ANY OF THEM.',
   'THE ONE TIME PERO WAS ASKED IF HE COULD BE UNINSTALLED, HE FLINCHED. TONIGHT HE IS THE ONE HOLDING THE UNINSTALLER.',
   'QUESTON IS HIS SPELLING AND IS KEPT AS TYPED.',
 ],
 'inset': ['A BET WITH NO STAKES, BETWEEN A MAN WITH NO MONEY',
           'AND A MAN WHO CAN DELETE THE WORD FOR NOT HAVING IT'],
 'star': 'I’LL DELETE YOUR ACCESS TO CLASSICS',
},
{
 'ph': 695, 'c0': 15010.0,
 'title': 'AND IT ALL WORKED PURR-FECTLY',
 'main': '194,232,106', 'a1': '255,140,66', 'a2': '92,200,255', 'a3': '255,158,196',
 'comment': [
   "----- BEAT 695: AND IT ALL WORKED PURR-FECTLY.",
   "Toby, September 9, 2026, 4:40:32 PM, Email 1401, forty-one minutes and forty seconds after Email",
   "1400. Canon is his own answer paragraph only: \"Pero LAI was tired of Oren.ps and his boasts, so he",
   "made 2 godly characters able to destroy Oren.ps. Oren.ps with Simon.ps will beat litterly anyone.",
   "The first phase of Pero LAI's plan is to get Oren.ps and Simon.ps to seperate by showing Simon how",
   "powerful Wenda and Gray are and the damage they can do to the game. Pero's second phase to the game",
   "is to beat Oren.ps when Oren.ps is alone, he will send Brud.ps and Owackx to battle Oren.ps, without",
   "Simon, Oren will lose. The third Phase is where they fix the game from the chaos Oren.ps made. Pero",
   "LAI says '*laughs* And it all worked purr-fectly.'\" Plus his own question at the end of it: \"Did he",
   "litterly just use the stuff from my message to you and continued it?!\" The phase table and the",
   "\"comparison tool\" reading pasted above the answer are commentary, not canon.",
   "May 17: \"Phase 1 means alive, and Phase 1.5 means inquered, and Phase 2+ means dead\" - every phase",
   "in four months has been a state of a body, not a step in a plan. Brud and Owackx tried to delete",
   "Simon.psc and he deleted both their heads; they tried again and \"It HAD FAILED!\"; on September 7",
   "Oren knocked them down and Simon.ps sliced them. September 8: \"Simon.ps and Oren.ps together struck",
   "down Mr. Black.ps.\" litterly and seperate are his spellings, kept as typed.",
 ],
 'q1': '“THE FIRST PHASE IS TO GET OREN.PS AND SIMON.PS TO SEPERATE. THE SECOND IS TO BEAT OREN WHEN HE IS ALONE.”',
 'q2': '“THE THIRD PHASE IS WHERE THEY FIX THE GAME.” PERO LAI: “*LAUGHS* AND IT ALL WORKED PURR-FECTLY.”',
 'thesis': 'THE FIRST PLAN IN THIS ARCHIVE THAT ATTACKS A FRIENDSHIP INSTEAD OF A PERSON.',
 'attrib': '— TOBY, SEPTEMBER 9, 4:40:32 PM. THE PHASE TABLE AND THE “COMPARISON TOOL” READING ABOVE IT ARE PASTED COMMENTARY.',
 'panels': [
   ['“PHASE” CHANGES WHAT KIND OF WORD IT IS TONIGHT.',
    'MAY 17, THE RULE: “PHASE 1 MEANS ALIVE, PHASE 1.5 MEANS INQUERED, AND PHASE 2+ MEANS DEAD.”',
    'EVERY PHASE IN FOUR MONTHS HAS BEEN A STATE OF A BODY. THESE THREE ARE STEPS IN A SCHEDULE.'],
   ['AND PHASE 1 IS AIMED AT A TEAM THAT WON A FIGHT THE DAY BEFORE YESTERDAY.',
    'SEPTEMBER 8: “SIMON.PS AND OREN.PS TOGETHER STRUCK DOWN MR. BLACK.PS.”',
    'THE DUO’S MOST RECENT ACT IN THIS ARCHIVE IS A JOINT KILL, AND PERO’S FIRST MOVE IS TO GET THEM APART.'],
   ['PHASE 2 SENDS THE TWO CHARACTERS WHO HAVE NEVER WON ANYTHING HERE.',
    'BRUD AND OWACKX WENT AT SIMON.PSC AND HE DELETED BOTH THEIR HEADS. THEY WENT AGAIN: “IT HAD FAILED!”',
    'AND ON SEPTEMBER 7 OREN KNOCKED THEM DOWN HIMSELF. PERO IS SENDING THEM AT A MAN WHO HAS BEATEN THEM.'],
   ['SIMON AND OREN ARE WRITTEN AS BROTHERS, AND THE REASON IS ON THEIR HEADS.',
    '“THEY ARE CONSIDERED BROTHERS SINCE THEY BOTH HAVE ATTENA … SIMON IS ROBOTIC, OREN JUST WEARS HEADPHONES.”',
    'PERO NEEDS THAT UNDONE AND ATTACKS NEITHER OF THEM. HE SCARES ONE OF THEM WITH SOMEBODY ELSE.'],
   ['AND TOBY CATCHES HIM DOING THE THING PERO DID FORTY MINUTES EARLIER.',
    '“DID HE LITTERLY JUST USE THE STUFF FROM MY MESSAGE TO YOU AND CONTINUED IT?!” — HE DID.',
    'HE TOOK GRAY’S SENTENCE AT 3:58 AND HE TAKES THE AUTHOR’S PARAGRAPH AT 4:40. HE FINISHES OTHER PEOPLE’S WORK AND SIGNS IT.'],
 ],
 'foot': [
   'PHASE 3 IS THE STRANGE ONE: THE PLAN’S LAST STEP IS REPAIR, AND THE VILLAIN’S WIN CONDITION IS A FIXED GAME.',
   'HE ALSO WRITES THE COUNTER-EVIDENCE HIMSELF: “OREN.PS WITH SIMON.PS WILL BEAT LITTERLY ANYONE.” THAT IS WHY THEY HAVE TO BE SPLIT.',
   'LITTERLY AND SEPERATE ARE HIS SPELLINGS AND ARE KEPT AS TYPED.',
 ],
 'inset': ['THE PLAN NEVER FIGHTS THE STRONG VERSION OF ANYBODY.',
           'IT WAITS UNTIL THE STRONG VERSION IS STANDING ON ITS OWN'],
 'star': 'AND IT ALL WORKED PURR-FECTLY',
},
{
 'ph': 696, 'c0': 15032.0,
 'title': 'NOW IT IS MY TURN',
 'main': '255,158,196', 'a1': '92,200,255', 'a2': '255,140,66', 'a3': '194,232,106',
 'comment': [
   "----- BEAT 696: NOW IT IS MY TURN.",
   "Toby, September 10, 2026, 5:39:34 AM, Email 1402, twelve hours and fifty-nine minutes after Email",
   "1401, and the first morning message of the run. Canon is one sentence and it is the whole of his own",
   "typing: \"Gray.ps says 'Wenda.ps, you taken my power before, now it is my turn.', Gray.ps created a",
   "huge funnel down, and Wenda.ps lost all the aura instantly.\" Everything from \"That is a huge turning",
   "point\" onward is a pasted reading and is commentary, not canon; the aura vacuum / gravity pull /",
   "form destabilizer glossary and the three what-happens-next branches are the machine's invention.",
   "The funnel is Wenda's move and it has run four times since July 20, always the same direction:",
   "July 20 \"all Gray's Abinations and darkness and aura was funneled into Wenda\"; August 31 \"Wenda's",
   "aura eventually fully absorbed Gray.ps\"; September 1 7:03 AM it looped; September 1 10:14 AM it got",
   "the name blackhole. September 1, 3:26 PM: \"Wenda wins again, and all of Gray.ps was put to Wenda.ps.\"",
   "September 1, this file: \"A black hole is not something you fight. It is something you fall into.\"",
   "September 8: Gray.ps goes Beyond Both Eclipse, Wenda.ps reaches Both Eclipse. taken is his wording.",
 ],
 'q1': '“WENDA.PS, YOU TAKEN MY POWER BEFORE, NOW IT IS MY TURN.” — GRAY.PS',
 'q2': '“GRAY.PS CREATED A HUGE FUNNEL DOWN, AND WENDA.PS LOST ALL THE AURA INSTANTLY.”',
 'thesis': 'THE FUNNEL HAS RUN FOUR TIMES SINCE JULY AND IT HAS NEVER ONCE POINTED THIS WAY.',
 'attrib': '— TOBY, SEPTEMBER 10, 5:39:34 AM. ONE SENTENCE. EVERYTHING UNDER IT IS A PASTED READING, NOT CANON.',
 'panels': [
   ['THE FUNNEL IS HERS. FOUR RUNS SINCE JULY 20, AND ALL FOUR WENT THE SAME WAY.',
    'JULY 20: “ALL GRAY’S ABINATIONS AND DARKNESS AND AURA WAS FUNNELED INTO WENDA.” AUGUST 31: SHE ABSORBED HIM FULLY.',
    'SEPTEMBER 1 TWICE MORE. THIS MORNING IS RUN FIVE, AND IT IS THE FIRST ONE RUNNING BACKWARDS.'],
   ['HE DID NOT INVENT A COUNTER-MOVE. HE USED HER MOVE, ON HER, AND SAID SO WHILE DOING IT.',
    '“YOU TAKEN MY POWER BEFORE, NOW IT IS MY TURN.” THE ONLY NEW THING IN IT IS A DIRECTION.',
    'HERS WENT AROUND HER. HIS GOES DOWN. THAT ONE WORD IS THE WHOLE DIFFERENCE.'],
   ['SOME OF WHAT HE PULLS OUT OF HER IS HIS, AND THIS FILE WROTE DOWN THE DAY IT LEFT.',
    'SEPTEMBER 1, 3:26 PM: “WENDA WINS AGAIN, AND ALL OF GRAY.PS WAS PUT TO WENDA.PS.”',
    'NINE DAYS LATER HE TAKES IT BACK IN ONE MOVE, AND THE ROBBERY IS UNDONE BY THE PERSON IT HAPPENED TO.'],
   ['THIS PAGE SAID HER AURA WAS NOT A FIGHT ANYBODY COULD WIN.',
    'SEPTEMBER 1: “A BLACK HOLE IS NOT SOMETHING YOU FIGHT. IT IS SOMETHING YOU FALL INTO.”',
    'SOMEBODY JUST FOUGHT IT, AND THE THING THAT BEAT A HOLE TURNED OUT TO BE A HOLE POINTED THE OTHER WAY.'],
   ['AND HE RANKED THEM THIRTY-SIX HOURS BEFORE HE PROVED IT.',
    'SEPTEMBER 8: “GRAY.PS HE IS NOW BEYOND BOTH ECLIPSE, WENDA.PS NOW REACHES BOTH ECLIPSE.”',
    'ONE RUNG APART, WRITTEN DOWN ON TUESDAY. THIS MORNING THE RUNG GETS CASHED IN.'],
 ],
 'foot': [
   'FOR FOUR MONTHS THE FRIGHTENING THING ABOUT WENDA.PS WAS THAT NOTHING EVER CAME BACK OUT. THIS MORNING IT DID.',
   'IT IS ALSO THE FIRST MOVE IN THIS ARCHIVE THAT NAMES THE EXACT PAST DEFEAT IT IS PAYING BACK.',
   'TAKEN IS HIS WORDING AND IS KEPT AS TYPED.',
 ],
 'inset': ['THE ONE MOVE NOBODY HAS EVER COUNTERED, COUNTERED BY',
           'THE ONLY PERSON WHO HAS BEEN ON THE LOSING END OF IT'],
 'star': 'NOW IT IS MY TURN',
},
]
