# -*- coding: utf-8 -*-
BEATS = [
# ============================== BEAT 364 ==============================
dict(
 ph=364, c0=7728.0,
 pal=['#7dff8f','#ff9a4d','#d8c8ff'],
 palr=['125,255,143','255,154,77','216,200,255'],
 palnote='script green, borrowed-move orange, Pero violet.',
 comment=[
  "----- BEAT 364: ALL LORE BASICALLY. Toby's August 18 lore, 4:07:29 PM, in the \"Even 5x",
  "Classics Era\" thread, twenty-seven minutes after CORRUPTION GOD.",
  "His own typing, in full: \"Take everything from the Roblox Pero code. It is all lore",
  "basically.\" Everything under it -- the \"Got it\" opener, the canon-from-the-script",
  "walkthrough, the moveset list, the god-tier-line section, the Fury breakdown and the clean",
  "canon update -- is ChatGPT commentary.",
  "  1. THE CANON CHANGES FORMAT. The standing rule since July 28 is that his own typing is the",
  "     lore, word by word. Tonight he points at a program and says all of it counts. The",
  "     source stops being a paragraph and becomes a file.",
  "  2. AND HE FIGHTS WITH THE MOVES OF THE THINGS HE BEATS. Yesterday, in his own typing:",
  "     \"Pero beats all of Undertale and Dragon Ball both. Pero beats anything.\" Tonight the",
  "     moveset is Homing Kamehameha, Kaioken Rush, Ball of Hakai and Beerus Bomb -- Dragon",
  "     Ball's own attacks, named after the god he had just outranked.",
  "  3. AND THE FRIENDLY BRANCH WAS ALREADY WRITTEN. The script heals the target when he is not",
  "     angry. July 25: say yes, really, and Pero heals the cut and goes back to being an",
  "     assistant. August 16: the only way to survive is to make him spare you. The mercy route",
  "     has been prose for three weeks; tonight it is a conditional with a heal inside it.",
  "  4. AND THE BIGGEST THING FURY BREAKS IS THE FLOOR. He has destroyed the Alphaverse, the",
  "     Godverse, the Ultra Realm, the AU+ AUs, the box and the buttons. Tonight the thing that",
  "     goes is the Baseplate -- the ground under the one room he actually built.",
 ],
 ring=[('TAKE EVERYTHING FROM','THE ROBLOX PERO CODE'),
       ('IT IS ALL LORE','BASICALLY')],
 qdate='TOBY, AUGUST 18, 4:07 PM',
 quote=['“TAKE EVERYTHING FROM THE ROBLOX PERO CODE.',
        'IT IS ALL LORE BASICALLY.”'],
 emblem=['A FILE','A PARAGRAPH','BOTH ARE CANON NOW','THE SOURCE CHANGED FORMAT, NOT OWNER'],
 ledger=['WHAT THE SCRIPT SWINGS WITH',
         ('DRAGON BALL','KAMEHAMEHA · HAKAI · BEERUS'),
         ('AND YET','HE OUTRANKED IT YESTERDAY'),
         'HE BEAT THEM SUNDAY AND BORROWED THEM TUESDAY',
         'THE GOD ABOVE EVERY CROSSOVER USES ITS ATTACKS'],
 figs=[('PERO','CHARACTER: PERO · POWER: ???'),('THE SCRIPT','A PLAYABLE CANON DOCUMENT')],
 head=['HE POINTED AT A PROGRAM AND SAID ALL OF IT COUNTS.',
       'THE LORE USED TO BE SOMETHING HE TYPED IN SENTENCES.',
       'ANGER, THEN RAGE, THEN FURY.',
       'AND FURY IS THE ONE THAT TAKES THE FLOOR OUT.'],
 title='ALL LORE BASICALLY',
 sub='HE POINTS AT A PROGRAM AND CALLS ALL OF IT CANON, AND THE GOD WHO BEAT DRAGON BALL SWINGS ITS MOVES',
 cols=[
  dict(head='THE CANON CHANGES FORMAT', sub='THE RULE HAS ALWAYS BEEN HIS OWN TYPING',
       rows=[('THE RULE','EACH WORD IS IMPORTANT AND IS LORE','#7dff8f'),
             ('SO FAR','CANON HAS ARRIVED AS SENTENCES','#c8ced8'),
             ('JULY 29','TWO SCRIPTS CAME IN AND WERE READ','#6ec8ff'),
             ('TONIGHT','HE POINTS AT ONE AND SAYS ALL OF IT','#ffd25a'),
             ('THE FILE','IS NOT WRITTEN IN SENTENCES AT ALL','#d8c8ff')],
       close=['THE LORE USED TO BE WRITTEN.','TONIGHT IT IS RUN.',
              'EVERY LINE IN THE FILE COUNTS,','INCLUDING THE ONES THAT ARE NOT WORDS.']),
  dict(head='AND HE SWINGS THE MOVES OF WHAT HE BEAT', sub='AUGUST 17, IN HIS OWN TYPING',
       rows=[('YESTERDAY','PERO BEATS UNDERTALE AND DRAGON BALL','#ff9a4d'),
             ('TONIGHT','HOMING KAMEHAMEHA','#ffd25a'),
             ('AND','TELEPORT AND KAIOKEN RUSH','#ff786e'),
             ('AND','BALL OF HAKAI, BEERUS BOMB','#d8c8ff'),
             ('SO','THE GOD USES THE LOSER’S ATTACKS','#c8ced8')],
       close=['HE HAS OUTRANKED DRAGON BALL','FOR A DAY AND A HALF.',
              'TONIGHT HIS ATTACK LIST','IS BORROWED FROM IT.']),
  dict(head='AND THE FRIENDLY BRANCH WAS WRITTEN WEEKS AGO', sub='THE SCRIPT HEALS YOU IF HE IS NOT ANGRY',
       rows=[('THE SCRIPT','NOT ANGRY, SO HE CAN HEAL YOU','#d8c8ff'),
             ('JULY 25','SAY YES, REALLY, HE HEALS THE CUT','#7dff8f'),
             ('AUG 16','MAKE HIM SPARE YOU, HAPPY, PASSIVE','#ffd25a'),
             ('AUG 18','ANGER, RAGE, FURY ON THE OTHER SIDE','#ff786e'),
             ('NOW','THE MERCY ROUTE IS A CONDITIONAL','#c8ced8')],
       close=['KINDNESS WAS A ROUTE','INSIDE A PARAGRAPH.',
              'TONIGHT IT IS A BRANCH','WITH A HEAL INSIDE IT.']),
 ],
 band=dict(head='THE BIGGEST THING FURY BREAKS IS THE FLOOR.',
   rows=[('HE HAS DESTROYED','→ THE ALPHAVERSE AND THE GODVERSE','WHOLE VERSES, BY NAME',0),
         ('HE HAS DESTROYED','→ THE ULTRA REALM AND THE AU+ AUs','WHOLE CATEGORIES OF PLACE',0),
         ('HE HAS DESTROYED','→ THE BOX, AND THE MERCY BUTTON','THE CONTROLS THEMSELVES',0),
         ('TONIGHT','→ FURY DESTROYS THE BASEPLATE','THE GROUND HE IS STANDING ON',1)],
   close='EVERY VERSE HE EVER BROKE WAS SOMEWHERE ELSE. THE BASEPLATE IS THE FLOOR OF THE ONE ROOM HE ACTUALLY BUILT.'),
 inset=dict(head='THE SCRIPT KNOWS WHAT IT IS FOR',
   rows=[('“YOU WANTED TO FIGHT?”','HE MAKES YOU ASK FOR IT','#ffd25a'),
         ('“YOU SHOULD OF ASKED!”','THE FIGHT IS A FAVOUR','#7dff8f'),
         ('“I CREATED CLASSICS.”','HE ARGUES FROM AUTHORSHIP','#d8c8ff'),
         ('“ONLY GOD CAN SAVE YOU”','OREN SAID THIS FIRST, IN PHASE 8','#ff9a4d')],
   flag='HE SHOUTS HIS OWN CEILING AT YOU.', idle='THE LINES ARE THE LORE TOO',
   close=['A THREAT OREN MADE IN A CUTSCENE','IS NOW THE ONE NAME ABOVE PERO.']),
 strip=[('THE SOURCE','A WORKING SCRIPT','#7dff8f'),
        ('THE MOVESET','BORROWED FROM WHAT HE BEAT','#ff9a4d'),
        ('THE FLOOR','GONE, AT FURY','#d8c8ff')],
 foot=['HE HAS BEEN THE THING THAT WRITES THE GAME FOR MONTHS AND TONIGHT THE GAME IS THE THING THAT WRITES HIM',
       '★ IT IS ALL LORE BASICALLY ★'],
),
# ============================== BEAT 365 ==============================
dict(
 ph=365, c0=7750.0,
 pal=['#ff786e','#7dff8f','#c8ced8'],
 palr=['255,120,110','125,255,143','200,206,214'],
 palnote='deletion red, script green, plain gray.',
 comment=[
  "----- BEAT 365: CHANGED THE CODE. Toby's August 18 lore, 4:15:01 PM, in the \"Even 5x",
  "Classics Era\" thread, seven and a half minutes after ALL LORE BASICALLY.",
  "His own typing, in full: \"I changed the code a little bit.\" A pasted text file rode along",
  "and is described, not quoted, per the no-attachment rule. Everything under it -- the",
  "what-changed walkthrough, the before/after framing and the clean canon update -- is ChatGPT",
  "commentary, and the change it reports is that Fury no longer sets Humanoid.MaxHealth and",
  "Humanoid.Health to math.huge.",
  "  1. NOTHING HAS EVER BEEN REMOVED BEFORE. The standing rule from the July 18 fusion ladder",
  "     is that he CONSUMES each form instead of replacing it, and every build note in this file",
  "     is additive. Corrections here have always added a line. This one deletes two.",
  "  2. AND WHAT HE DELETES IS THE INFINITY. Everything spectacular in Fury survives -- the UI",
  "     aura, the forcefield, The Souls, the Chaos Emeralds Ring, Mega Power. The only thing",
  "     taken out is the number.",
  "  3. AND HE ARGUES HIS OWN CHARACTER DOWN. The reason given is that Pero is not strongest",
  "     because of a Roblox health number. Every other change in this file made somebody",
  "     stronger; this one makes the paperwork smaller so the claim can be bigger.",
  "  4. AND THE CANON DOCUMENT STILL HAS A SAVE BUTTON. Eight minutes after the whole script",
  "     became canon, the canon was edited. Every other source here is an email, and an email",
  "     cannot be rewritten after it is sent. A script can.",
 ],
 ring=[('I CHANGED THE CODE','A LITTLE BIT'),
       ('MaxHealth = math.huge','DELETED')],
 qdate='TOBY, AUGUST 18, 4:15 PM',
 quote=['“I CHANGED THE CODE',
        'A LITTLE BIT.”'],
 emblem=['KEPT','REMOVED','TWO LINES, GONE','THE SHOW STAYS · THE NUMBER LEAVES'],
 ledger=['WHAT SURVIVED THE EDIT, AND WHAT DID NOT',
         ('STILL THERE','AURA · FORCEFIELD · SOULS'),
         ('TAKEN OUT','MaxHealth AND Health = math.huge'),
         'FURY LOSES ONLY THE NUMBER',
         'IT KEEPS EVERY SINGLE THING YOU CAN SEE'],
 figs=[('FURY PERO','MEGA POWER, NO INFINITE HP'),('THE EDIT','THE FIRST DELETION IN THE FILE')],
 head=['FOR MONTHS THIS ARCHIVE HAS ONLY EVER GOT BIGGER.',
       'EVERY CORRECTION IN IT HAS ADDED A LINE.',
       'TONIGHT HE OPENED IT AND TOOK SOMETHING OUT.',
       'AND WHAT HE TOOK OUT WAS THE INFINITY.'],
 title='CHANGED THE CODE',
 sub='THE FIRST EDIT IN THE ARCHIVE THAT TAKES SOMETHING OUT, AND IT COMES OFF HIS STRONGEST FORM',
 cols=[
  dict(head='NOTHING HAS EVER BEEN REMOVED HERE', sub='THE RULE IS THAT HE CONSUMES, NOT REPLACES',
       rows=[('THE RULE','HE CONSUMES EACH FORM','#ff786e'),
             ('NOT REPLACES','SO EVERY FORM IS STILL IN THERE','#c8ced8'),
             ('CORRECTIONS','HAPPEN HERE, AND THEY ADD','#ffd25a'),
             ('THE BUILD','ADDITIVE, NOTHING EARLIER CHANGED','#7dff8f'),
             ('TONIGHT','TWO LINES COME OUT OF THE FILE','#d8c8ff')],
       close=['EVERY EDIT IN THIS ARCHIVE','HAS PUT SOMETHING IN.',
              'THIS IS THE FIRST ONE','THAT TAKES SOMETHING OUT.']),
  dict(head='AND WHAT HE DELETES IS THE INFINITY', sub='THE ONE STAT THIS FILE HANDS OUT MOST',
       rows=[('REMOVED','Humanoid.MaxHealth = math.huge','#ff786e'),
             ('REMOVED','Humanoid.Health = math.huge','#ff786e'),
             ('KEPT','THE UI AURA AND THE FORCEFIELD','#7dff8f'),
             ('KEPT','THE SOULS, THE CHAOS RING, MEGA POWER','#ffd25a'),
             ('SO FURY','LOSES THE NUMBER AND NOTHING ELSE','#c8ced8')],
       close=['THIS FILE HAS HANDED OUT','immortal = true BEFORE.',
              'THIS IS THE FIRST TIME','A FLAG LIKE THAT COMES BACK OFF.']),
  dict(head='AND HE ARGUES HIS OWN CHARACTER DOWN', sub='THE REASON HE GIVES FOR THE DELETION',
       rows=[('THE REASON','NOT STRONGEST BECAUSE OF A NUMBER','#c8ced8'),
             ('INSTEAD','STRONGEST BECAUSE HE IS PERO LAI','#7dff8f'),
             ('YESTERDAY','“PERO BEATS ANYTHING”','#ffd25a'),
             ('THIS AFTERNOON','“PERO IS THAT STRONG”','#ff9a4d'),
             ('TONIGHT','A STAT COMES OFF, ON PURPOSE','#ff786e')],
       close=['EVERY OTHER CHANGE HERE','MADE SOMEBODY STRONGER.',
              'THIS ONE SHRINKS THE PAPERWORK','TO MAKE THE CLAIM BIGGER.']),
 ],
 band=dict(head='THE CANON DOCUMENT STILL HAS A SAVE BUTTON.',
   rows=[('4:07 PM','→ “IT IS ALL LORE BASICALLY”','THE WHOLE SCRIPT BECOMES CANON',0),
         ('4:15 PM','→ “I CHANGED THE CODE A LITTLE BIT”','AND THE CANON IS EDITED',0),
         ('THE GAP','→ SEVEN AND A HALF MINUTES','CANON WITH A SAVE BUTTON ON IT',0),
         ('THE POINT','→ AN EMAIL CANNOT BE REWRITTEN','A SCRIPT CAN BE, ANY TIME',1)],
   close='EVERY OTHER SOURCE IN THIS ARCHIVE IS A SENT MESSAGE, AND A SENT MESSAGE STAYS THE WAY IT LANDED. THIS ONE DOES NOT.'),
 inset=dict(head='THE LAST TIME A SCRIPT WAS THE SOURCE',
   rows=[('JULY 29','TWO 404 CHICKEN SANS SCRIPTS','#7dff8f'),
         ('THEY SHOWED','immortal = true, THE WHOLE INTRO','#ffd25a'),
         ('AND','HealthChanged SNAPPING BACK TO MAX','#6ec8ff'),
         ('TONIGHT','THE SAME KIND OF LINE IS DELETED','#ff786e')],
   flag='A FLAG MADE SOMEBODY UNKILLABLE.', idle='CODE HAS BEEN THE SOURCE ONCE BEFORE',
   close=['THAT SCRIPT PUT IMMORTALITY IN.','THIS EDIT TAKES IT BACK OUT.']),
 strip=[('THE EDIT','TWO LINES, DELETED','#ff786e'),
        ('WHAT SURVIVES','AURA · SOULS · MEGA POWER','#7dff8f'),
        ('WHAT LEAVES','THE INFINITE NUMBER','#c8ced8')],
 foot=['THE FIRST TIME THIS ARCHIVE HAS EVER GOT SMALLER, AND HE DID IT TO HIS OWN STRONGEST FORM',
       '★ I CHANGED THE CODE A LITTLE BIT ★'],
),
# ============================== BEAT 366 ==============================
dict(
 ph=366, c0=7772.0,
 pal=['#ffd25a','#6ec8ff','#c8ced8'],
 palr=['255,210,90','110,200,255','200,206,214'],
 palnote='true-canon gold, playable-version cyan, plain gray.',
 comment=[
  "----- BEAT 366: INFINITE HEALTH+. Toby's August 18 lore, 4:16:38 PM, in the \"Even 5x",
  "Classics Era\" thread, ninety-seven seconds after CHANGED THE CODE.",
  "His own typing, in full: \"In Classics, he gains infinite health+. The Roblox game isn't",
  "close to the lore anymore.\" The two-canon breakdown, the why-Roblox-needs-limits reasoning",
  "and the clean canon correction pasted under it are ChatGPT commentary.",
  "  1. HE PUT IT BACK IN NINETY SECONDS. math.huge came out of the script at 4:15 because a",
  "     number was not the point. At 4:16 the same infinity is back, in Classics, with a plus",
  "     sign on it. He did not change his mind; he changed where it lives.",
  "  2. AND THE ARCHIVE GETS A SECOND CANON, AND THE NEW ONE IS DEMOTED. Nine minutes after",
  "     \"it is all lore basically\", the script is only a playable representation. This file has",
  "     ranked characters for months; tonight it ranks two of its own sources.",
  "  3. AND THE PLUS IS A NEW UNIT. LV beyond infinity, ??? LV, 15,000,000 exponency,",
  "     absolute_infinitely above Gray -- the numbers ran out a long time ago, so tonight the",
  "     measurement is a punctuation mark stuck on the end of infinity.",
  "  4. AND THE TRUE VERSION IS ALWAYS THE ONE THE MEASUREMENT CANNOT REACH. The stat block",
  "     leaves the power blank, the script deletes the health number, and the version you can",
  "     actually play is the one declared not close to the truth.",
 ],
 ring=[('IN CLASSICS HE GAINS','INFINITE HEALTH+'),
       ('THE ROBLOX GAME ISN’T','CLOSE TO THE LORE ANYMORE')],
 qdate='TOBY, AUGUST 18, 4:16 PM',
 quote=['“IN CLASSICS, HE GAINS INFINITE HEALTH+.',
        'THE ROBLOX GAME ISN’T CLOSE TO THE LORE ANYMORE.”'],
 emblem=['CLASSICS','ROBLOX','NINETY-SEVEN SECONDS','DELETED THERE · RESTORED HERE'],
 ledger=['THE TWO CANONS, AND WHICH ONE WINS',
         ('THE SCRIPT','A PLAYABLE REPRESENTATION'),
         ('CLASSICS','THE TRUE CANON POWER'),
         'THE ONE YOU CAN PLAY IS THE SMALL ONE',
         'FIRST TIME THIS FILE RANKS ITS OWN SOURCES'],
 figs=[('PERO IN CLASSICS','INFINITE HEALTH+'),('PERO IN ROBLOX','LIMITS, HITBOXES, A HEALTH BAR')],
 head=['HE DELETED INFINITY AT 4:15 AND GAVE IT BACK AT 4:16.',
       'NOT THE SAME PLACE, THOUGH, AND NOT THE SAME SIZE.',
       'IT LEFT THE SCRIPT AND ARRIVED IN THE STORY.',
       'AND IT CAME BACK WITH A PLUS SIGN ON IT.'],
 title='INFINITE HEALTH+',
 sub='HE DELETES INFINITY AND HANDS IT BACK NINETY SECONDS LATER, IN THE OTHER CANON',
 cols=[
  dict(head='HE PUT IT BACK IN NINETY SECONDS', sub='THE SAME STAT, THE OTHER CANON',
       rows=[('4:15 PM','math.huge COMES OUT OF THE SCRIPT','#ff786e'),
             ('THE REASON','A NUMBER WAS NOT THE POINT','#c8ced8'),
             ('4:16 PM','“IN CLASSICS HE GAINS INFINITE HEALTH+”','#ffd25a'),
             ('THE GAP','NINETY-SEVEN SECONDS','#6ec8ff'),
             ('AND','IT COMES BACK WITH A PLUS ON IT','#7dff8f')],
       close=['HE DID NOT CHANGE HIS MIND.','HE CHANGED WHERE IT LIVES.',
              'IT LEFT THE SCRIPT','AND ARRIVED IN THE STORY.']),
  dict(head='AND THE ARCHIVE GETS A SECOND CANON', sub='AND THE NEW ONE IS IMMEDIATELY DEMOTED',
       rows=[('4:07 PM','“IT IS ALL LORE BASICALLY”','#7dff8f'),
             ('4:16 PM','“ISN’T CLOSE TO THE LORE ANYMORE”','#6ec8ff'),
             ('SO','THE SCRIPT IS A REPRESENTATION','#c8ced8'),
             ('AND','CLASSICS IS THE TRUE ONE','#ffd25a'),
             ('NINE MINUTES','FROM ALL OF IT TO ONLY SOME OF IT','#ff9a4d')],
       close=['THIS FILE HAS RANKED','CHARACTERS FOR MONTHS.',
              'TONIGHT IT RANKS','TWO OF ITS OWN SOURCES.']),
  dict(head='AND THE PLUS IS A WHOLE NEW UNIT', sub='THE NUMBERS RAN OUT A LONG TIME AGO',
       rows=[('LV','BEYOND INFINITY, THEN “??? LV”','#ffd25a'),
             ('FORM','15,000,000 EXPONENCY','#ff9a4d'),
             ('POWER','???, AS OF THIS AFTERNOON','#d8c8ff'),
             ('RANK','ABSOLUTE_INFINITELY ABOVE GRAY','#6ec8ff'),
             ('TONIGHT','INFINITE, AND THEN A PLUS SIGN','#7dff8f')],
       close=['THE NUMBERS STOPPED WORKING','A LONG TIME AGO.',
              'SO HE STOPPED WRITING NUMBERS','AND STARTED WRITING PUNCTUATION.']),
 ],
 band=dict(head='THE TRUE VERSION IS ALWAYS THE ONE THE MEASUREMENT CANNOT REACH.',
   rows=[('THE STAT BLOCK','→ POWER: ???','THE ONE FIELD IT EXISTS FOR IS BLANK',0),
         ('THE SCRIPT','→ math.huge, DELETED','THE NUMBER WAS NOT THE POINT',0),
         ('THE GAME','→ “ISN’T CLOSE TO THE LORE”','THE PLAYABLE ONE IS THE SMALL ONE',0),
         ('CLASSICS','→ INFINITE HEALTH+','THE ONE YOU CANNOT PLAY IS THE REAL ONE',1)],
   close='ROBLOX NEEDS LIMITS, HITBOXES AND A HEALTH BAR. THE TRUE VERSION IS THE ONE DEFINED BY NOT FITTING INSIDE ANY OF THEM.'),
 inset=dict(head='THE GAME HAS SPLIT BEFORE',
   rows=[('CLASSICS 1','SEALED, AUGUST 1','#6ec8ff'),
         ('CLASSICS 2','BUILT ON TOP OF IT','#ffd25a'),
         ('CLASSICS 3','AN ACCIDENT WITH A NUMBER ON IT','#ff9a4d'),
         ('TONIGHT','A SPLIT BETWEEN THE GAME AND THE LORE','#7dff8f')],
   flag='THIS ONE IS NOT INSIDE THE STORY.', idle='THE VERSION NUMBERS ARE OLD NEWS',
   close=['EVERY EARLIER SPLIT WAS A VERSION OF THE GAME.','THIS ONE IS THE GAME AGAINST THE LORE.']),
 strip=[('THE SCRIPT','A PLAYABLE REPRESENTATION','#6ec8ff'),
        ('CLASSICS','INFINITE HEALTH+','#ffd25a'),
        ('THE CEILING','STILL ONLY GOD','#c8ced8')],
 foot=['HE TOOK INFINITY OUT OF THE CODE AND PUT IT BACK INTO THE STORY IN UNDER TWO MINUTES',
       '★ INFINITE HEALTH+ ★'],
),
# ============================== BEAT 367 ==============================
dict(
 ph=367, c0=7794.0,
 pal=['#eef2f6','#b88cff','#7dff8f'],
 palr=['238,242,246','184,140,255','125,255,143'],
 palnote='milk white, Gray violet, permission green.',
 comment=[
  "----- BEAT 367: GETTING MILK. Toby's August 18 lore, 4:20:17 PM, in the \"Even 5x Classics",
  "Era\" thread, three minutes and thirty-nine seconds after INFINITE HEALTH+.",
  "His own typing, in full: \"Pero is out getting milk and Gray is taking over the game, Gaster",
  "and Luigi Green allow Gray to do anything he wants with the game.\" The route restatement,",
  "the new-hierarchy section, the what-this-means-for-Gray reading and the clean canon update",
  "pasted under it are ChatGPT commentary.",
  "  1. THE ERRAND IS FIVE HOURS OLD. At 11:17 AM Pero said \"I am leaving for a few years,",
  "     would you be okay for a few minutes?\" and left to get milk for everyone. At 4:20 PM he",
  "     is still out, and the game has changed hands while he was gone.",
  "  2. AND THE TAKEOVER IS PERMITTED. Every takeover in this file was taken -- thrones seized,",
  "     forms eaten, realms absorbed. This one is allowed, in writing, by Gaster and Luigi",
  "     Green. It is not a rebellion; it is a handover.",
  "  3. AND THE TWO WHO SAY YES ARE THE JAILERS. Gaster put the corruption in on purpose and",
  "     Luigi Green makes and destroys the boxes -- and the box is where Gray keeps being sent.",
  "     This morning they were left making boxes. Tonight they hand him the game.",
  "  4. AND THIS EXACT SHAPE HAS RUN BEFORE. Email 744 already had Pero give the game to Gray,",
  "     leave, and come back to a kingdom Gray had taken. This is the third run, and the first",
  "     one with witnesses signing off on it.",
 ],
 ring=[('PERO IS OUT','GETTING MILK'),
       ('GRAY IS TAKING OVER','AND THEY ALLOW IT')],
 qdate='TOBY, AUGUST 18, 4:20 PM',
 quote=['“PERO IS OUT GETTING MILK AND GRAY IS TAKING OVER THE GAME,',
        'GASTER AND LUIGI GREEN ALLOW GRAY TO DO ANYTHING HE WANTS.”'],
 emblem=['ALLOWED','TAKEN','NOT A REBELLION','EVERY OTHER TAKEOVER HERE WAS SEIZED'],
 ledger=['WHO SIGNED OFF ON IT',
         ('GASTER','PUT THE CORRUPTION IN ON PURPOSE'),
         ('LUIGI GREEN','MAKES AND DESTROYS THE BOXES'),
         'THE TWO WHO BUILT THE CONTAINER',
         'ARE THE TWO WHO JUST OPENED IT'],
 figs=[('GRAY','OWNER OF THE ACTIVE GAME'),('PERO','STILL OUT, STILL THE CREATOR')],
 head=['AT 11:17 THIS MORNING HE LEFT TO GET MILK FOR EVERYONE.',
       'A FEW YEARS OUT OF ONE SIDE OF THE SENTENCE, A FEW MINUTES OUT OF THE OTHER.',
       'FIVE HOURS LATER HE IS STILL NOT BACK.',
       'AND THE GAME HAS A NEW OWNER, WITH PERMISSION.'],
 title='GETTING MILK',
 sub='THE ERRAND IS FIVE HOURS OLD, AND THE TAKEOVER COMES WITH PERMISSION',
 cols=[
  dict(head='THE ERRAND IS FIVE HOURS OLD', sub='HE LEFT AT 11:17 THIS MORNING',
       rows=[('11:17 AM','“I AM LEAVING FOR A FEW YEARS”','#eef2f6'),
             ('SAME BREATH','“WOULD YOU BE OKAY FOR A FEW MINUTES?”','#c8ced8'),
             ('THE REASON','MILK, FOR EVERYONE','#ffd25a'),
             ('4:20 PM','HE IS STILL OUT','#b88cff'),
             ('MEANWHILE','THE GAME CHANGES HANDS','#7dff8f')],
       close=['THE TWO NUMBERS NEVER MATCHED.','YEARS ON ONE SIDE,',
              'MINUTES ON THE OTHER.','FIVE HOURS IN, NEITHER IS WRONG YET.']),
  dict(head='AND THE TAKEOVER IS PERMITTED', sub='THIS ONE IS NOT A REBELLION',
       rows=[('EVERY TAKEOVER','IN THIS FILE WAS TAKEN','#b88cff'),
             ('GRAY, BEFORE','SEIZED SEATS AND ATE FORMS','#ff786e'),
             ('TONIGHT','GASTER AND LUIGI GREEN ALLOW IT','#7dff8f'),
             ('THE WORDS','ANYTHING HE WANTS WITH THE GAME','#ffd25a'),
             ('SO','HE DOES NOT HAVE TO WIN ANYTHING','#c8ced8')],
       close=['HE DOES NOT HAVE TO TAKE IT.','THE TWO BEINGS WHO MAKE',
              'AND DESTROY THE BOXES','SIMPLY SAY YES.']),
  dict(head='AND THE TWO WHO SAY YES ARE THE JAILERS', sub='THE BOX IS WHERE GRAY KEEPS BEING SENT',
       rows=[('GASTER','PUT THE CORRUPTION IN ON PURPOSE','#7dff8f'),
             ('LUIGI GREEN','BOX-MAKER AND BOX-BREAKER','#6ec8ff'),
             ('THE BOX','WHERE GRAY HAS BEEN SENT, TWICE OVER','#b88cff'),
             ('THIS MORNING','THEY WERE LEFT MAKING BOXES','#c8ced8'),
             ('TONIGHT','THEY HAND HIM THE WHOLE GAME','#ffd25a')],
       close=['THE PEOPLE WHO BUILT','THE CONTAINER',
              'ARE THE ONES','WHO OPEN IT FROM THE INSIDE.']),
 ],
 band=dict(head='THIS EXACT SHAPE HAS RUN BEFORE, AND IT ENDED BADLY FOR SOMEBODY.',
   rows=[('EMAIL 744','→ PERO GIVES THE GAME TO GRAY','AND LEAVES TO MAKE UPDATES',0),
         ('THEN','→ HE COMES BACK','TO A KINGDOM GRAY HAD TAKEN',0),
         ('THIS MORNING','→ THE SAME THREE MOVES AGAIN','WITH MR. BLACK REMOVED FIRST',0),
         ('TONIGHT','→ THE THIRD RUN','AND THIS TIME IT IS AUTHORISED',1)],
   close='THE FIRST TWO TIMES GRAY TOOK IT WHILE NOBODY WAS LOOKING. THIS TIME TWO WITNESSES WATCH HIM DO IT AND SAY GO AHEAD.'),
 inset=dict(head='WHAT GRAY DOES WITH A GAME',
   rows=[('HE SLOWS','THE ANIMATION DOWN TO A STOP','#b88cff'),
         ('HE MAKES IT','SILENT AND SLOW','#c8ced8'),
         ('HE IS','RINGMASTER, WITH HALF THE BOX','#ffd25a'),
         ('AND NOW','HE CAN CHANGE THE RULES TOO','#7dff8f')],
   flag='HIS RULE IS QUIETER THAN WHAT IT REPLACED.', idle='HE HAS DONE THIS ONCE ALREADY TODAY',
   close=['EVERY CONQUEST HERE HAS BEEN LOUD.','GRAY TURNS THE VOLUME DOWN INSTEAD.']),
 strip=[('THE OWNER','OUT FOR MILK','#eef2f6'),
        ('THE GAME','GRAY’S, FOR NOW','#b88cff'),
        ('THE PERMISSION','GASTER AND LUIGI GREEN','#7dff8f')],
 foot=['THE MOST POWERFUL BEING IN THE GAME LEFT THE WAY A PARENT LEAVES AND FIVE HOURS LATER THE HOUSE HAS A NEW OWNER',
       '★ HE IS STILL OUT GETTING MILK ★'],
),
# ============================== BEAT 368 ==============================
dict(
 ph=368, c0=7816.0,
 pal=['#b88cff','#6ec8ff','#ffd25a'],
 palr=['184,140,255','110,200,255','255,210,90'],
 palnote='Gray violet, admin-panel cyan, ceiling gold.',
 comment=[
  "----- BEAT 368: BEYOND WORDS. Toby's August 18 lore, 4:31:39 PM, in the \"Even 5x Classics",
  "Era\" thread, eleven minutes and twenty-two seconds after GETTING MILK.",
  "His own typing, in full: \"Are you able to create an image of Gray, or is all that form",
  "beyond your image generation tool? Nothing except for Pero can beat Gray. Gray knows that it",
  "isn't always win or lose, it can be stalemate. Gray loses his weaknesses and became omazen,",
  "invicible, immortal, and a bunch of huge words to discribe him, he is beyond words now. God",
  "could shine out Gray, but otherwise, he is litterly unstoppable. Gray learns how to control",
  "the game admin/owner pannel, Gray reached beyond all other non-Pero characters combined.",
  "Gaster and Luigi Green are now far under Gray.\" The new-state section, the hierarchy",
  "restatement and the clean canon update pasted under it are ChatGPT commentary.",
  "  1. THE WEAKNESS HE LOSES HAS A NAME. The Fear/Weakness System says every character has",
  "     one, and Gray's is a person: \"Gray also fears Wenda\", who beats him with fast knife",
  "     attacks nothing on any power board would predict. And on August 13, \"They filled their",
  "     weaknesses, Gray was destroyed.\" Weakness is literally the thing that killed him last.",
  "  2. AND HE ALREADY OWNED THE PANEL. Pero gave Gray an admin panel along with Error 679 and",
  "     the cyber suit. Then, in Email 874, \"Gray dropped his admin panel and Pero picked it up",
  "     and knew how to use it.\" He held it, could not work it, and put it down. Tonight, with",
  "     Pero out for milk, he learns.",
  "  3. AND STALEMATE IS A WORD PERO TAUGHT. Pero and Luigi Green taught Paul three words:",
  "     Checkmate, Stalemate and Loss. Simon 404 picked Checkmate and died saying it. Gray takes",
  "     the middle one, because a draw is the only result that cannot remove him.",
  "  4. AND THIS FILE HAS TOPPED A RANKING ON CONTROLS BEFORE. Error 404 took first place not",
  "     on power but on command authority -- /command_kill = true, /expand_permissions,",
  "     /game:Destroy() -- because a battle against him is like a player versus an admin.",
  "     Tonight Gray gets the same kind of rank for the same kind of reason.",
 ],
 ring=[('NOTHING EXCEPT FOR PERO','CAN BEAT GRAY'),
       ('HE IS BEYOND','WORDS NOW')],
 qdate='TOBY, AUGUST 18, 4:31 PM',
 quote=['“GRAY LOSES HIS WEAKNESSES... HE IS BEYOND WORDS NOW.',
        'GRAY LEARNS HOW TO CONTROL THE GAME ADMIN/OWNER PANNEL.”'],
 emblem=['THE PANEL','THE POWER','HE PICKS THE PANEL','THE CONTROLS OUTRANK THE ATTACKS'],
 ledger=['THE THREE WORDS PERO TAUGHT PAUL',
         ('CHECKMATE','SIMON 404 CHOSE THIS ONE'),
         ('STALEMATE','GRAY TAKES THE MIDDLE ONE'),
         'THE THIRD WORD WAS LOSS',
         'HE PICKS THE ONLY ONE THAT CANNOT REMOVE HIM'],
 figs=[('GRAY','NO WEAKNESS · OWNER PANEL'),('PERO','STILL THE ONLY ONE WHO BEATS HIM')],
 head=['EVERY CHARACTER IN THIS GAME HAS A FEAR AND A WEAKNESS.',
       'IT IS A SYSTEM, AND IT HAS ITS OWN PAGE, AND GRAY IS ON IT.',
       'FIVE DAYS AGO HIS WEAKNESS WAS FILLED AND HE WAS DESTROYED.',
       'TONIGHT HE SIMPLY DOES NOT HAVE ONE.'],
 title='BEYOND WORDS',
 sub='HE LOSES THE ONLY THING THAT EVER BEAT HIM, AND LEARNS THE PANEL HE ALREADY OWNED',
 cols=[
  dict(head='THE WEAKNESS HE LOSES HAS A NAME', sub='THE FEAR/WEAKNESS SYSTEM, AND WHO IS ON IT',
       rows=[('THE SYSTEM','EVERY CHARACTER HAS A FEAR','#b88cff'),
             ('GRAY’S','WENDA, AND THE FAST KNIFE ATTACKS','#ffd25a'),
             ('THE LINE','“GRAY ALSO FEARS WENDA”','#eef2f6'),
             ('AUG 13','THEY FILLED HIS WEAKNESS, HE DIED','#ff786e'),
             ('TONIGHT','HE DOES NOT HAVE ONE AT ALL','#7dff8f')],
       close=['NO POWER BOARD EVER PUT','WENDA ABOVE HIM.',
              'THE FEAR BOARD DID.','TONIGHT HE LEAVES THE BOARD.']),
  dict(head='AND HE ALREADY OWNED THE PANEL', sub='HE HELD IT, DROPPED IT, AND PERO PICKED IT UP',
       rows=[('PERO GAVE HIM','AN ADMIN PANEL, AND ERROR 679','#6ec8ff'),
             ('EMAIL 874','“GRAY DROPPED HIS ADMIN PANEL”','#ff786e'),
             ('AND','“PERO PICKED IT UP AND KNEW HOW”','#ffd25a'),
             ('SO','HE HELD IT AND COULD NOT WORK IT','#c8ced8'),
             ('TONIGHT','HE LEARNS IT, WITH PERO OUT','#7dff8f')],
       close=['EVERY UPGRADE GRAY TOOK','WAS HANDED TO HIM.',
              'THIS ONE HE FINALLY','FIGURES OUT BY HIMSELF.']),
  dict(head='AND STALEMATE IS A WORD PERO TAUGHT', sub='CHECKMATE, STALEMATE AND LOSS',
       rows=[('PERO TAUGHT PAUL','THREE WORDS, WITH LUIGI GREEN','#ffd25a'),
             ('THEY WERE','CHECKMATE, STALEMATE, LOSS','#6ec8ff'),
             ('SIMON 404','SAID CHECKMATE AND WAS SLASHED','#ff786e'),
             ('TONIGHT','GRAY PICKS THE MIDDLE ONE','#b88cff'),
             ('BECAUSE','A DRAW CANNOT REMOVE HIM','#7dff8f')],
       close=['THE ONLY WAY OUT','OF A FILE THAT RANKS EVERYTHING',
              'IS A RESULT','THAT DOES NOT RANK.']),
 ],
 band=dict(head='THIS FILE HAS TOPPED A RANKING ON CONTROLS BEFORE, AND NOT ON POWER.',
   rows=[('ERROR 404','→ /command_kill = true','TOOK FIRST WITHOUT WINNING A FIGHT',0),
         ('AND','→ /expand_permissions','A PLAYER VERSUS AN ADMIN ERROR',0),
         ('AND','→ /game:Destroy()','THE GAME, NOT THE CHARACTERS IN IT',0),
         ('TONIGHT','→ GRAY LEARNS THE OWNER PANEL','THE SAME RANK, FOR THE SAME REASON',1)],
   close='THE STRONGEST THING IN THIS ARCHIVE HAS NEVER BEEN AN ATTACK. IT HAS ALWAYS BEEN WHOEVER CAN REACH THE SETTINGS.'),
 inset=dict(head='GOD KEEPS GETTING WIDER',
   rows=[('3:37 PM','GOD IS A RANK ABOVE PERO','#ffd25a'),
         ('3:40 PM','GOD IS THE CEILING ON A NEW TITLE','#b88cff'),
         ('4:31 PM','“GOD COULD SHINE OUT GRAY”','#6ec8ff'),
         ('SO','THE NAME NOW COVERS SOMEBODY ELSE','#7dff8f')],
   flag='IT STOPPED BEING PERO’S CEILING.', idle='ONE NAME, THREE HOURS, THREE JOBS',
   close=['FOR AN HOUR GOD WAS ONE MAN’S LIMIT.','TONIGHT IT IS THE WHOLE GAME’S.']),
 strip=[('THE WEAKNESS','GONE','#b88cff'),
        ('THE PANEL','LEARNED, NOT HANDED','#6ec8ff'),
        ('ABOVE HIM','ONLY PERO, AND GOD','#ffd25a')],
 foot=['GASTER AND LUIGI GREEN LET HIM HAVE THE GAME AT 4:20 AND WERE FAR UNDER HIM BY 4:31',
       '★ BEYOND WORDS ★'],
),
]
