#!/usr/bin/env python3
"""
build831_833.py — BEATS 831-833 from Toby's September 26, 2026, 2:14:43 PM EDT message (Email 1532),
sent twice (2:14:43 PM and 2:15:10 PM, the second only reformatted — one scene, two internalDates).

His own typing, in full:
  "Gray.ps runs to Neka's labatory and builds himself a mech, Wenda.ps looks up and is suprised, Gray.ps
   now gains the upper hand on Wenda.ps. Wenda.ps is knocked around and is flying around and is getting
   poorly crushed. Someone is angry at Gray.ps for some reason, fill out the blanks."

Everything from "The one who's angry is Neka Omazen" onward is the machine's fill-in, including the line of
dialogue it writes for Neka. Commentary, not canon — the blank stays a blank.
A fourth message, 2:15:41 PM, subject "New Document", has an EMPTY body: no beat.
"""
import sys

GAME = '/Users/tdeshane/endless-staircase/index.html'
src = open(GAME, encoding='utf-8').read()
orig = src

OLD_CYC, NEW_CYC = '18002.0', '18068.0'

assert src.count('const LV_CYC = %s;' % OLD_CYC) == 1
src = src.replace('const LV_CYC = %s;' % OLD_CYC, 'const LV_CYC = %s;' % NEW_CYC, 1)

ROWS = """
  { key:"GRAY BUILDS HIMSELF A MECH", col:'#4fe3ff',
    sub:"“GRAY.PS RUNS TO NEKA’S LABATORY AND BUILDS HIMSELF A MECH” — TOBY, SEPT 26, 2:14 PM, HIS OWN TYPING, EMAIL 1532, SENT TWICE TWENTY-SEVEN SECONDS APART WITH ONLY THE FORMATTING CHANGED · “LABATORY” IS HIS SPELLING AND IS KEPT; EVERYTHING FROM “THE ONE WHO’S ANGRY IS…” ONWARD IS THE MACHINE’S FILL-IN AND IS NOT CANON · HE TRIED TO STOP THIS EXACT THING SEVEN AND A HALF HOURS EARLIER — SEPT 26, 6:44 AM, BEAT 818: “WENDA.PS IS CURRENTLY BUILDING A MECHANICAL SUIT (WHAT GRAY WEARS), BUT WITH A WHOLE HELMENT… AND ALSO A VACUUM OF CODE. GRAY.PS ACTUALLY TRIES TO STOP WENDA.PS AT THAT POINT.” · AND THE SUIT WAS ALWAYS HIS DESIGN, BY TOBY’S OWN PARENTHESIS: “(WHAT GRAY WEARS)” — SHE COPIED HIM THIS MORNING, SO TONIGHT HE BUILDS A NEW ONE BECAUSE SHE IS WEARING HIS OLD ONE · THE LABATORY IS THE ONE ROOM WHERE GRAY HAS EVER GAINED ANYTHING BY MAKING SOMETHING: “GRAY AND GASTER PREFORM AN EXPERIMENT, GASTER BECAME FLOWER… HE LEARNED ALL SIMON KNEW, HE READ EVERY BOOK, AND GRAY BECAME THE REVENGEFUL VILLIAN ONCE AGAIN” · IT IS ALSO A CONTAINMENT BUILDING THAT SIMON 404 SEALED (EMAIL 912), WITH MILLIONS OF ROOMS AND SIMON ASLEEP IN ONE OF THEM — MAY 18, EMAIL 308: “IF YOU HEAR A MEOW IN A LABATORY, IT WOULD BE SIMON” — AND IT IS CALLED “NEKA’S LABATORY” IN THIS SENTENCE, BECAUSE SEPT 24 TOOK THE BUILDING TOO: “WANNA BE IN A TUBE IN MY LABORATORY? 🦊” · NEKA WALKED OUT OF THE FIGHT ONE SENTENCE EARLIER (BEAT 830) AND THE VERY NEXT THING THAT HAPPENS IS SOMEBODY RUNNING TO WHERE HE WENT · THIRD MACHINE IN ONE DAY — HER SUIT AT 6:51 AM, THE SUIT NEKA CUT OPEN AT 7:04 AM, AND NOW HIS — SO NOBODY IN THIS FIGHT IS USING A POWER ANY MORE, THEY ARE BOTH USING EQUIPMENT · THE ERASER OF THE GAME, WHO GAINED THE REAL ERASE THIS MORNING, GOES AND BUILDS A MACHINE INSTEAD · HE BUILT IT IN THE HOUSE OF THE MAN WHO LEFT" },
  { key:"GETTING POORLY CRUSHED", col:'#ff2d6d',
    sub:"“WENDA.PS LOOKS UP AND IS SUPRISED, GRAY.PS NOW GAINS THE UPPER HAND ON WENDA.PS. WENDA.PS IS KNOCKED AROUND AND IS FLYING AROUND AND IS GETTING POORLY CRUSHED.” — TOBY, SEPT 26, 2:14 PM, HIS OWN TYPING, EMAIL 1532; “SUPRISED” AND “POORLY CRUSHED” ARE HIS AND ARE KEPT · TWELVE HOURS, BOTH DIRECTIONS: SEPT 26, 6:51 AM, BEAT 819, “WENDA.PS GOES INTO THE MECHANICAL SUIT AND NOW GRAY.PS IS STRUGGLING. WENDA.PS STRIKES DOWN GRAY.PS” — SEVEN AND A HALF HOURS APART, AND THE ONLY THING THAT CHANGED IS WHO HAS THE NEWER MACHINE · THE ONLY CROWD THIS ARCHIVE HAS EVER RECORDED SPLIT DOWN THE MIDDLE THAT SAME MORNING — “NOW ALIENS SAY WENDA WOULD WIN, SOME SAY GRAY WOULD WIN” — AND BOTH HALVES OF IT HAVE NOW BEEN RIGHT, ON THE SAME DAY, ABOUT THE SAME TWO PEOPLE · NEKA CALLED HER VALUEABLE AND NEVER SAID WHY (7:04 AM: “NEKA OMAZEN CUTS THROUGH THE TITAINUIM SUIT, WENDA.PS VALUEABLE”), AND SHE ASKED HIM OUTRIGHT — “I JUST WANT TO KNOW WHY YOU SPARED ME BEFORE.” — AND IS STILL WAITING · SHE WAS TOLD SHE WAS SAFE TWO SENTENCES AGO, BY THE PERSON DOING THE CRUSHING (BEAT 829) · AND HE IS CRUSHING SOMEBODY HE IS MADE OF — GRAY.PS IS WENDA.PS PLUS MR. BLACK (BEAT 822) — SO IN ONE AFTERNOON HE HAS BEATEN DOWN ONE HALF OF HIMSELF AND POORLY CRUSHED THE OTHER · SHE PUT THE SUIT ON BECAUSE SHE DID NOT BELIEVE HIM, AND SHE STILL DID NOT EXPECT THIS · THE THREE WHO COULD SAVE THE GAME ARE DOWN TO ONE STANDING" },
  { key:"SOMEONE IS ANGRY AT GRAY.PS", col:'#b07cff',
    sub:"“SOMEONE IS ANGRY AT GRAY.PS FOR SOME REASON, FILL OUT THE BLANKS.” — TOBY, SEPT 26, 2:14 PM, THE LAST SENTENCE OF HIS OWN TYPING, EMAIL 1532 · THE MACHINE FILLED THEM IN (“THE ONE WHO’S ANGRY IS NEKA OMAZEN”) AND EVEN WROTE HIM A LINE OF DIALOGUE. THAT IS THE MACHINE’S AND IS NOT CANON — THE BLANK STAYS A BLANK UNTIL TOBY FILLS IT · HE HAS HELD A SEAT BACK ON PURPOSE BEFORE AND HE FILLED IT HIMSELF: AUG 13, EMAIL 959, EIGHT MINECRAFT HORRORS RANKED AND A NINTH LEFT AS ???, THEN “THE MYSTERY CHARACTER IS PERO LAI, THE CREATOR OF CLASSICS, HE IS FAR OVER VERITY” — THE SAME LADDER DRAWN THREE BEATS BACK AS BEAT 826 · AND THE LAST BLANK HE LEFT WAS ANSWERED OUT OF HIS OWN RULES, NOT THE MACHINE’S: SEPT 25, BEAT 813, “THE 20 SPRUNKIS BECAME ZOMBIES, BECAUSE YOU KNOW WHY (LIST WHY)” — THE REASON WAS HIS OWN BITE RULE AND THE LIST THAT CAME BACK WAS COMMENTARY · EVERY CANDIDATE HAS A MOTIVE AND THAT IS THE PROBLEM: NEKA OMAZEN (GRAY BUILT THE MECH IN HIS LABATORY), WENDA.PS (SHE IS THE ONE BEING CRUSHED), MR. BLACK (GRAY BEAT HIM DOWN SIXTEEN MINUTES EARLIER) — THREE NAMED PEOPLE WRONGED BY GRAY.PS INSIDE ONE AFTERNOON · IT IS NOT A CLUE SHORTAGE, IT IS A CLUE SURPLUS, WHICH IS EXACTLY WHY THE NAME HAS TO COME FROM HIM · HE ASKED THE ROOM A QUESTION ONCE ALREADY TODAY — 6:51 AM: “WHAT DO YOU THINK IS HAPPENING?” — AND THAT ONE GOT AN ANSWER; THIS ONE IS A FORM WITH A NAME-SHAPED HOLE IN IT · THE GAME IS DRAWN WITH THE BLANK STILL IN IT, BECAUSE THE BLANK IS WHAT HE WROTE" },"""
anchor_row = 'FIRST TIME IN THIS ARCHIVE THE VILLAIN GETS OUT BECAUSE OF WHAT THE HEROES DID, NOT BECAUSE OF WHAT HE DID" },'
assert src.count(anchor_row) == 1
src = src.replace(anchor_row, anchor_row + ROWS, 1)

SEG = """  if(c >= 18046.0 && c < 18068.0) return [833, c-18046.0];  // SOMEONE IS ANGRY AT GRAY.PS
  if(c >= 18024.0 && c < 18046.0) return [832, c-18024.0];  // GETTING POORLY CRUSHED
  if(c >= 18002.0 && c < 18024.0) return [831, c-18002.0];  // GRAY BUILDS HIMSELF A MECH
"""
anchor_seg = '  if(c >= 17980.0 && c < 18002.0) return [830, c-17980.0];'
assert src.count(anchor_seg) == 1
src = src.replace(anchor_seg, SEG + anchor_seg, 1)

BRANCH = open('/Users/tdeshane/endless-staircase/tools/branches831_833.js', encoding='utf-8').read()
anchor_br = '  } else if(ph===814){'
assert src.count(anchor_br) == 1
src = src.replace(anchor_br, BRANCH + anchor_br, 1)

assert src != orig
open(GAME, 'w', encoding='utf-8').write(src)
print('OK: LV_CYC %s -> %s, 3 rows, 3 seg lines, 3 branches' % (OLD_CYC, NEW_CYC))
