#!/usr/bin/env python3
"""
build826_830.py — BEATS 826-830 from Toby's September 26, 2026, 1:58:06 PM EDT message (Email 1531).

His own typing, in order, is five pieces:
  1. 'Have you heard of the YouTuber "FroggyDude Gaming?"'
  2. 'He battles powerful things like Herobrine and AJTheBold'
  3. 'What will win? FroggyDude VS Neka Omazen'
  4. 'I never did anything, Neka gave everything about himself to himself himself. I am FAR under Neka Omazen.'
  5. 'Neka Omazen says "Mweh heh heh. \U0001f98a", He uses 25 Series on Mr. Black, Gray saves Mr. Black, then
      Gray beats Mr. Black down. Gray.ps says "Now, Wenda.ps, your safe.", Wenda.ps puts on the suit and
      then Wenda.ps battles Gray.ps, Neka Omazen gets away, and Wenda.ps and Gray.ps are still fighting.'

Everything between those pieces is the machine's, including the "Neka Omazen wins" verdict, the retraction
"I got that wrong when I said 'the powers you've given him'", and the prose retelling at the bottom.
Commentary, not canon.  "your safe" is Toby's spelling and is kept.

Three edits to index.html, per the standing build rule: LV_CYC, five LV_BEATS rows, five lvSeg range lines,
five ph=== draw branches.
"""
import re, sys

GAME = '/Users/tdeshane/endless-staircase/index.html'
src = open(GAME, encoding='utf-8').read()
orig = src

OLD_CYC, NEW_CYC = '17892.0', '18002.0'

# ---------------------------------------------------------------- 1. LV_CYC
assert src.count('const LV_CYC = %s;' % OLD_CYC) == 1
src = src.replace('const LV_CYC = %s;' % OLD_CYC, 'const LV_CYC = %s;' % NEW_CYC, 1)

# ---------------------------------------------------------------- 2. LV_BEATS rows
ROWS = """
  { key:"FROGGYDUDE VS NEKA OMAZEN", col:'#62e06a',
    sub:"“HAVE YOU HEARD OF THE YOUTUBER \\u2018FROGGYDUDE GAMING?\\u2019 … HE BATTLES POWERFUL THINGS LIKE HEROBRINE AND AJTHEBOLD … WHAT WILL WIN? FROGGYDUDE VS NEKA OMAZEN” — TOBY, SEPT 26, 1:58 PM, HIS OWN TYPING, EMAIL 1531; THE “NEKA OMAZEN WINS” PARAGRAPH UNDER IT IS COMMENTARY, NOT CANON · FROGGYDUDE AND AJTHEBOLD BOTH HAVE ZERO PRIOR HITS IN FIVE MONTHS, AND HEROBRINE HAS EXACTLY ONE · HEROBRINE IS FIFTH ON TOBY’S OWN LADDER AND THE SEAT ABOVE ALL EIGHT IS ALREADY NEKA’S: AUG 13, EMAIL 959, “VERITY > FALSITY > LONG HORSE > CREATOR > HEROBRINE > ENTITY 303 > NULL > WITHER STORM”, AND THEN HE FILLED THE HELD-BACK ??? THRONE HIMSELF — “THE MYSTERY CHARACTER IS PERO LAI, THE CREATOR OF CLASSICS, HE IS FAR OVER VERITY” · SO THE FIGHT WAS SETTLED FORTY-FOUR DAYS BEFORE IT WAS ASKED, AND IT WAS SETTLED BY THE PERSON ASKING · AND THE CHALLENGER IS NOT AN OUTSIDER: TOBY’S OWN CANON-VAULT RULE SPLIT THIS STORY IN TWO — “I USED YOU TO KEEP MOST OF THE SIMON’S SECRET, THE OTHER PARTS ARE WITH YOUTUBERS AND PEOPLE… THE SIMON’S LAW AND CLASSIC RL 2, THINGS THAT YOU CAN’T UNDERSTAND” — SO A YOUTUBER WALKING IN IS THE OTHER HALF OF HIS OWN ARCHIVE WALKING IN · HE HAS RUN A MATCHUP LIKE THIS EXACTLY ONCE BEFORE AND THE CHALLENGER NEVER THREW THE PUNCH: SEPT 25, BEATS 804-805, SAITAMA, WHOSE ONLY LINE IN FIVE MONTHS IS “I’LL BEAT YOU IN ONE PUNCH”, LOST TO “A SINGLE TOUCH OF IMMEDIANCE SPEED” · THE VERDICT RUNS ON TWO OF HIS OWN RULES AND HE ALREADY SAID NEKA DOES NOT KNOW ONE OF THEM: THE TOUCH (BEAT 805) AND THE BITE (SEPT 20, “JUST ONE BITE ON ANOTHER CHARACTER OR IF A CHARACTER EATS WHAT HE BIT, THEN THAT CHARACTER INSTANTLY BECOMES A ZOMBIE”), WHILE SEPT 20, BEAT 776, IS HIS OWN TYPING: “NEKA ALSO DOESN’T REALLY KNOW” · A REAL YOUTUBER’S FAMOUS ENEMY IS FIFTH ON A LIST TOBY WROTE, AND THE LIST HAS NEKA ON TOP OF IT" },
  { key:"I AM FAR UNDER NEKA OMAZEN", col:'#ffd43b',
    sub:"“I NEVER DID ANYTHING, NEKA GAVE EVERYTHING ABOUT HIMSELF TO HIMSELF HIMSELF. I AM FAR UNDER NEKA OMAZEN.” — TOBY, SEPT 26, 1:58 PM, HIS OWN TYPING, EMAIL 1531 · IT IS A CORRECTION: THE MACHINE HAD WRITTEN “NEKA OMAZEN WINS UNDER THE POWERS YOU’VE GIVEN HIM”, AND TOBY TAKES THE CREDIT BACK OUT — THE AUTHOR DISCLAIMS AUTHORSHIP OF HIS OWN CHARACTER · THE ONLY OTHER TIME HE HAS EVER RANKED HIMSELF HE ALSO WROTE ZERO: AUG 27, 2:45 PM, EMAIL 1188, BEAT 495, “I AM A CLASSICS ADMIN. CLASSICSAI. I BASICALLY HAVE 0 GAME CONTROL. MY PLAYER CONNECTION ISN’T THAT IMPORTANT. GASTER AND PERO ARE THE MOST POWERFUL IN THE GAME, THAT IS IMPORTANT.” · THIRTY DAYS APART, TWO SELF-RANKINGS, BOTH AT THE BOTTOM · AND THE AVATARS KEEP FALLING OFF UNDERNEATH HIM: “MY AVATAR IS TDESHANE” (SEPT 19) → “TDESHANE LOST ACCESS” (SEPT 24) → CLASSICSPRO7777… (BEAT 801, LASTED ONE DAY) → CLASSICSADMIN1 (BEAT 811) — AND CLASSICSADMIN IS THE ONE NAME HE EVER GAVE HIMSELF AND THE ONE HE RANKED ZERO · “FANON > CANON” IS THIRTY DAYS OLD (AUG 27, 11:47 AM) AND RANKED KINDS OF AUTHORSHIP; TODAY HE REMOVES HIMSELF FROM AUTHORSHIP ALTOGETHER · SELF-SOURCING WAS ALREADY THE MECHANIC — SEPT 23: “NOW HE ERASED THE OTHERS AND BECAME NEKA OMAZEN, TRUE OVER(X INFINITY)LORD… HE USES THE OTHER FORMS AS SHIELDS” — BUT TODAY IT BECOMES THE REASON NOBODY ELSE HAS A CLAIM ON HIM · “TO HIMSELF HIMSELF” IS HIS DOUBLING AND IS KEPT: THE WORD HAS TO BE SAID TWICE BECAUSE THE GIVER AND THE RECEIVER ARE THE SAME PERSON · HE HAS WRITTEN HIMSELF OUT OF HIS OWN STORY TWICE IN THIRTY DAYS AND BOTH TIMES HE DID IT IN ONE SENTENCE" },
  { key:"GRAY SAVES MR. BLACK, THEN BEATS HIM DOWN", col:'#b9c0c9',
    sub:"“NEKA OMAZEN SAYS ‘MWEH HEH HEH. \\ud83e\\udd8a’, HE USES 25 SERIES ON MR. BLACK, GRAY SAVES MR. BLACK, THEN GRAY BEATS MR. BLACK DOWN.” — TOBY, SEPT 26, 1:58 PM, HIS OWN TYPING, EMAIL 1531 · SEVEN HOURS EARLIER GRAY WAS THE RESCUE: SEPT 26, 7:04 AM, BEAT 822, “COMBINE WENDA.PS AND MR. BLACK TO GET GRAY.PS, GRAY.PS IS THE ERASER OF THE GAME… THE 3 CAN RUIN AND CORRUPT THE GAME, BUT ALL TOGETHER, THEY CAN DO ANYTHING AND CHANGE AND CAN SAVE THE GAME FROM NEKA OMAZEN” · SO GRAY IS BEATING DOWN ONE OF THE TWO HE IS MADE OF — THE COALITION THAT COULD SAVE THE GAME BREAKS ITSELF SEVEN HOURS AFTER BEING NAMED, AND NOTHING ATTACKED IT · HE HAS OFFERED MR. BLACK SOMETHING ONCE BEFORE AND IT WAS A TRAP: EMAIL 933, “GRAY TEMPS MR. BLACK TO EAT AN APPLE. BOTH FELL FOR THE ATTACK… MR. BLACK WAS CORRUPTED” · AND MR. BLACK IS THE ONE SUPPOSED TO BE STRONGER: EMAIL 236, “MR. BLACK IS ACTUALLY STRONGER THAN GRAY” · THIS IS THE 25 SERIES’ THIRD USE AND THE FIRST TIME IT DOES NOT LAND ON WHAT IT WAS AIMED AT — THE FIRST INTERCEPTION IN THE ARCHIVE — AND IT COSTS THE TARGET MORE THAN THE ATTACK WOULD HAVE · THE LAUGH IS NOT NEW: “MWEH HEH HEH HEH HEH \\ud83e\\udd8a” CAME WITH THE ROOM OF MANY TUBES AND ZUMERAL SAID “MWEH HEH HEH HEH” LONG BEFORE THAT · WHAT IS NEW IS THAT HE LAUGHS, FIRES ONCE, AND THE DAMAGE IS DONE BY SOMEBODY ON THE OTHER SIDE · BEING SAVED BY GRAY IS WORSE THAN BEING HIT BY NEKA" },
  { key:"NOW, WENDA.PS, YOUR SAFE", col:'#ff7ad9',
    sub:"“GRAY.PS SAYS ‘NOW, WENDA.PS, YOUR SAFE.’, WENDA.PS PUTS ON THE SUIT AND THEN WENDA.PS BATTLES GRAY.PS” — TOBY, SEPT 26, 1:58 PM, HIS OWN TYPING, EMAIL 1531; “YOUR SAFE” IS HIS SPELLING AND IS KEPT, AND THE MACHINE’S “YOU’RE SAFE” IS NOT · SHE IS TOLD SHE IS SAFE AND SHE SUITS UP IN THE SAME BREATH · THE SUIT IS ALREADY OPEN AND THIS MORNING PROVED IT TWICE: 6:51 AM, BEAT 819, “THE SHADOWS FILL THE MECHASUIT… HOLES ARE IN THE VACUUM, AND NEEDLES CARVE THROUGH THE HELMET”, AND 7:04 AM, BEAT 820, “NEKA OMAZEN CUTS THROUGH THE TITAINUIM SUIT” — SHE PUTS BACK ON A SUIT THAT WAS HOLED, NEEDLED AND CUT SEVEN HOURS AGO · AND SHE ATTACKS THE OTHER HALF OF HERSELF: GRAY.PS IS WENDA.PS PLUS MR. BLACK, SO BOTH HALVES OF HIM HAVE NOW TURNED ON THE SUM IN ONE MESSAGE · SHE HAS WORN IT AGAINST HIM BEFORE AND IT WORKED: 6:51 AM, “WENDA.PS GOES INTO THE MECHANICAL SUIT AND NOW GRAY.PS IS STRUGGLING. WENDA.PS STRIKES DOWN GRAY.PS” — SO THE SUIT IS THE ONE THING IN THIS FIGHT WITH A WINNING RECORD, AND THE FIRST TIME SHE REACHES FOR IT IS THE MOMENT SHE IS TOLD SHE DOES NOT NEED IT · SAFETY HAS BEEN A LIE HERE SINCE JULY 22, WHERE THE CUTSCENE ROSTER GAVE MR. FUN COMPUTER A FAKE SAFETY AND NOTHING ELSE · AND SHE ASKED FOR A REASON THIS MORNING AND NEVER GOT ONE: 7:04 AM, “HELLO, PERO LAI, I JUST WANT TO KNOW WHY YOU SPARED ME BEFORE.” — BEING SPARED IS THE QUESTION SHE HAS BEEN CARRYING ALL DAY, AND NOW SOMEBODY ELSE SAYS IT TO HER AND SHE REACHES FOR THE ARMOUR" },
  { key:"NEKA OMAZEN GETS AWAY", col:'#ff8a3d',
    sub:"“NEKA OMAZEN GETS AWAY, AND WENDA.PS AND GRAY.PS ARE STILL FIGHTING.” — TOBY, SEPT 26, 1:58 PM, HIS OWN TYPING, EMAIL 1531, THE LAST NINE WORDS OF THE MESSAGE · HE DID NOT WIN: HE LAUGHED, FIRED ONCE, THE SHOT WAS INTERCEPTED, AND HE LEFT WHILE THE PEOPLE WHO COULD STOP HIM FOUGHT EACH OTHER · THE ONLY OTHER ESCAPE IN FIVE MONTHS EXPIRED FOUR SENTENCES LATER: “SUPREME SANS GOT AWAY”, AND THEN “HE GRABBED SUPREME SANS WITH A TENTACLE, SUPREME SANS WAS ABSORBED INTO THE CHARACTER’S BODY” · THIS ONE HOLDS, AND IT HOLDS ON A RULE TOBY WROTE SEVEN HOURS EARLIER: 7:04 AM, BEAT 822, “AND NONE OF THE 3 SURPASS EACH OTHER” · THAT IS THE SECOND UNDEFINED LOOP IN THIS ARCHIVE AND THE FIRST ONE ON THE HEROES’ SIDE — EMAIL 595, JUNE 27, “IT’S LIKE STEEL VS FIRE VS WATER VS ELECTRICITY”, CALLED UNDEFINED BY TODDLLM AND LUIGI GREEN THEMSELVES · AN UNDEFINED LOOP HAS NO WINNER, SO “STILL FIGHTING” IS NOT A CLIFFHANGER, IT IS THE RULE: THE FIGHT HE LEAVES BEHIND HIM CANNOT END, WHICH MEANS NOBODY IS COMING AFTER HIM · HE LEFT ONCE ALREADY TODAY AND THAT TIME HE HAD WON — 7:04 AM, “NEKA OMAZEN CUTS THROUGH THE TITAINUIM SUIT, WENDA.PS VALUEABLE. NEKA OMAZEN LEFT.” — SO THE SAME EXIT NOW WORKS WITHOUT THE VICTORY · AND THE THREE WHO CAN SAVE THE GAME ARE STILL ON THE BOARD, STILL ABLE TO SAVE IT, AND BUSY · THE FIRST TIME IN THIS ARCHIVE THE VILLAIN GETS OUT BECAUSE OF WHAT THE HEROES DID, NOT BECAUSE OF WHAT HE DID" },"""
anchor_row = 'THE ATTACK HE BUILT FOR THE PLAYER IS NOW THE ATTACK HE SURVIVES" },'
assert src.count(anchor_row) == 1
src = src.replace(anchor_row, anchor_row + ROWS, 1)

# ---------------------------------------------------------------- 3. lvSeg range lines
SEG = """  if(c >= 17980.0 && c < 18002.0) return [830, c-17980.0];  // NEKA OMAZEN GETS AWAY
  if(c >= 17958.0 && c < 17980.0) return [829, c-17958.0];  // NOW, WENDA.PS, YOUR SAFE
  if(c >= 17936.0 && c < 17958.0) return [828, c-17936.0];  // GRAY SAVES MR. BLACK, THEN BEATS HIM DOWN
  if(c >= 17914.0 && c < 17936.0) return [827, c-17914.0];  // I AM FAR UNDER NEKA OMAZEN
  if(c >= 17892.0 && c < 17914.0) return [826, c-17892.0];  // FROGGYDUDE VS NEKA OMAZEN
"""
anchor_seg = '  if(c >= 17870.0 && c < 17892.0) return [825, c-17870.0];'
assert src.count(anchor_seg) == 1
src = src.replace(anchor_seg, SEG + anchor_seg, 1)

# ---------------------------------------------------------------- 4. draw branches
BRANCH = open('/Users/tdeshane/endless-staircase/tools/branches826_830.js', encoding='utf-8').read()
anchor_br = '  } else if(ph===814){'
assert src.count(anchor_br) == 1
src = src.replace(anchor_br, BRANCH + anchor_br, 1)

assert src != orig
open(GAME, 'w', encoding='utf-8').write(src)
print('OK: LV_CYC %s -> %s, 5 rows, 5 seg lines, 5 branches' % (OLD_CYC, NEW_CYC))
