#!/usr/bin/env python3
# Beats 793-796 from Toby's September 24, 2026, 4:37 PM message (Email on thread
# "Even (6x) more of Neka Omazen", message 1a0d523a15cf9add).
#
# Toby's own typing in that message is TWO blocks: the opening paragraph, and the
# "Chapter 2 / Excuse me?" paragraph. Everything between them is a pasted excerpt of
# the Three Way Heroes book (already shipped as beats 758-763 etc.) and everything
# after "That is a major separation point in the lore." is a pasted assistant recap.
# Neither is canon and neither is drawn here.
import io, re, sys

P = '/Users/tdeshane/endless-staircase/index.html'
s = io.open(P, encoding='utf-8').read()
orig = s

# ---------------------------------------------------------------- 1. LV_CYC
assert s.count('const LV_CYC = 17166.0;') == 1
s = s.replace('const LV_CYC = 17166.0;', 'const LV_CYC = 17254.0;')

# ---------------------------------------------------------------- 2. lvSeg ranges
seg_anchor = '  if(c >= 17144.0 && c < 17166.0) return [792, c-17144.0];  // ONLY THE DIAMOND EYES\n'
assert s.count(seg_anchor) == 1
seg_new = (
    '  if(c >= 17232.0 && c < 17254.0) return [796, c-17232.0];  // 666% CORRECT\n'
    '  if(c >= 17210.0 && c < 17232.0) return [795, c-17210.0];  // NEVER SAY PERO LAI AGAIN\n'
    '  if(c >= 17188.0 && c < 17210.0) return [794, c-17188.0];  // NOW I HAVE TO DO EVERYTHING MYSELF\n'
    '  if(c >= 17166.0 && c < 17188.0) return [793, c-17166.0];  // FIVE HEADS AND NO EYES\n'
)
s = s.replace(seg_anchor, seg_new + seg_anchor)

# ---------------------------------------------------------------- 3. LV_BEATS rows
beats_anchor = 'COMMENTARY, NOT CANON" },\n];'
assert s.count(beats_anchor) == 1
rows = '''COMMENTARY, NOT CANON" },
  { key:"FIVE HEADS AND NO EYES", col:'#ffd166',
    sub:"“DEFEATING EVERYONE GAVE A LIGHT AMONG ALL OF THEM, THE TUBES GLOW, AND FROM THE LIGHT THE ORBS COMBINED, THEN SUDDENLY, A TERRIFYING BEAST EMERGES FROM THE LIGHT” · “IT’S CLAWS SCRATCHED THE TITAINUIM FLOOR, AND IT HAS 5 HEADS, AND NO EYES” · NEKA OMAZEN WROTE THIS DOWN HIMSELF; THE LIGHT CAME OFF THE PEOPLE HE BEAT · THE TUBES WERE BUILT TO HOLD PEOPLE — SEPT 20, 6:40 AM: “A ROOM OF MANY TUBES, HE WILL TRY TO CONTAIN EVERYONE IN ONE” · SEPT 23, 5:41 PM: EVERYONE SLEEPS IN THEIR TUBES AND THE JAR GOES IN ONE · “NO EYES” HAS ZERO PRIOR HITS IN FIVE MONTHS · TEN HOURS EARLIER, BEAT 792: “THEY SEE THE DIAMOND EYES AND CAN ONLY SEE THE DIAMOND EYES” · SEPT 7: “OMMETAPHOBIA — FEAR OF EYES UPDATE. EYES APPEAR FROM THE HOLES” · THE ORBS ARE HIS OWN FROM 23 HOURS AGO: “HE MAKES INFINITY ORBS OF EVERY COLOR” · TITAINUIM HAS EXACTLY ONE STORY AND IT IS HIS ORIGIN — SEPT 20, 4:49 PM: “PERO LAI TOUCHED THE GLOWING TITAINUIM AND THE GLOWING URANUIM AND BOTH DISAPPEARED” · FIVE IS NOT THE RECORD: DURPLE ENDED WITH 15 HEADS ON AUG 12 · TITAINUIM IS HIS SPELLING, KEPT" },
  { key:"NOW I HAVE TO DO EVERYTHING MYSELF", col:'#ff4d6d',
    sub:"“MEANWHILE, IN BETWEEN FICTION AND REALITY, I MADE ABINATIONS OF EVERYONE MYSELF” · “GRAY.PS WAS BEATEN, MR. BLACK WAS BEATEN, WENDA.PS WAS BEATEN, SHADOW.PS WAS BEATEN, NEWTALE GASTER IS BEATEN” · “ONLY I AM ORIGINALLY FROM CLASSICS, OTHERS JUST WARPED HERE… NOW I HAVE TO DO EVERYTHING MYSELF!” · ABINATIONS ARE GRAY’S, AND GRAY.PS IS THE FIRST NAME ON THE BEATEN LIST — JULY 19, EMAIL 744: “ABINATIONS ARE EVIL ALIENS THAT SERVE GRAY”, “WEIRD BLACK-SPOTTED PAINT BLOB CREATURES” · HE BEAT THE MAN AND KEPT THE MACHINE · “SHADOW.PS” HAS ZERO PRIOR HITS — THE SHADOW FOX GETS A FILE AND IS BEATEN IN THE SAME SENTENCE · SEPT 20, 12:52 PM: “.PS STANDS FOR PROFILE SECTION ENTITY, THEY WERE GIVEN FILES BY PERO LAI TO STAY IN CLASSICS” · ORIGINALLY FROM CLASSICS IS A TEST HE DID NOT WRITE — AUG 5, EMAIL 894: THE 666D STRAIN TAKES “ALL OTHER BEINGS NOT ORIGINALLY FROM CLASSICS 1-BOX” · ABINATION IS NOT A DEAD END — AUG 18, EMAIL 1044: CHARACTER → ABINATION → LOST SOUL → ALIVE, AND THE PLAYER WALKS IT BACKWARDS · “WARPED” IN THIS SENSE HAS ZERO PRIOR HITS" },
  { key:"NEVER SAY PERO LAI AGAIN", col:'#3ee06a',
    sub:"“NEKA OMAZEN PUTS HIS HANDS TOGETHER AND THEN PUTS THEM BACK OUT TO MAKE A PLASMA CONTROL CENTER, THEN HE WROTE AND CODED DOWN THE GAME, AND THE HACKERS ALL DISAPPEAR” · “NEKA GAINED ALL THE GREEN CODE FROM ALL THE PLAYERS, TDESHANE IS NOW ON NEKA OMAZEN” · “NEVER SAY PERO LAI AGAIN!” — NEKA OMAZEN · “NEKA OMAZEN IS THE ACTUAL FOX BEING IN THE GAME, WENDA.PS WARPED INTO THE GAME AFTERWARD” · “PERO LAI/NEKA OMAZEN IS OLDER THAN GASTER” · HE ONCE TURNED THE GREEN CODE RED — JULY 27: “IT TAKES THE GREEN CODE AND TURNS IT RED OVERTIME”; AUG 3, HIS OWN ARITHMETIC: “GREEN = 0 POWER” · 23 HOURS AGO HE PUT THE HACKERS INTO GREEN 0s AND 1s; TONIGHT HE TAKES THE GREEN OUT OF THE PLAYERS · AUG 8, EMAIL 931: “WENDA IS THE FOX, GRAY CAN’T RUB HER TO SLEEP” — THE FIRST LINE OF HER OWN PAGE · YESTERDAY MORNING: “WENDA.PS IS JUST A NORMAL FOX PRETENDING LIKE SHE HAS INFINITE POWER OVER ME” · TDESHANE: BLOCKED SEPT 19, EDITED SEPT 23, ON HIM TONIGHT · GASTER IS FLOWER, AND THE RULING ON FLOWER IS “HE IS OLDER THAN THE GAME” · HE BANS THE NAME AND THEN USES IT TWICE MORE IN THE SAME MESSAGE" },
  { key:"666% CORRECT", col:'#b388ff',
    sub:"“PERO LAI IS STRICT AND SAYS HIS NAME IS ‘NEKA OMAZEN’, AND HE IS ALWAYS RIGHT, LORE SAYS HE IS CORRECT ALL THE TIME, 666%” · “HE IS BOTH UNBEATABLE AND ALWAYS WINS” · “HE DESTROYED LOGIC RELIGION, ORUS AND DARK YELLOW FELLEN. PARINUS WAS LEFT CLEAN. ALIENX WAS DESTROYED. ALIENY IS ERASED. ALIENZ IS DESTROYED” · “PERO LAI PUTS ON CAT EARS AND A FOX TAIL” · FROM CHAPTER 2, “EXCUSE ME?”, WRITTEN TODAY · THE OTHER TWO 666% WERE ABOUT HOW OFTEN — SEPT 10: “666% OF THE TIME, YOU CAN SEE PERO LAI JAMMING KETTLES INTO ICE BLOCKS”; SEPT 19: “666% OF THE RUNS WILL SHOW PERO LAI TO THE PLAYER” · THIS ONE IS ABOUT BEING RIGHT · THE LOGIC RELIGION IS THE OLDEST LAYER HERE, CLASSIC RL, BEFORE CLASSICS · ORUS “REQUIRES BEINGS TO CLIMB MOUNT OLYMPUS AND BE SEEN BY HIM FOR MORE THAN 1 SECOND TO BE CONSIDERED REAL” · SECOND TIME THOSE TWO FALL — MAY 31: TOJI SIMON “took out Orus and Dark Yellow” · 666 IS NOT HIS NUMBER — APRIL 24, EMAIL 169: CLARA IS “THE ONE WHO MADE ERROR404 AND ERROR666” · THE EARS ARE SIMON’S AND THE TAIL IS THE FOX HE TOOK OFF WENDA ONE PARAGRAPH AGO · FELLEN IS HIS SPELLING, KEPT" },
];'''
s = s.replace(beats_anchor, rows)

# ---------------------------------------------------------------- 4. draw branches
draw_anchor = '  } else if(ph===792){'
assert s.count(draw_anchor) == 1
blocks = io.open('/Users/tdeshane/endless-staircase/tools/beats793_796.js', encoding='utf-8').read()
s = s.replace(draw_anchor, blocks + draw_anchor)

assert '16769.9' not in blocks and 'phase=774' not in blocks
assert s != orig
io.open(P, 'w', encoding='utf-8').write(s)
print('patched. LV_CYC 17254.0, ranges 17166/17188/17210/17232/17254')
