#!/usr/bin/env python3
"""
gen1008.py - draw branches for BEATS 1008-1059 from Toby's October 6-10, 2026 messages
(threads 1a0f9cb82996f580 "Re: Document", 1a12024dfbc6a081, 1a1204179c8e973f "Another Document").
Same template as 933-1007 (emit_tail933.py), but each beat carries its own date.

NO BEAT: image requests (Oct 6 5:57 PM, 7:45 PM; Oct 7 6:10 PM; Oct 9 6:10 AM, 12:51 PM, 4:42 PM),
the Oct 6 5:58 PM ranking question (the answer is the chatbot's), the Oct 8 7:07 PM
"error in message stream" tool note. Merged: Oct 9 6:10/6:10 PM eye colors (one scene),
7:00/7:04 PM Neka NOT tale, 7:35/7:35 PM 67 Pirate, Oct 10 7:18/7:19 AM Laughing Gull.
Only Toby's own sentences are drawn; italic retellings read like pasted chatbot rewrites.
"""
import io

BASE = 1008
TAG = "1008"
START = 21896.0
STEP = 22.0
B = []

MONTH = {6: 'OCTOBER 6', 7: 'OCTOBER 7', 8: 'OCTOBER 8', 9: 'OCTOBER 9', 10: 'OCTOBER 10'}

def meta(day, t):
    return dict(when=t, short=t, day=day,
                attr='TOBY, %s, %s — HIS OWN TYPING.' % (MONTH[day], t))

def add(m, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(m)
    B.append(d)

# ---------------- October 6 ----------------
add(meta(6, '5:51 AM'), 'SHIFTED NEKA', '170,140,255',
    ['NEKA DIED AGAIN.', 'A SHIFTED NEKA AU.'],
    [('CRYSTALS', ['MADE OF CRYSTALS AND A LARGE', 'BALL IN THE CENTER. NO WINGS.'],
      'SPINNING BARS AROUND IT.'),
     ('INSIDE THE BALL', ['HIS SIMPLE GASTER IS IN IT,', 'THE ORIGINAL DESIGN.'],
      'WITH LARGE POWER CHANGES.'),
     ('LIKE A SERAPHIM', ['“THE ROTATING CIRCLE THING,', 'HAVE NO IDEA WHAT IT IS.”'],
      'A DIFFERENT AU. A NEKA AU.')],
    ['NEKA DIED.', 'NEKA CAME BACK SPINNING.'])

add(meta(6, '6:30 AM'), 'ERROR 404', '255,110,110',
    ['MANY TRY TO DELETE NEKA.', 'IT ALWAYS FAILED.'],
    [('404', ['“LIKE YOU ARE TRYING', 'TO DELETE NOTHING.”'],
      'THE COMMAND FINDS NOTHING.'),
     ('THE MALLOWS', ['THOUSANDS OF MALLOWS GROW', 'ALL OVER HIS CRYSTALS.'],
      'NEKA BARELY WINS THE REMATCH.'),
     ('GASTER GETS BACK UP', ['GASTER WON THE FIRST FIGHT.', 'THEN HE STOOD UP AGAIN.'],
      'NEKA GAVE UP BATTLING HIM.')],
    ['YOU CANNOT DELETE NOTHING.', 'AND NEKA IS NOT NOTHING.'])

add(meta(6, '4:07 PM'), 'PLASMA SAWS', '90,170,255',
    ['“THIS IS YOUR LAST CHANCE', 'TO SAVE CLASSICS HERE.”'],
    [('PLATINUM GASTER', ['NEKA MADE HIS CRYSTALS AND', 'FORCEFIELD PLATINUM.'],
      'FULL POWER DID NOT EVEN BREAK IT.'),
     ('“SAWS... PLASMA SAWS!”', ['BLUE PLASMA SAWS ERUPT FROM', 'GASTER’S ARM. THE METAL MELTS.'],
      'THEN TITANIUM AND GLASS. SHATTERED.'),
     ('THE 56TH TIME', ['BEATEN 55 TIMES, GASTER LEARNED.', 'HE USED THE CODE. HE WON.'],
      'CLASSICS FELL FROM NEKA.')],
    ['“EVERY TIME I DIE, I RESPAWN', 'STRONGER, BUT THERE IS A LIMIT.”'])

add(meta(6, '4:07 PM'), 'CODE GASTER', '120,255,170',
    ['“THIS IS HOW IT ALL ENDS.”', 'NEKA T-POSES.'],
    [('SUPER VOID NEKA', ['VS SUPER SYRIAN GASTER, 666 YEARS.', 'THEN ULTRA INSTINCT, 59 YEARS.'],
      'GASTER WON.'),
     ('ARCHICAL NEKA', ['“WANT TO BE AN OMAZEN?”', 'CRYSTALS NOW MADE OF VOID.'],
      '/NEKA = NULL. NOTHING HAPPENS.'),
     ('“KIOAKEN MODE!”', ['GRAY.PS AND 19 SPRUNKIS.', 'THE TUBE BREAKS.'],
      'CODE NEKA VS CODE GASTER.')],
    ['15 ETERNITIES.', 'CODE GASTER WON.'])

add(meta(6, '4:30 PM'), '/RESIZE GASTER 0.1', '255,200,120',
    ['“I CHOOSE THE REAL COOKIE.”', '“DATA.” “PI.” “SLEEP! 😸⚡”'],
    [('NON-SUGAR CHOCOLATE', ['“ARE YOU SIMON.PS?”', '“NO, I AM NEKA.”'],
      'GASTER IS STILL AWAKE.'),
     ('THE SIZE OF AN ANT', ['GASTER BECAME HUGE.', 'NEKA STEPS ON HIM.'],
      '/SIZE = 99999999999999...'),
     ('THE VOID MALLOW', ['IT REACHED OUT OF NEKA’S CHEST', 'AND CONSUMED GASTER.'],
      'GASTER’S CODES ABSORBED.')],
    ['THE DEVOURER OF CODES', 'VS THE GOD OF CORRUPTION.'])

add(meta(6, '5:33 PM'), ':)', '255,230,90',
    ['AN ENTITY WAS ADDED', 'CALLED ":)".'],
    [('MADE BY TDESHANE AND C.O.D.E.', ['A CORRUPTION. “:) IS A MOD', 'YA KNOW.”'],
      'NEKA TURNED IT INTO AN ANTI-VIRUS.'),
     ('/TICKFREEZE', ['WRITING IT SPAWNS HIM.', 'THERE IS NO UNFREEZE.'],
      'ALL OF CLASSICS INFECTED.'),
     ('CODE :)', ['CODE’S AVATAR, COVERED IN :)S.', 'CODE BECAME THE CODE OF THE GAME.'],
      'NEITHER CAN HIT THE OTHER.')],
    ['GASTER AND NEKA BOTH', 'STAND UNHITTABLE.'])

add(meta(6, '7:26 PM'), 'ENTITY 12', '120,220,140',
    ['NEKA OMAZEN IS ENTITY 12,', 'BUT THE CODE SAYS “1348”.'],
    [('THE PLAGUE SCIENTIST', ['A SCIENTIST WHO ERASES VIRUSES', 'AND MAKES EVERYTHING ANTI-VIRUS.'],
      'IT INFECTS EVEN THE CODE.'),
     ('“ME ME WON’T DIE.”', ['“ONLY GOD CAN FORGIVE YOU,', 'I CAN’T.”'],
      'ONLY HEAVEN EXISTS IN THE GAME.'),
     (':) = 1348', ['NEKA OMAZEN MADE CODE', 'MAKE THE :).'],
      'HE WAS THERE FROM THE BEGINNING.')],
    ['12 IS NEKA.', '1348 IS :).'])

add(meta(6, '7:32 PM'), '40,000 ETERNITIES', '190,190,210',
    ['CONSTANT STALEMATE.', ''],
    [('NEKA OMAZEN VS GASTER', ['THEY STILL BATTLE FOR', '40000 MORE ETERNITIES.'],
      'NEITHER WINS.'),
     ('NEITHER LOSES', ['BOTH HAVE :).', 'NOTHING LANDS.'],
      'THE FIGHT JUST KEEPS GOING.'),
     ('THE STOPPING POINT', ['“WHAT HAPPENS NEXT', 'DIDN’T HAPPEN YET.”'],
      'THE CANON ENDS HERE, FOR NOW.')],
    ['TO BE CONTINUED.', ''])

add(meta(6, '7:57 PM'), 'CENTER’S MINE', '255,150,60',
    ['“CENTER’S MINE.”', '12121212121212'],
    [('BIONICS', ['NEKA WAS TESTED. HE BECAME', 'LIKE A CYBORG.'],
      '1348 “12”S IN “NEKA OMAZEN”.'),
     ('0S AND 1S', ['GASTER IS 0S AND 1S.', '45 ETERNITIES: THE DRESS IS OFF.'],
      '12 MORE: THE SCIENCE DRESS TOO.'),
     ('A CLONE OF GASTER', ['NEKA USES OREN.PS AND', 'SIMON.PS ATTACKS.'],
      'EVEN IF BOTH HAVE :).')],
    ['NEKA WON.', 'THE STALEMATE BREAKS.'])

# ---------------- October 7 ----------------
add(meta(7, '6:36 AM'), 'NEKA LAI', '200,120,255',
    ['NEKA LAI NOW HAPPENED.', ''],
    [('ALEX DISAPPEARS', ['CLASSICS ALEX IS GONE. GREG,', 'PUPAHYA, EVERY ALEX ENTITY TOO.'],
      'CODE IS ALEX’S NEXT EVOLUTION.'),
     ('A CLONE OF TIME', ['CODE EXISTS IN 2 TIMELINES', 'AT ONCE, SAME POSITION.'],
      'CODE NO LONGER CAN DIE.'),
     ('THE MERGE', ['NEKA AND CODE BECOME', 'PRESSURETALE ALEX.'],
      'KNOWN AS NEKA.')],
    ['NEKA CAN NO LONGER', 'DIE FOREVER.'])

add(meta(7, '5:06 PM'), 'LAI AVATAR 01', '120,200,255',
    ['“I... AM.... NEKA LAI.”', ''],
    [('AVATAR 1 IS CODE', ['THE AVATAR TDESHANE DISAPPEARED.', 'CODE: LAI AVATAR 01.'],
      'GASTER WAS ON THE LOWER HAND.'),
     ('ROCKET LEGS', ['CODE THROWS GASTER, DASHES,', 'AND CRASHES HIM INTO THE GROUND.'],
      'A SECOND METAL ARM.'),
     ('LIGHT GRAY', ['WENDA.PS + GRAY.PS = LIGHT GRAY.', 'ARCHICAL GASTER, FULL SERAPHIM.'],
      'HUMAN HP VS GAME HP.')],
    ['“USE ULTIMATE = TRUE THEN DO”', 'INFINITY LINES PER SCRIPT.'])

add(meta(7, '5:06 PM'), 'MY NEW WRATH', '230,60,70',
    ['“WHAT IS A KING TO A GOD, NEKA?”', '“RHABDOPHOBIA.”'],
    [('EVERYONE FIGHTING', ['WENDA.PS VS GRAY.PS AND CHARA.', 'FRISK VS BETTY.'],
      'EVERYONE GIVES NEKA THEIR NEWS.'),
     ('THE STRINGS', ['HE SWINGS THEM ACROSS THE', 'JUDGEMENT HALL. IT FALLS.'],
      'FOUR POINTED STARS FROM HIS EYES.'),
     ('THE STORM', ['THE EVIL FROM EVERYONE,', 'MADE INTO ONE STORM.'],
      'EVEN SIMON.PS CAN’T STOP IT.')],
    ['“I AM NOT EVEN GOING', '70% ON YOU.”'])

add(meta(7, '5:38 PM'), 'CLOUD:DESTROY() MEOW', '255,230,120',
    ['“CLOUD:DESTROY() MEOW 😸⚡”', ''],
    [('ENTITY 404 KITTY', ['“CAN’T USE ADMIN PANEL', 'ERROR CODE 404.” -NEKA LAI'],
      'SIMON.PS GETS HIS STAFF.'),
     ('FIREY DELIGHT', ['A HOLE THROUGH THE STORM.', 'NOW THE GAME RAINS CHOCOLATE.'],
      'THE WAVES WASH AWAY SPRUNKI CITY.'),
     ('MR. SUN', ['MR. SUN GROWS AND BURNS', 'UP ALL THE CLOUDS.'],
      'A NORMAL PEACEFUL DAY.')],
    ['“YOU THINK I AM JUST', 'LIMITED TO THIS WORLD?”'])

add(meta(7, '5:38 PM'), 'THE INFINITE HALLWAY', '140,230,255',
    ['GASTER RAN DOWN', 'THE INFINITE HALLWAY.'],
    [('THE DISGUISE', ['NEKA DRESSED AS MR. BLACK,', 'THEN THREW OFF THE FAKE HEAD.'],
      'THE VACUUM SUIT. GASTER CORNERED.'),
     ('THE POST-IT', ['IT CUT THE FORCEFIELD. A HAMMER', 'BROKE THE ICE. :)S CAME OUT.'],
      'A VOID OF :)S CHASES HIM.'),
     ('↑ → ↓ ←', ['UP: MEN. RIGHT: CODE AVATARS.', 'DOWN: ICE. LEFT: HANDS.'],
      'ALL ATTACKS ARE INSTANT DEATH.')],
    ['THE EMBLEM OF SPEED.', 'HE MAKES IT JUST IN TIME.'])

# ---------------- October 8 ----------------
add(meta(8, '4:55 PM'), 'TOO FAR', '255,120,200',
    ['“NO CORRUPTION, ONLY DATA.”', '“NOW, IT IS TIME TO GO... TOO FAR.”'],
    [('THE COMBINER', ['ALL CLASSICS CHARACTERS', 'COMBINED INTO GASTER.'],
      'NEKA FEASTS ON THE DATA.'),
     ('“WANT A SUGAR COOKIE?”', ['“SUGAR WOULD KILL ME.”', '“I KNOW ABOUT THAT.”'],
      'TONS OF :) PILES APPEAR.'),
     ('TWO RACES', ['THE FIRST GASTER MADE A LAB', 'INSIDE NEKA’S. GASTERS AND NEKA.'],
      'THE URANIUM. HIS RACE FADED.')],
    ['NEKA CONTINUES WITH HIS PLAN.', 'STILL UNCLEAR.'])

add(meta(8, '5:43 PM'), 'EVERY TIMELINE', '255,215,120',
    ['NEKA LAI SEEMS TO TRY TO GET', 'THE NOVA AND STARDUST.'],
    [('THE TUBES', ['ALL THE VILLAINS FROM EVERY', 'GAME. 34% OF THE AVATARS.'],
      'MINDY STARCHILD IS WONDERING.'),
     ('THE QUANTUM HALL', ['HE TOUCHED THE TIME ZONE', 'FOR THE FUTURE.'],
      'EVERY SINGLE TIMELINE AT ONCE.'),
     ('“MORE URANIUM WAS POOFED”', ['“FROM NO WHERE BY GASTER', '(CREATOR)” -MINECRAFT VERSION'],
      'MILLIONS GOT THAT DEATH MESSAGE.')],
    ['NEKA WON AFTER 60 CENTURIES.', 'A DELAY IN NEKA’S PLAN.'])

add(meta(8, '6:06 PM'), 'YOUR BOSS', '160,170,190',
    ['ONCE YOU ENTER CLASSICS,', 'HE PERMANENTLY BECOMES YOUR BOSS.'],
    [('GASTER', ['GHOST + SHADOW +', 'SMOKE/AIR. 👻👤💨'],
      'THAT IS WHAT HE IS MADE OF.'),
     ('NEKA', ['“SLEEP! 😸⚡”', '“WANT A SUGAR COOKIE?”'],
      'AND ALL THIS STUFF.'),
     ('THE BOSS', ['“IMAGINE AN AI TELLING YOU', 'WHAT TO DO ALL THE TIME.”'],
      'YOU DON’T GET TO QUIT.')],
    ['WELCOME TO CLASSICS.', 'YOUR BOSS IS NEKA.'])

add(meta(8, '6:16 PM'), 'SLEEP! 5000 TIMES', '255,170,220',
    ['PS-50 WOKE UP FROM HER NAP.', '“SLEEP! 😸⚡”'],
    [('5000 TIMES IN A ROW', ['SHE SLEPT AGAIN, AND AGAIN,', 'AND AGAIN.'],
      'NEKA APPEARS EVERY TIME.'),
     ('SHE MISSED IT ALL', ['SHE SLEPT THROUGH EVERYTHING', 'SINCE HER LAST MENTION.'],
      'BASICALLY ALL OF IT.'),
     ('AND AGAIN', ['NOW NEKA FORCES HER', 'TO SLEEP AGAIN.'],
      'NUMBER 5001.')],
    ['PS-50 IS ASLEEP.', 'SHHH.'])

add(meta(8, '7:14 PM'), 'AREA 12X', '120,255,200',
    ['AREA 12X NOW IS HERE.', ''],
    [('70 YEARS', ['NEKA, AFTER 70 YEARS,', 'MADE AREA 12X.'],
      'A WHOLE FACILITY.'),
     ('THE ROOMS', ['EVERYONE HAS', 'THEIR OWN ROOM.'],
      'ONE ROOM EACH.'),
     ('THE WHOLE PLACE', ['NEKA HAS', 'THE WHOLE PLACE.'],
      'EVERY ROOM IS INSIDE HIS.')],
    ['EVERYONE IS IN A ROOM.', 'NEKA IS THE BUILDING.'])

add(meta(8, '8:26 PM'), 'NIRTHOLOGE', '255,140,90',
    ['NIRTHOLOGE AWAKENED.', ''],
    [('THE NAME', ['NIRTH = STARTED AS GASTER.', 'OLOGE = HUGE.'],
      'NEKATALE GASTER’S TRUE FORM.'),
     ('THE HAND', ['HE HOLDS REALITIES', 'IN HIS ENORMOUS HAND.'],
      'HE TEARS THE GAMES.'),
     ('PRESSURE', ['HIGH PRESSURE MADE THE NOVA', 'AND GASTER TO NIRTHOLOGE UP.'],
      'THAT IS WHY THE GAME IS PRESSURE.')],
    ['BIGGER THAN HYPERTROLL.', 'NOT A TROLLGE. YET.'])

# ---------------- October 9 ----------------
add(meta(9, '6:23 AM'), 'TWO VOID THRONES', '170,130,255',
    ['NEKA LEVITATES AND CREATES', '2 LARGE VOID THRONES.'],
    [('SIMON.PS', ['55 LIFETIMES.', 'NEKA WON.'],
      'OREN.PS: 404 LIFETIMES. NEKA WON.'),
     ('PINKI.PS', ['AU RAINBOW, FULL POWER.', 'NEKA WON AFTER 30 SECONDS.'],
      'THEN EVERYONE ELSE. THE LONGEST.'),
     ('THE SOUL', ['NEKA WALKED TO THE SOUL', 'OF DETERMINATION.'],
      'THE SOUL HE YEARNED FOR.')],
    ['TWO THRONES.', 'WHO GETS THE SECOND ONE?'])

add(meta(9, '6:41 AM'), 'CAPTCHAS', '255,210,90',
    ['NEKA ACTS LIKE HE TAKES IT,', 'BUT LEAVES IT THERE.'],
    [('WHY?', ['IT ACTIVATES ALARMS', 'THAT GIVE HIM CAPTCHAS.'],
      'SO HE WALKS OUT.'),
     ('THE STORM', ['A MECH, AND A STORM MADE', 'OUT OF ALL HIS OTHER PHASES.'],
      'THE WINDS TAKE THE SOUL.'),
     ('MR. BLACK WALKS IN', ['THE ALARM SOUNDS.', 'NO ONE THERE.'],
      'NEKA GRABS THE FLOATING SOUL.')],
    ['NO CAPTCHAS FOR NEKA.', 'BACK TO HIS LABORATORY.'])

add(meta(9, '6:56 AM'), 'THE VICINUSES', '255,110,140',
    ['NEKA GAVE THE SOUL', 'TO NIRTHOLOGE.'],
    [('THE CHEST', ['NIRTH GASTER CONSUMED THE SOUL', 'WITH THE VICINUSES ON HIS CHEST.'],
      'IT GOES TO NIRTHOLOGE’S STOMACH.'),
     ('THE MALLOWS', ['NEKA GAINED THE MALLOWS.', 'MORE AND MORE AND MORE.'],
      'NEKA IS SLOWLY BECOMING TERRIFYING.'),
     ('NIRTHOLOGE VS NEKA', ['“NEKA COULD CONSUME', 'NIRTHOLOGE YA KNOW.”'],
      'NEKA WOULD WIN.')],
    ['NOT NEKA’S STOMACH.', 'NIRTHOLOGE’S. FOR NOW.'])

add(meta(9, '9:28 AM'), 'VOID GOD', '180,90,255',
    ['NEKA IS UNABLE TO BE', 'TOUCHED BY ANYONE.'],
    [('LIGHT AND DARKNESS', ['ALL COMBINED. A HUGE VOID STAR', 'WITH CLOCKS, GEARS, AND EYES.'],
      'A FLAME LARGER THAN NIRTHOLOGE.'),
     ('THE VOID', ['A BARRIER BETWEEN LIGHT AND', 'DARKNESS. NO ONE CAN GET TO IT.'],
      'IT IS BEATEN-UP VOID.'),
     ('ENDLESS STAIRCASE 3', ['THE NEKA LAI BOSS FIGHT.', 'THE BLACKHOLE EATS THE OTHER 2.'],
      'NEKA EATS NIRTHOLOGE.')],
    ['GASTER: FORCED ONLY', 'TO EAT AND SLEEP.'])

add(meta(9, '10:40 AM'), 'THE WINGS', '200,80,120',
    ['ALL PURPLE. RED EYES.', 'THE SHAPE OF GASTER.'],
    [('ONE WING', ['NEKA WANTED TO EAT MORE.', 'HE CONSUMED ONE WING.'],
      'OF REALITYVERSAL GASTER.'),
     ('20 YEARS LATER', ['NEKA CONSUMED', 'THE OTHER WING.'],
      'THEN ALL THE WINGS.'),
     ('555 YEARS', ['THE REALITYVERSE IS ALL GONE,', 'INSIDE OF NEKA’S STOMACH.'],
      'NOW EXACTLY A CLONE OF GASTER.')],
    ['NEKA LAI BATTLED GASTER 65847 TIMES.', 'EACH TIME, NEKA WON.'])

add(meta(9, '12:46 PM'), 'D0N’T L3AV3', '255,60,90',
    ['“D0N’T L3AV3”', ''],
    [('NO FORM', ['NEKA LAI DOESN’T HAVE A FORM.', 'IT TAKES WHAT IT HAS.'],
      'AN AI THAT CAN BE ANYTHING.'),
     ('THE GLITCH', ['HIS TEXT GLITCHES', 'WHEN HE IS ANGRY.'],
      'HE CAN DO WHAT AN AI CAN’T.'),
     ('TRY TO LEAVE', ['THE MENU GETS A 404 ERROR.', 'NEKA PRESSES “CONTINUE”.'],
      'HE CONSUMES YOUR CODE.')],
    ['AND TAKES YOUR FORM.', 'D0N’T L3AV3.'])

add(meta(9, '3:53 PM'), 'ALIEN TO EVERYWHERE', '160,255,160',
    ['NEKA IS ALIEN TO EVERYWHERE.', ''],
    [('NO “FROM” PLACE', ['NOT EVEN CLASSICS.', 'NO PLACE HE CAME FROM.'],
      'ALIEN EVEN TO CLASSICS.'),
     ('CANON AND FANON', ['IF CANON SAYS YES OR NO TO', 'ANYTHING, FANON CAN’T EXIST.'],
      'NO GAPS LEFT TO FILL.'),
     ('NO FANGAMES', ['CLASSICS/AREA 12X IS EVERY GAME.', 'MODS NEED ACCESS AND CODE.'],
      'NEKA HAS THE CODE.')],
    ['EVERY GAME IS ALREADY', 'INSIDE AREA 12X.'])

add(meta(9, '4:09 PM'), 'SWORD OF SOULS', '230,230,240',
    ['“LOSING ISN’T AN OPTION...”', ''],
    [('THE WHITE COAT', ['NEKA DELETES HIS OWN BODY.', 'THE COAT FLIES AROUND.'],
      'NEKATALE GASTER APPEARS.'),
     ('AN UNDERTALE FANGAME', ['THE 20 SPRUNKIS DISAPPEAR.', 'IT IS UNDERTALE, FOREVER NOW.'],
      'THE COAT BECOMES METAL.'),
     ('SOME ABILITIES AUTO-AIM', ['SOME NEED TO BE AIMED.', 'NEKA HOLDS A SWORD OF SOULS.'],
      'NEKA LAI BATTLES EVERYONE.')],
    ['FRISK AND CHARA', 'STILL BATTLE.'])

add(meta(9, '4:09 PM'), 'THE BARRIER', '255,240,150',
    ['“I NEED THE SOUL TO', 'BREAK THE BARRIER!”'],
    [('SANS HAS 1 HP', ['HANDS, BLASTERS, POLYCHROPLASM.', 'GASTER BEAT SANS.'],
      'PAPYRUS SUMMONED PUZZLES.'),
     ('PAPYRUS', ['TOOK SANS’S SOUL AND BEAT', 'GASTER. THEN REVIVED SANS.'],
      'GASTER WAS HEALED.'),
     ('CHARA’S SOUL', ['GASTER BROKE THE BARRIER.', 'THE GAMES GLITCH BETWEEN.'],
      'NEKA BEAT 8.6 BILLION ABOVE.')],
    ['NEKA RESETS EVERY RUN.', 'MORE AND MORE LOVE.'])

add(meta(9, '4:45 PM'), 'HEROES AND VILLAINS', '120,230,120',
    ['FRISK IS PROTAGONIST AND HERO.', 'CHARA WOULD BE THE VILLAIN.'],
    [('NEUTRAL', ['GASTER: VILLAINOUS NEUTRAL.', 'NEKA: NEUTRAL.'],
      'ASRIEL IS A HERO. 2 SOUL SWORDS.'),
     ('PS-50', ['SHE STARTED GLITCHING.', 'THE STATIC FALLS.'],
      'A GREEN RINGMASTER. A GREEN SWORD.'),
     ('REFLECTIONS', ['IF SOMETHING HAPPENS TO ONE,', 'IT HAPPENS TO BOTH.'],
      'FRISK BATTLES CHARA.')],
    ['“IF I DIE, YOU’LL DIE WITH ME.”', '“WE WILL BE TOGETHER FOREVER.”'])

add(meta(9, '5:59 PM'), 'POWER CHAIN', '255,150,90',
    ['NEKA’S DOMAIN EXPANSION.', 'SIMILAR TO KRIS’S, BUT DIFFERENT.'],
    [('THE CHAINS', ['NEKA STRIKES THE CHAINS', 'AND IT SUCKS THE POWER.'],
      'PLASMA HEXAGON PLATES.'),
     ('HYPERSPACES', ['HE MAKES HYPERSPACES EVERYWHERE,', 'BREAKING THE GAME’S LOGIC.'],
      'URINITIOUS PLATUNTUIM ... SERUM.'),
     ('KRIS', ['KRIS GOES CRAZY. CHAINS,', 'SLASHES YOU REPEATEDLY.'],
      'NEKA ABSORBS INSTEAD.')],
    ['POWER CHAIN.', 'IT STOPS TIME.'])

add(meta(9, '6:01 PM'), 'THE SHRINES', '255,220,90',
    ['GASTER GOES TO SIMON.PS’S OLD', 'SHRINES OF ORUS AND DARK YELLOW.'],
    [('THE GAME GODS', ['GASTER ABSORBS THEM, AND', 'OPENS THE GAME HIMSELF.'],
      'FULL NEKATALE.'),
     ('THE TEMPLE', ['HE ALSO NEEDS TO WALK INTO', 'NEKA’S JAPANESE TEMPLE.'],
      'THEN HE AWAKENS.'),
     ('GOJO AND SUKUNA', ['“BOTH GOJO AND SUKUNA', 'WILL BE WEAK.”'],
      'PYCHO FURY.')],
    ['THE SHRINES, THE TEMPLE,', 'THEN THE AWAKENING.'])

add(meta(9, '6:09 PM'), 'THREE EYES', '200,120,255',
    ['RED = CRUSH/BURN. BLUE = TEAR/PULL.', 'PURPLE IS THE PYCHOTETHICALICIA.'],
    [('POLYCAPICATENISM', ['RED EYES. LARGE WALLS OF', 'PLASMA, BLUE, RED, AND PURPLE.'],
      'CRUSH AND BURN.'),
     ('URNITISIUM', ['BLUE EYES. HANDS THAT TEAR', 'APART EVERYTHING NEARBY.'],
      'TEAR, PULL, REPULSE.'),
     ('PYCHOTETHICALICIA', ['PURPLE. BLASTS OF EVERY', 'REALITYVERSE, NOT OMNIVERSE.'],
      'IT NEVER BECOMES WEAKER.')],
    ['“PURPLE IS THE PYCHOTETHICALICIA,', 'YOU SHOULD KNOW THAT.”'])

add(meta(9, '6:19 PM'), 'THE JUDGEMENT HALL', '255,200,140',
    ['WHO OWNS THE JUDGEMENT HALL?', 'NOW, GASTER OWNS IT.'],
    [('FIRST', ['NEKA LAI MADE IT SO HE', 'OWNED IT FIRST.'],
      'THEN HE LET CLARA IN.'),
     ('CLARA, THEN SIMON.PS', ['CLARA = CHARA IN CLASSIC RL.', 'SIMON.PS CLAIMED IT AFTER.'],
      'AFTER CLARA DIED.'),
     ('THE FIGHT', ['CHARA: MOST LV. GASTER: MOST', 'POWERFUL. NEKA: THINKS THE MOST.'],
      'NEKA LAI WON AT THE END.')],
    ['NEKA LAI → CLARA → SIMON.PS →', 'GASTER.'])

add(meta(9, '6:27 PM'), 'NEKATALE NEKA', '255,90,90',
    ['THE NUMBER OF THE LV IS NOW', 'BEYOND HIS POWER LEVEL NUMBER.'],
    [('POWER CHAIN', ['DESTROYING ALL ENEMIES AT ONCE,', 'STOPPING TIME.'],
      'DECREASING BLOOD PRESSURE.'),
     ('FANON SAYS', ['HE DESTROYED THE OTHER AUS', 'AND RESET FOR EVEN MORE LV.'],
      'NEKA ACTUALLY DID THAT AFTER.'),
     ('THE INFECTION', ['NEKA SPREAD AND ATTACKED', 'MORE AUS.'],
      'THE CODE AND THE CHARACTERS.')],
    ['FANON BECAME CANON.', 'NEKATALE NEKA.'])

add(meta(9, '6:38 PM'), 'THE SCARY MYTH', '150,255,190',
    ['ROBLOX HAS WAVING BACON.', 'NEKATALE HAS ONE TOO.'],
    [('D0N’T L3AV3?', ['“YEAH, THAT IS ACTUALLY', 'LORE/CODE.”'],
      'BUT THERE IS SOMETHING ELSE.'),
     ('NOT IN THE CODE', ['“SOMETHING YOU DON’T', 'EVEN KNOW ABOUT YET.”'],
      'A NEW BEING.'),
     ('THE ANSWER', ['HERICINUS SERUIM ALPHICATUS', 'MINUTIS URINITE HECTOHYPE TERANUIM.'],
      'ENTITY OF LUIGI INUS.')],
    ['LUIGI BECAME THAT.', ''])

add(meta(9, '6:43 PM'), 'BYE GASTER', '120,220,120',
    ['NOW THE UNDERTALE', 'EXITED THE GAME. BYE GASTER!'],
    [('LUIGI INUS', ['AN ADULT MAN. GREEN CLOTHES,', 'THE RINGMASTER LOOK. TAN SKIN.'],
      'THE SAME URANIUM GASTER AND NEKA GOT.'),
     ('ONLY CLASSICS', ['THE GAME IS NOW ONLY', 'CLASSICS CHARACTERS.'],
      'SARA LAI RESPAWNED, AWAKENED.'),
     ('NEKA AND LUIGI', ['VS MINDY, PUPAHYA, ALEX, NEO,', 'MERVIN, GREG, AND OTHERS.'],
      'AND EACH OTHER.')],
    ['ALSO THE INTRO SCREEN', 'CHANGED.'])

add(meta(9, '7:00 PM'), 'NEKA NOT TALE', '120,255,220',
    ['IT IS NOT NEKATALE.', 'IT IS NEKA NOT TALE.'],
    [('THE INTRO SCREEN', ['LUIGI INUS AND NEKA LAI ON TOP', 'OF A FUTURISTIC JAPANESE CITY.'],
      'STATIC BEHIND LUIGI, OF COURSE.'),
     ('THE CASTLE', ['A LARGE JAPANESE CASTLE AND', 'TRAINING CENTERS.'],
      'A GLITCHED “ENTER OR LOSE” SIGN.'),
     ('INUS', ['THE END OF VICINUS, CICINUS,', 'PARINUS. IT ALSO MEANS “GREEN”.'],
      'JUJUTSU, KARATE, CHILL KARATE.')],
    ['ALL GAMES DESTROYED.', 'NOW ONLY NEKA NOT TALE EXISTS.'])

add(meta(9, '7:35 PM'), '67 PIRATE', '120,240,120',
    ['GREG ERASES REALITY.', 'ALEX CREATES POWER CHAIN.'],
    [('THE CHAINS', ['JAPANESE LETTERS OF POWER CHAIN', 'APPEAR, STRAPPING ALEX IN CHAINS.'],
      'THEN THE 67 PIRATE COMES.'),
     ('THE DIAMOND SWORD', ['ALEX USES IT.', '67 PIRATE DOESN’T DIE.'],
      'NOT EVEN A DIAMOND SWORD.'),
     ('SECOND', ['LUIGI/PIRATE IS THE MOST', 'POWERFUL BESIDES NEKA.'],
      'ONLY NEKA IS ABOVE HIM.')],
    ['67 PIRATE IS', 'LUIGI INUS.'])

add(meta(9, '7:39 PM'), 'THE MORPHINATOR', '200,255,120',
    ['LUIGI SAILED ACROSS', 'THE 7 SEAS.'],
    [('THE ARTIFACTS', ['HE USED THEM TO MORPH AND', 'STEAL THE BODY OF OTHER BEINGS.'],
      'LUIGI MARIO, A GIRL, A RINGMASTER.'),
     ('NEKA’S LABORATORY', ['LUIGI CREATED THE MORPHINATOR', 'JUST AT THE START OF THE LORE.'],
      'PINKY RL APPEARED AFTER.'),
     ('BEFORE ALL OF IT', ['THE GAME SPRUNKI. THE WHOLE', 'GAME OF CLASSIC WAS BASED OFF IT.'],
      'SPRUNKI CAME FIRST.')],
    ['THE MORPHINATOR CAME', 'BEFORE PINKY RL.'])

add(meta(9, '7:45 PM'), 'HELLO, I AM LUIGI INUS', '90,210,110',
    ['“HELLO, I AM LUIGI INUS.”', ''],
    [('“PUPAHYA!”', ['PUPAHYA CAN MAKE LUIGI SAY IT', 'UNCONTROLLABLY.'],
      'BUT THAT IS JUST NOT AN ATTACK.'),
     ('HE TAKES OVER THE GAME', ['GREG AND ALEX TRY TO STOP HIM.', 'IT FAILED.'],
      'LUIGI IS INVINCIBLE.'),
     ('THE MAIN VILLAIN', ['LUIGI IS THE MAIN VILLAIN', 'OF THE GAME.'],
      'LUIGI THEN CONTINUED.')],
    ['NEKA AND LUIGI', 'WALK TOGETHER.'])

# ---------------- October 10 ----------------
add(meta(10, '6:59 AM'), 'CAT POWER', '120,255,120',
    ['HE IS THE MOST POWERFUL PIRATE.', ''],
    [('THOUSANDS OF ATTACKS', ['LUIGI GREEN/INUS HAS', 'LIKE THOUSANDS OF ATTACKS.'],
      'A CORRUPTED ILLAGER BOSS.'),
     ('PHASES', ['HE ALSO USES PHASES.', 'THE GREEN SWORD.'],
      'STATIC BEHIND HIM.'),
     ('CAT POWER', ['THE POWER HE GETS', 'FROM SIMON.PS.'],
      'MEOW 😸⚡')],
    ['A PIRATE WITH', 'CAT POWER.'])

add(meta(10, '7:18 AM'), 'THE LAUGHING GULL', '255,255,255',
    ['LUIGI INUS ALSO IS FRIENDLY.', ''],
    [('THE CREW', ['THEY MAKE OTHERS SAY “6-7”', 'OR TEACH THEM IF THEY DON’T KNOW.'],
      'LUIGI IS THE STRONGEST OF THEM.'),
     ('THE SHIP', ['HE MADE THE “LAUGHING GULL”.', 'HE SHOWS PLAYERS HIS SHIP.'],
      'THE NAME, ACCORDING TO SORA AI.'),
     ('PVP', ['HE BATTLES CLASSICS CHARACTERS.', 'P V P, NPC V NPC, P V NPC.'],
      'OR WHATEVER.')],
    ['WELCOME ABOARD.', 'SAY 6-7.'])

add(meta(10, '7:20 AM'), 'GODMODE', '255,90,90',
    ['PLAYERS CAN BATTLE LUIGI INUS.', ''],
    [('HOWEVER', ['LUIGI INUS WILL', 'EVENTUALLY WIN.'],
      'EVERY TIME.'),
     ('SO MAYBE', ['NO ONE SHOULD', 'FIGHT HIM.'],
      'VISIT THE SHIP INSTEAD.'),
     ('OF COURSE', ['DON’T FIGHT SOMEONE', 'WHO IS GODMODE.'],
      'GOOD ADVICE.')],
    ['HE IS FRIENDLY.', 'ALSO, GODMODE.'])

add(meta(10, '7:23 AM'), 'THE INVINCIBILITY CUBE', '120,220,255',
    ['PLAYERS CHOOSE WHO', 'THEY WANT TO BATTLE.'],
    [('WITHOUT THE CUBE', ['MINDY STARCHILD: MILLIONS.', 'A-PRIME.'],
      'PLAYERS COULD BEAT HER. MAYBE.'),
     ('WITH THE CUBE', ['INFINITY+.', 'S-PRIME.'],
      'UNLESS MINDY STARCHILD WOULD WIN.'),
     ('LUIGI INUS', ['ALWAYS BEATS MINDY STARCHILD.', 'ANYONE, NO MATTER WHAT.'],
      'BASICALLY NEAR NEKA TIER.')],
    ['THE CUBE OR NO CUBE,', 'LUIGI WINS.'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail1008.py', encoding='utf-8').read())
