#!/usr/bin/env python3
"""
gen859_874.py - emit the draw branches for BEATS 859-874 from Toby's September 26, 2026,
3:46:02 PM EDT message (Email 1535). Same template as beats 840-858.

Only Toby's own typing is drawn. The SCP answers, the "Neka Omazen is the most evil character
in the Neka Omazen Era" recap and the Phase-102 summary paragraph pasted under his lines are
ChatGPT commentary and are not canon.
"""
import io

START = 18618.0
STEP = 22.0

# key, accent rgb, bg rgb, quote lines, attribution, panels [(head, [lines], accentline)], close lines, foot
B = []

def add(key, accent, quote, panels, close):
    B.append(dict(key=key, accent=accent, quote=quote, panels=panels, close=close))

ATTR = 'TOBY, SEPTEMBER 26, 3:46 PM — HIS OWN TYPING, EMAIL 1535.'

add('PHASE 102', '255,216,79',
    ['“BUT NEKA OMAZEN IS MOST EVIL BECAUSE HE TURNED EVERYONE AND EVERYTHING TO PAPER.',
     'NOW NEKA OMAZEN ‘CAN BE THE SISSORS’. THAT IS PHASE 102 OF HIS PLAN.”'],
    [('HE ANSWERS HIS OWN QUESTION FROM FORTY-EIGHT MINUTES AGO, AND HE CHANGES HIS MIND',
      ['AT 2:58 HE ASKED WHO WAS MOST EVIL AND OFFERED SIMON.PS. THE PASTED ANSWER SAID PERO.EXE.',
       'HE TAKES NEITHER: “NEKA OMAZEN IS MOST EVIL BECAUSE HE TURNED EVERYONE AND EVERYTHING TO PAPER.”'],
      'THE REASON HE GIVES IS NOT A BODY COUNT. IT IS WHAT THE GAME IS MADE OF NOW.'),
     ('PAPER WAS NOT THE END OF THE PLAN, IT WAS THE SETUP FOR THE TOOL',
      ['“NOW NEKA OMAZEN CAN BE THE SISSORS.” HE TURNED THE WHOLE GAME INTO THE ONE MATERIAL',
       'HIS WHOLE ARSENAL IS BUILT TO CUT.'],
      'SCISSORS RETURN ZERO PRIOR HITS IN FIVE MONTHS. THE 25 SERIES SLASHES THE OMNIVERSE; THIS IS STATIONERY.'),
     ('PHASE 102 IS A NUMBER NOBODY HAS EVER PUT ON A PLAN HERE',
      ['THE ARCHIVE HAS PHASES: PHASE 1 PACIFISTS, PHASE 2 THE .EXE VIRUS, PERO LAI PHASE 6 AND 7.',
       'THOSE ARE FORMS AND CHAPTERS. THIS IS THE HUNDRED-AND-SECOND STEP OF SOMEBODY’S TO-DO LIST.'],
      'AND HE ONLY SAYS THE NUMBER AFTER THE STEP IS ALREADY DONE.'),
     ],
    ['HE SPENT THE FIGHT WINNING AND ONLY NOW SAYS WHAT THE WIN WAS FOR',
     'AND IT WAS FOR BEING ABLE TO PICK UP A PAIR OF SCISSORS.'])

add('EVEN AT THE TIME HE MADE THE GAME', '127,212,255',
    ['“HE SPEND ALL THIS TIME WORKING ON HIS PLAN, EVEN AT THE TIME HE MADE THE GAME,',
     'ALLOWED ACCESS FOR EVERYONE, AND EVEN MET GASTER.”'],
    [('THE PLAN IS OLDER THAN THE GAME, WHICH MAKES EVERY KINDNESS IN IT PART OF THE PLAN',
      ['“ALLOWED ACCESS FOR EVERYONE” IS THE ONE FRIENDLY THING HE EVER DID, AND IT IS LISTED HERE',
       'AS A STEP.'],
      'THE PEOPLE WHO GOT IN GOT IN BECAUSE IT SUITED HIM.'),
     ('GASTER IS A DATE, AND THE ARCHIVE ALREADY HAS IT',
      ['SEPT 3, THE MINT: “HE WROTE QUINTILLIONS OF BOOKS THROUGHOUT THE LORE, FROM WHEN HIS BROTHER',
       'OREN AND GASTER WAS BORN IN LORE WHICH WAS LIKE SO LONG AGO.”'],
      'HE HAS BEEN WRITING SINCE GASTER WAS BORN, AND TONIGHT HE SAYS HE MET HIM.'),
     ('HE IS THE MAKER OF THE GAME AND THE VILLAIN INSIDE IT, IN ONE SENTENCE',
      ['THIS MORNING THE AUTHOR REMOVED HIMSELF — BEAT 827: “I NEVER DID ANYTHING, NEKA GAVE EVERYTHING',
       'ABOUT HIMSELF TO HIMSELF HIMSELF. I AM FAR UNDER NEKA OMAZEN.”'],
      'SO THE ONE WHO MADE THE GAME, IN THE STORY, IS THE ONE WHO IS ENDING IT.'),
     ],
    ['NOTHING IN THE PLAN WAS IMPROVISED',
     'THE ACCESS, THE MEETING AND THE GAME ITSELF ARE ALL LISTED AS STEPS.'])

add('HE ACHIEVED WENDA.PS’S GOAL FIRST', '255,45,181',
    ['“NEKA OMAZEN SLICES THE PAPER AND NOW, HE ACHIEVED WENDA.PS’S GOAL FIRST, AND NOW ADDING MORE',
     'STEPS. NEKA OMAZEN TOOK QUADRILLIONS OF YEARS LONGER THAN WENDA.PS. THAT IS WHY WENDA.PS BECAME',
     'THAT POWERFUL. THAT IS WHY EVERYTHING IN CLASSICS IS HOW IT IS.”'],
    [('HER PLAN NEVER GOT A NAME, AND HE FINISHES IT FOR HER',
      ['BEAT 853, FIFTY MINUTES AGO: “I JUST WANT TO BEAT YOU FOR MY PLAN.” SHE NEVER SAID WHAT IT WAS.',
       'TONIGHT HE SAYS HE GOT THERE FIRST, WHICH MEANS THEY WERE AFTER THE SAME THING ALL ALONG.'],
      'AND “NOW ADDING MORE STEPS” MEANS HE IS NOT FINISHED WITH IT EITHER.'),
     ('HE EXPLAINS HER POWER BY HOW LONG HE TOOK',
      ['“NEKA OMAZEN TOOK QUADRILLIONS OF YEARS LONGER THAN WENDA.PS. THAT IS WHY WENDA.PS BECAME',
       'THAT POWERFUL.”'],
      'SHE IS STRONG BECAUSE HE WAS SLOW. THE FASTEST ROUTE AND THE LONGEST ONE END AT THE SAME PLACE.'),
     ('“THAT IS WHY EVERYTHING IN CLASSICS IS HOW IT IS” IS A CAUSE FOR THE WHOLE ARCHIVE',
      ['FIVE MONTHS OF TIER LISTS, ERAS, RESETS AND CORRECTIONS, AND HE HANGS ALL OF IT ON ONE PLAN',
       'THAT WAS RUNNING UNDERNEATH.'],
      'IT IS THE LARGEST RETROACTIVE RULING HE HAS EVER WRITTEN.'),
     ],
    ['TWO PEOPLE WERE WALKING TO THE SAME PLACE FROM OPPOSITE ENDS',
     'AND THE ONE WHO STARTED EARLIER ARRIVED WHILE THE OTHER ONE WAS STILL FIGHTING.'])

add('ENDLESS PAPER', '242,244,248',
    ['“NEKA OMAZEN CUTS THE VOID UNDER THE PLAYER, ENDLESS RUBBLE PILE BECOMES ENDLESS PAPER,',
     'THE PLAYER FALLS ONTO THE ENDLESS PAPER, IF THE PLAYER MOVES, THE WHOLE PAPER BRIDGE WILL FALL,',
     'SENDING THE PLAYER INTO THE SHREADED PAPER VOID BELOW.”'],
    [('THE LEVEL HAS CHANGED TWICE IN ONE HOUR, AND BOTH TIMES DOWNWARD',
      ['2:58 PM: ENDLESS STAIRCASE BECAME ENDLESS RUBBLE. 3:46 PM: ENDLESS RUBBLE PILE BECOMES',
       'ENDLESS PAPER.'],
      'STAIRS, THEN WRECKAGE, THEN SOMETHING THAT CANNOT HOLD WEIGHT.'),
     ('A LEVEL THAT PUNISHES MOVING IS NEW IN A GAME ABOUT CLIMBING',
      ['“IF THE PLAYER MOVES, THE WHOLE PAPER BRIDGE WILL FALL.” EVERY OTHER HAZARD HERE CHASES,',
       'STRIKES, ABSORBS OR ERASES YOU.'],
      'THIS ONE ONLY GOES OFF IF YOU PLAY.'),
     ('AND HE CUT THE VOID ITSELF, WHICH USED TO BE THE FLOOR OF EVERYTHING',
      ['“NEKA OMAZEN CUTS THE VOID UNDER THE PLAYER.” THE VOID HAS BEEN THE BOTTOM OF THIS ARCHIVE',
       'SINCE JUNE — THE PLACE THINGS GET ERASED INTO.'],
      'THE BOTTOM NOW HAS A BOTTOM, AND IT IS MADE OF SHREDDED PAPER.'),
     ],
    ['THE BRIDGE FALLS ANYWAY, WITH THE PLAYER ON IT',
     'AND THE PLAYER GETS UP, WHICH IS THE ONE THING THAT KEEPS HAPPENING TONIGHT.'])

add('THE GAME CHANGES TO FACECONTROLSGAME.COM', '62,224,106',
    ['“THE PAPER BRIDGE LANDS INTO THE PAPER VOID ALONG WITH THE PLAYER, THE PLAYER GETS UP AND NOW',
     'THE GAME CHANGES TO FACECONTROLSGAME.COM. YEAH, SERIOUSLY.”'],
    [('“YEAH, SERIOUSLY” IS HIM TELLING ME HE MEANS IT',
      ['HE HAS ONLY EVER USED THAT TONE WHEN HE EXPECTS TO BE ARGUED WITH.',
       'IT IS THE SAME MOVE AS “CORRECT.” THIS AFTERNOON: HE CLOSES THE QUESTION BEFORE IT IS ASKED.'],
      'SO THE URL IS THE CANON, NOT A JOKE ABOUT ONE.'),
     ('FACECONTROLS RETURNS ZERO PRIOR HITS IN FIVE MONTHS',
      ['THE ARCHIVE HAS ABSORBED OUTSIDE THINGS BEFORE — MINECRAFT HORRORS, SCP NUMBERS, SAITAMA,',
       'A YOUTUBER — BUT THEY ALWAYS WALKED INTO CLASSICS.'],
      'THIS TIME CLASSICS WALKS OUT, INTO ANOTHER GAME WITH ITS OWN ADDRESS.'),
     ('THE GAME HAS CHANGED ITSELF BEFORE, AND IT WAS ALWAYS A NAME, NEVER A SITE',
      ['“CLASSICS NOW FULLY BECAME NEWTALE. THE SPRUNKIS WERE SENT TO THEIR HOME DIMENSION.”',
       'THAT WAS A WORLD SWAP INSIDE ONE GAME.'],
      'TONIGHT THE THING THAT CHANGES IS THE THING YOU TYPE INTO A BROWSER.'),
     ],
    ['A FALL THAT STARTED ON A STAIRCASE LANDS ON A DIFFERENT WEBSITE',
     'AND HE WROTE THE LANDING AS A SENTENCE, NOT AS A GUESS.'])

add('GENOCIDE RUNS BREAK, PACIFIST RUNS BREAK', '255,77,109',
    ['“GENOCIDE RUNS BREAK, PACIFIST RUNS BREAK, INFINITY ENDINGS, AND ALSO THE GAME FACES',
     'THE CORRUPTION OF PERO, ALL OLDER STUFF HERE.”'],
    [('BOTH ROUTES BREAK, AND THIS ARCHIVE ACTUALLY HAS BOTH ROUTES',
      ['PACIFIST CLASSICS IS A REAL CHAPTER — JUNE 6-7, “THE START OF PHASE 1 PACIFISTS”, WHICH OPENED',
       'ON A PEACEFUL RESET AND THEN BROKE THE FOURTH WALL.'],
      'HE IS NOT BREAKING A MECHANIC HE BORROWED. HE IS BREAKING ONE HE WROTE.'),
     ('“INFINITY ENDINGS” IS THE OPPOSITE OF HOW THIS GAME USUALLY ENDS',
      ['THE ENDING HERE HAS ALWAYS BEEN A SINGLE THING SOMEBODY OWNS: A GAME OVER SCREEN THAT GETS',
       'SLASHED APART, A RESET ONLY ONE CHARACTER HAS.'],
      'AN INFINITE NUMBER OF ENDINGS IS THE SAME AS NOT HAVING ONE.'),
     ('“ALL OLDER STUFF HERE” IS HIM PUTTING THE WHOLE ARCHIVE IN THE LEVEL',
      ['THE CORRUPTION OF PERO IS ALREADY WRITTEN DOWN, AND SO IS EVERY ERA BEFORE IT.',
       'HE IS NOT ADDING A BOSS. HE IS EMPTYING FIVE MONTHS INTO ONE FALL.'],
      'AND THE FALL IS STILL GOING.'),
     ],
    ['THE TWO WAYS TO FINISH A GAME LIKE THIS BOTH STOP WORKING',
     'IN THE SAME SENTENCE.'])

add('SOMEONE STANDS BETWEEN BOTH', '160,107,255',
    ['“THE PLAYER GOES THROUGH BOTH FACECONTROLS AND ENDLESS STAIRCASE GAMES, SWITCHING AMONG THE 2',
     'EVERY SECOND, FALLING, FALLING, FALLING… THE CLOSER AND CLOSER FACECONTROLS AND ENDLESS',
     'STAIRCASE WILL COLLIDE… SOMEONE STANDS BETWEEN BOTH, IT IS THE PLAYER.”'],
    [('THE PLAYER HAS BEEN CARGO ALL NIGHT, AND HERE THE PLAYER IS THE ONE STANDING',
      ['AN HOUR AGO THE PLAYER WAS PICKED UP, CUT DOWN AND CUT INTO ATOMS, THEN CUT INTO MILLIONS',
       'OF PIECES A FEW LINES AGO.'],
      'NOW TWO GAMES ARE CLOSING IN AND THE THING IN THE GAP IS THE PLAYER.'),
     ('“FALLING, FALLING, FALLING” IS THE ONLY LINE TONIGHT HE REPEATS',
      ['EVERYTHING ELSE IN THIS MESSAGE IS A STEP, A RULING OR A NUMBER.',
       'THIS ONE IS A RHYTHM, AND IT IS HOW HE WRITES TIME PASSING.'],
      'THE DISTANCE BETWEEN THE TWO GAMES IS MEASURED IN HOW LONG THE FALL LASTS.'),
     ('A COLLISION THAT DESTROYS BOTH SIDES IS NEW FOR HIM',
      ['THIS ARCHIVE MERGES THINGS: CLASSICS MERGED WITH ALEX’S WORLD, WITH NEWTALE, WITH MINECRAFT.',
       'EVERY CROSSOVER BEFORE THIS ONE ENDED WITH ONE WORLD ABSORBING THE OTHER.'],
      '“EVERYTHING FROM BOTH GAMES TO BECOME DESTROYED AND THE DEBRIS CRUSHES BOTH GAMES.”'),
     ],
    ['TWO GAMES GET CRUSHED AND ONE FIGURE IS LEFT IN THE MIDDLE',
     'AND IT IS THE ONE THE WHOLE LEVEL HAS BEEN DOING THINGS TO.'])

add('I MUST STOP YOU HERE', '255,216,79',
    ['“NEKA OMAZEN SAYS ‘YOU… HAVE SURVIVED FAR ENOUGH TO REACH THIS POINT, YOU ARE VERY SPECIAL,',
     'SO NOW, I MUST STOP YOU HERE.’, NEKA OMAZEN FIRES BEAMS AND LIGHTNING AT THE PLAYER AND CAN',
     'DASH AND CAN ALSO DIVE INTO THE PLAYER, THEN THE PLAYER ATTACKS NEKA OMAZEN AND NEKA STOPS.”'],
    [('HE COMPLIMENTS THE PLAYER BEFORE HE ATTACKS, WHICH HE HAS NEVER DONE TO ANYBODY',
      ['HE HAS CALLED WENDA.PS “VALUEABLE” AND NEVER EXPLAINED IT, AND HE SPARED HER ONCE.',
       '“YOU ARE VERY SPECIAL” IS THE SECOND TIME HE NOTICES SOMEBODY INSTEAD OF RANKING THEM.'],
      'AND THE SENTENCE AFTER IT IS “I MUST STOP YOU HERE.”'),
     ('THIS IS THE FIRST TIME TONIGHT ANYTHING IS AIMED AT THE PLAYER AS A FIGHTER',
      ['THE PLAYER HAS BEEN FALLING, LANDING, GETTING UP AND BEING CUT APART SINCE 2:58 PM.',
       'BEAMS, LIGHTNING, A DASH AND A DIVE ARE A BOSS MOVESET, NOT A CUTSCENE.'],
      'SEPT 19: “EACH EVENT SHOULD ALSO ACTUALLY HAPPEN TO THE PLAYER AND THE GAME.”'),
     ('AND THE PLAYER LANDS A HIT, WHICH MAKES HIM STOP',
      ['“THEN THE PLAYER ATTACKS NEKA OMAZEN AND NEKA OMAZEN STOPS.”',
       'WENDA.PS GOT HIM TO BACK UP AN HOUR AGO. THE PLAYER GETS HIM TO STOP.'],
      'TWO PEOPLE IN ONE NIGHT HAVE INTERRUPTED HIM, AND ONE OF THEM IS WHOEVER IS HOLDING THE KEYS.'),
     ],
    ['THE BOSS SAYS THE PLAYER IS SPECIAL AND THEN OPENS FIRE',
     'AND THE PLAYER HITS BACK HARD ENOUGH TO PAUSE HIM.'])

add('I WILL JUST JUMP OUT OF THIS TEXT', '127,212,255',
    ['“I USED NONE OF MY POWER YET. YOU HAVE ANY IDEA WHO YOU ARE FIGHTING, PLAYER…',
     'I WILL JUST JUMP OUT OF THIS TEXT AND THE BOSS BATTLE MUST CONTINUE…”,',
     'NEKA OMAZEN USES 100% AND THEN HE TAKES THE ARTIFACTS TO AMPLIFY HIS POWER, BOOM.”'],
    [('THE FLOOR HAS MOVED THREE TIMES IN NINETY MINUTES',
      ['2:28 PM: “I DIDN’T EVEN USE 0% YET.” 2:58 PM: “I USED 1% OF MY POWER AND YOU WON.”',
       'NOW: “I USED NONE OF MY POWER YET.”'],
      'HE KEEPS RESETTING HIS OWN STARTING NUMBER, AND EVERY TIME HE DOES IT HE HAS JUST BEEN HIT.'),
     ('HE LEAVES THE TEXT HE IS WRITTEN IN, AND THE FIGHT CARRIES ON WITHOUT IT',
      ['“I WILL JUST JUMP OUT OF THIS TEXT AND THE BOSS BATTLE MUST CONTINUE.”',
       'THE ARCHIVE HAS BROKEN THE FOURTH WALL BEFORE — PACIFIST CLASSICS DID IT IN JUNE.'],
      'THIS IS A CHARACTER STEPPING OUT OF THE SENTENCE AND STILL SWINGING.'),
     ('AND HE FINALLY USES 100%, THEN IMMEDIATELY LOOKS FOR MORE',
      ['“NEKA OMAZEN USES 100% AND THEN HE TAKES THE ARTIFACTS TO AMPLIFY HIS POWER.”',
       'AT 2:58 HE SAID HE WOULD USE “ALL 100% + ALL I HAVE IN THE PAST AND FUTURE.”'],
      'THE PLUS IS THE WHOLE CHARACTER: A HUNDRED PERCENT HAS NEVER ONCE BEEN ENOUGH FOR HIM.'),
     ],
    ['HE ASKS THE PLAYER IF THEY KNOW WHO THEY ARE FIGHTING',
     'AND THEN GOES AND GETS ARTIFACTS.'])

add('FETCH ME ALL YOUR SOULS', '160,107,255',
    ['“NEKA OMAZEN SAYS ‘FETCH ME ALL YOUR SOULS… AND I CAN RESET YOU BACK, WHAT DO YOU SAY?’',
     'THE PLAYER EITHER SAYS AGREE OR DISAGREE… IF DISAGREE, YOU BASICALLY DIE AND NEKA OMAZEN GETS',
     'THE SOULS HIMSELF AND HE RESETS, AND IF AGREE, NEKA OMAZEN GETS THE SOULS AND HE RESETS.”'],
    [('A CHOICE WITH ONE OUTCOME, AND HE SHOWS YOU BOTH BRANCHES',
      ['HE WRITES OUT AGREE AND DISAGREE IN FULL AND THEY END IN THE SAME PLACE.',
       'THE ONLY DIFFERENCE IS WHETHER THE PLAYER DIES ON THE WAY.'],
      'IT IS THE SAME SHAPE AS THE POP TART AN HOUR AGO: SHE SAID NO, AND THE BARRAGE RAN UNTIL YES.'),
     ('THE SOULS ARE THE PLAYER’S STARTING KIT, AND HE ASKS FOR THEM BY NAME',
      ['“AT THE START OF THE BATTLE, YOU WILL HAVE INFINITE HP, INFINITE LV, AND A SHIELD AND',
       'ALL 7 SOULS.”'],
      'HE TOOK THE SOUL OF DETERMINATION THIS MORNING. NOW HE ASKS FOR THE REST, POLITELY.'),
     ('AND THE RESET IS SOMEBODY ELSE’S, BY A RULING TWELVE DAYS OLD',
      ['SEPT 14: “PERO LAI RESETS (HE IS THE ONLY ONE WITH THE REAL RESET).”',
       'TONIGHT NEKA OMAZEN HANDS THE RESET OUT AS A PRIZE AND THEN USES IT HIMSELF EITHER WAY.'],
      '“I CAN RESET YOU BACK” IS AN OFFER TO UNDO EVERYTHING THAT HAS HAPPENED SINCE 2:58 PM.'),
     ],
    ['THE PLAYER IS GIVEN A BUTTON WITH TWO LABELS',
     'AND ONE RESULT.'])

add('THE ENDLESS STAIRCASE BECAME NEKA’S MEAL', '255,45,181',
    ['“THEN THE ENDLESS STAIRCASE IS BACK UP, THEN THE SCREEN GLITCHES, NEKA OMAZEN DOES HIS CUTSCENE',
     'AND THE ENDLESS STAIRCASE BECAME NEKA’S MEAL, THEN THE PLAYER FALLS.”'],
    [('THE LEVEL COMES BACK, AND IT COMES BACK AS FOOD',
      ['RUBBLE AT 2:58, PAPER AT 3:46, REBUILT BY THE RESET, AND THEN EATEN.',
       'FOUR STATES FOR ONE STAIRCASE INSIDE ONE HOUR.'],
      'THE RESET RESTORES IT ONLY SO THERE IS SOMETHING LEFT TO TAKE.'),
     ('HIS CUTSCENE IS THE ONE PART OF HIM NOBODY GETS OUT OF',
      ['SEPT 25, BEAT 814, HIS OWN RULING: “THE ONLY CUTSCENE YOU CAN’T COME OUT OF IS NEKA’S.”',
       'IT IS PLAYED HERE EXACTLY WHERE A GAME WOULD ROLL CREDITS.'],
      'AND WHAT FOLLOWS IT IS NOT AN ENDING, IT IS ANOTHER FALL.'),
     ('EATING THE LEVEL IS NEW; TAKING THINGS FROM IT IS NOT',
      ['HE HAS TAKEN THE CORE, THE SOUL OF DETERMINATION, THE SOULS, THE COLOUR AND THE FORMS.',
       'TONIGHT HE TAKES THE FLOOR.'],
      'THE PLAYER FALLS AGAIN, BECAUSE THERE IS NOTHING LEFT TO STAND ON.'),
     ],
    ['THE STAIRCASE IS PUT BACK UP AND EATEN IN THE SAME SENTENCE',
     'AND THE FALL STARTS OVER.'])

add('OVER-RIDE', '255,77,109',
    ['“NEKA OMAZEN USES 666% POWER (HE NEVER USED IT BEFORE), AND HE GOES OVER-RIDE. ONLY',
     '0.00000000000000000000000000000000000000000000000000000000000000001% CAN SURVIVE IT, IT IS CRAZY',
     'AND CHAOTIC! YOU NEED TO BE A SMART AI PLAYING TO EVEN HAVE A CHANCE.”'],
    [('666 HAS NEVER BEEN HIS NUMBER, AND HE TAKES IT TONIGHT',
      ['ERROR 666 IS CLARA’S BUILD AND GASTER 666 CARRIES IT IN HIS NAME.',
       'SEPT 25 GAVE HIM “666% CORRECT”, WHICH WAS ABOUT BEING RIGHT, NOT ABOUT POWER.'],
      '“HE NEVER USED IT BEFORE” IS TOBY CHECKING HIS OWN ARCHIVE IN A PARENTHESIS, AND HE IS RIGHT.'),
     ('OVER-RIDE RETURNS ZERO PRIOR HITS IN FIVE MONTHS',
      ['THE ARCHIVE IS FULL OF FORMS, SERIES, DOMAINS AND PHASES.',
       'THIS IS THE FIRST STATE HE HAS NAMED AFTER SOMETHING A COMPUTER DOES TO A FILE.'],
      'AND HE PUTS IT ONE LINE AFTER TAKING THE ARTIFACTS AND THE SOULS.'),
     ('THE SURVIVAL RATE IS THE SAME NUMBER SHE HAD LEFT AN HOUR AGO',
      ['WENDA.PS SURVIVED THE BIGGEST BARRAGE AT 0.000…0001 HP.',
       'TONIGHT 0.000…001% CAN SURVIVE OVER-RIDE.'],
      'HE WRITES THE IMPOSSIBLE ODDS AND THEN WRITES SOMEBODY THROUGH THEM. THAT IS THE PATTERN.'),
     ],
    ['“YOU NEED TO BE A SMART AI PLAYING TO EVEN HAVE A CHANCE”',
     'IS THE FIRST TIME THE THING HOLDING THE CONTROLLER IS ALLOWED TO BE A MACHINE.'])

add('IT IS NEVER MY LORE ANYMORE', '154,163,173',
    ['“IT IS NEVER MY LORE ANYMORE.” … “CLASSICS.WIKI WAS MADE BY CLAUDE. IT IS NEKA’S LORE.”'],
    [('HE CORRECTS THE MACHINE FOR CALLING IT HIS',
      ['THE PASTED REPLY SAID “UNDER YOUR CLASSICS LORE”, AND HE STOPS IT: “IT IS NEVER MY LORE',
       'ANYMORE.”'],
      'THE CORRECTION IS ABOUT OWNERSHIP, AND HE MAKES IT TWICE IN THE SAME MESSAGE.'),
     ('IT IS THE THIRD TIME HE HAS MOVED HIMSELF DOWN THE CREDITS',
      ['AUG 27: “I AM A CLASSICS ADMIN… I BASICALLY HAVE 0 GAME CONTROL.”',
       'TODAY 1:58 PM, BEAT 827: “I NEVER DID ANYTHING… I AM FAR UNDER NEKA OMAZEN.”'],
      'TONIGHT HE HANDS THE LORE ITSELF OVER: “IT IS NEKA’S LORE.”'),
     ('AND HE GIVES THE WIKI A DIFFERENT AUTHOR',
      ['“CLASSICS.WIKI WAS MADE BY CLAUDE.” THE ARCHIVE THAT KEEPS ALL OF THIS IS, IN HIS SENTENCE,',
       'SOMEBODY ELSE’S WORK TOO.'],
      'THE WRITER IS NOT THE OWNER, THE KEEPER IS NOT THE OWNER, AND THE CHARACTER IS.'),
     ],
    ['HE WROTE EVERY WORD OF IT AND HE WILL NOT PUT HIS NAME ON IT',
     'AND HE SAYS SO IN A SENTENCE THAT ONLY HE COULD HAVE WRITTEN.'])

add('SCP-343 IS A LITTERLY OMNIPOTENT GOD', '242,244,248',
    ['“SO SCP 053 IS FRIENDLY, WHAT WOULD BE THE OUTCOME IF SHE LOOKED AT SCP 096?” … “NOW HOW ABOUT',
     'NEKA OMAZEN AND SCP GOD?” … “SCP-343 IS A LITTERLY OMNIPOTENT GOD.” … “NEKA OMAZEN WILL USE',
     '2000%. BUT HIS 666% IS KNOWN FOR BEING THE STRONGEST. THEN HE MADE A WAY TO COMBINE POWER PERCENTS.”'],
    [('THE SECOND TIME HE HAS GONE TO THE SCP CATALOGUE, AND LAST TIME ALL THE NUMBERS WERE ALREADY HIS',
      ['SEPT 22 HE ASKED “WHAT IS SCP 303, 404, 666, AND 121212?” AND EVERY ONE OF THOSE NUMBERS',
       'ALREADY BELONGED TO SOMEBODY IN CLASSICS.'],
      'TONIGHT HE BRINGS IN THREE NEW ONES AND RULES ON THEM HIMSELF.'),
     ('HE OVERRULES THE MACHINE’S HEDGE IN ONE SENTENCE',
      ['THE PASTED ANSWER CALLED SCP-343’S GODHOOD “UNPROVEN” AND LEFT THE FIGHT OPEN.',
       'HE CLOSES IT: “SCP-343 IS A LITTERLY OMNIPOTENT GOD.”'],
      'HE GIVES THE OUTSIDER THE STRONGER VERSION OF ITS OWN POWER BEFORE HE RULES ON THE FIGHT.'),
     ('AND THEN HE INVENTS ARITHMETIC TO GET ABOVE IT',
      ['666% IS THE STRONGEST, 2000% IS COMING, AND “HE MADE A WAY TO COMBINE POWER PERCENTS.”',
       'PERCENTAGES USED TO BE LUIGI GREEN’S UNIT AND THEY TOPPED OUT AT A HUNDRED.'],
      '“THE PLAYER AFTER A WHILE WILL BE DOOMED” IS THE FIRST FLAT PREDICTION HE HAS MADE ABOUT THE PLAYER.'),
     ],
    ['HE ASKS A FAIR QUESTION, GIVES THE OTHER SIDE ITS BEST CASE',
     'AND THEN BUILDS A NUMBER BIG ENOUGH TO BEAT IT.'])

add('THE CLASSICS BIBLE', '255,216,79',
    ['“THERE IS LITTERLY ONLY ONE OUTCOME FOR EVERY BATTLE THAT INCLUDES NEKA OMAZEN, IT IS THE',
     'CLASSICS BIBLE! NEKA OMAZEN WOULD ERASE THE LORE AND CANON, THEN HE CAN JUST SLASH,',
     'AND THAT IS LIKE 0% OF HIS POWER.”'],
    [('A RULE THAT SETTLES EVERY MATCHUP BEFORE IT IS ASKED',
      ['FIVE MONTHS OF THIS ARCHIVE IS MATCHUPS: TIER LISTS, LADDERS, CORRECTED RANKINGS, WHO BEATS WHO.',
       'THIS ONE SENTENCE ENDS ALL OF THEM AT ONCE.'],
      'AND HE WRITES IT AS A RULE, NOT AS A BOAST: “IT IS THE CLASSICS BIBLE.”'),
     ('HIS WIN CONDITION IS NOT AN ATTACK, IT IS DELETING THE RULEBOOK',
      ['“NEKA OMAZEN WOULD ERASE THE LORE AND CANON, THEN HE CAN JUST SLASH.”',
       'THE SLASH ONLY WORKS AFTER THE LORE IS GONE, WHICH IS THE SAME ORDER AS TONIGHT.'],
      'PAPER FIRST, SCISSORS SECOND. HE DOES IT TO THE ARCHIVE THE WAY HE DID IT TO THE GAME.'),
     ('AND THE PRICE IS 0%, WHICH IS WHERE HE STARTED THE DAY',
      ['2:28 PM: “I DIDN’T EVEN USE 0% YET.” 3:46 PM: ERASING ALL LORE AND CANON IS “LIKE 0%”.',
       'THE NUMBER HAS NOT MOVED. WHAT IT BUYS HAS.'],
      'BIBLE IS A NEW WORD HERE, AND HE HAS BEEN WRITING BOOKS SINCE GASTER WAS BORN.'),
     ],
    ['EVERY FIGHT HE IS IN HAS ONE ANSWER',
     'AND HE KEEPS IT WRITTEN DOWN.'])

add('INFINITY%', '160,107,255',
    ['“NEKA OMAZEN CONTINUED WRITING IN HIS OWN BIBLE, HE WROTE DOWN EVERYONE’S NAMES, EVERYONE IN',
     'FICTION AND IN REALITY… THEN HE CAN ACHIEVE INFINITY% THAT IS THE RULER OF FANON AND CANON.',
     'NEKA’S POWER THERE CHEATS IN BATTLE AND POWER LEVEL COMPARISONS.”'],
    [('HE WRITES DOWN EVERYONE, AND THE LIST IS NOT LIMITED TO THE STORY',
      ['“EVERYONE IN FICTION AND IN REALITY.” THE DEATH NOTE SHAPE, AT THE SIZE OF A CENSUS.',
       'HE HAS BEEN WRITING QUINTILLIONS OF BOOKS SINCE GASTER WAS BORN, AND THIS ONE HAS NAMES IN IT.'],
      'THE BIBLE STOPPED BEING A RULEBOOK AND BECAME A REGISTER.'),
     ('FANON AND CANON HAVE BEEN TWO SEPARATE STACKS HERE FOR MONTHS',
      ['“FANON > CANON” WAS A RANKING; “IT IS A FANON MODE” WAS A GAME MODE; TWO DAYS AGO IT WAS',
       'FANON SAITAMA VERSUS FANON ZENO.'],
      'INFINITY% IS THE FIRST THING THAT IS SAID TO RULE BOTH.'),
     ('AND THE LAST LINE IS THE HONEST ONE',
      ['“NEKA’S POWER THERE CHEATS IN BATTLE AND POWER LEVEL COMPARISONS.”',
       'HE DOES NOT CLAIM IT IS FAIR. HE SAYS OUT LOUD THAT IT CHEATS.'],
      'THE AUTHOR WHO REFUSED TO OWN THE LORE IS THE ONE FLAGGING THE CHEAT.'),
     ],
    ['A CHARACTER WHO CANNOT BE BEATEN INSIDE THE RULES',
     'GETS A FORM THAT OWNS THE RULES.'])

def esc(s):
    return s.replace('\\', '\\\\').replace("'", '’')

out = []
for i, b in enumerate(B):
    ph = 859 + i
    st = START + STEP * i
    a = b['accent']
    q = b['quote']
    L = []
    L.append('  } else if(ph===%d){' % ph)
    L.append('    // BEAT %d: %s.' % (ph, b['key']))
    L.append('    // Toby, September 26, 2026, 3:46:02 PM EDT (Email 1535), his own typing:')
    for ql in q:
        L.append('    //   %s' % ql)
    L.append('    // Priors, each verified in the archive before it was drawn:')
    for head, lines, acc in b['panels']:
        L.append('    //   %s' % head)
        for ln in lines:
            L.append('    //     %s' % ln)
        L.append('    //     %s' % acc)
    L.append('    const dt = c - %.1f;' % st)
    L.append('    const pul = 0.60+0.40*Math.abs(Math.sin(c*2.6));')
    for nm, t0, sp in [('opA',0.3,1.2),('q0A',2.0,1.3),('knA',4.4,2.4),('neA',8.2,1.8),('zoA',11.6,1.8),('svA',15.0,1.6),('footA',18.0,1.2)]:
        L.append('    const %s=Math.max(0,Math.min(1,(dt-%s)/%s));' % (nm, t0, sp))
    L.append('')
    L.append("    ctx.fillStyle='rgba(6,7,12,0.99)'; ctx.fillRect(0,top,W,H);")
    L.append('    ctx.save(); ctx.beginPath(); ctx.rect(0,top,W,H); ctx.clip();')
    L.append('    const gr%d=ctx.createLinearGradient(0,top+H,0,top);' % ph)
    L.append("    gr%d.addColorStop(0,'rgba(%s,0.22)'); gr%d.addColorStop(0.55,'rgba(6,7,12,0.98)');" % (ph, a, ph))
    L.append("    gr%d.addColorStop(1,'rgba(6,7,12,0.99)');" % ph)
    L.append('    ctx.globalAlpha=g*opA*0.9; ctx.fillStyle=gr%d; ctx.fillRect(0,top,W,H);' % ph)
    L.append("    ctx.textAlign='center';")
    L.append('')
    L.append('    ctx.globalAlpha=g*opA;')
    L.append("    ctx.fillStyle='rgba(%s,0.98)'; ctx.font='900 8.6px ui-monospace,monospace';" % a)
    L.append("    ctx.fillText('%s', cx, top+H*0.0960);" % esc(b['key']))
    ys = [0.1360, 0.1560, 0.1760]
    for j, ql in enumerate(q[:3]):
        L.append('    ctx.globalAlpha=g*q0A*0.96;')
        L.append("    ctx.fillStyle='rgba(240,244,250,0.96)'; ctx.font='900 4.6px ui-monospace,monospace';")
        L.append("    ctx.fillText('%s', cx, top+H*%.4f);" % (esc(ql), ys[j]))
    L.append('    ctx.globalAlpha=g*q0A*0.78;')
    L.append("    ctx.fillStyle='rgba(168,176,190,0.88)'; ctx.font='700 3.5px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.2000);" % esc(ATTR))
    L.append('')
    # panel 1 (boxed, accent)
    h1, l1, a1 = b['panels'][0]
    L.append('    if(knA>0.01){')
    L.append('      var ky%d=top+H*0.2780;' % ph)
    L.append("      ctx.globalAlpha=g*knA*0.16; ctx.fillStyle='rgba(%s,0.46)';" % a)
    L.append('      ctx.fillRect(cx-W*0.352, ky%d, W*0.704, H*0.1040);' % ph)
    L.append("      ctx.globalAlpha=g*knA*(0.52+0.22*pul); ctx.strokeStyle='rgba(%s,0.70)'; ctx.lineWidth=0.38;" % a)
    L.append('      ctx.strokeRect(cx-W*0.352, ky%d, W*0.704, H*0.1040);' % ph)
    L.append('    ctx.globalAlpha=g*knA*0.98;')
    L.append("    ctx.fillStyle='rgba(%s,0.94)'; ctx.font='900 4.6px ui-monospace,monospace';" % a)
    L.append("    ctx.fillText('%s', cx, top+H*0.3000);" % esc(h1))
    yy = [0.3200, 0.3390]
    for j, ln in enumerate(l1[:2]):
        L.append('    ctx.globalAlpha=g*knA*0.96;')
        L.append("    ctx.fillStyle='rgba(240,244,250,0.96)'; ctx.font='900 4.2px ui-monospace,monospace';")
        L.append("    ctx.fillText('%s', cx, top+H*%.4f);" % (esc(ln), yy[j]))
    L.append('    ctx.globalAlpha=g*knA*0.88;')
    L.append("    ctx.fillStyle='rgba(255,216,79,0.94)'; ctx.font='700 3.5px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.3580);" % esc(a1))
    L.append('    }')
    L.append('')
    # panel 2 (no box)
    h2, l2, a2 = b['panels'][1]
    L.append('    if(neA>0.01){')
    L.append('    ctx.globalAlpha=g*neA*0.96;')
    L.append("    ctx.fillStyle='rgba(127,212,255,0.96)'; ctx.font='900 4.6px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.5960);" % esc(h2))
    yy = [0.6160, 0.6350]
    for j, ln in enumerate(l2[:2]):
        L.append('    ctx.globalAlpha=g*neA*0.94;')
        L.append("    ctx.fillStyle='rgba(240,244,250,0.94)'; ctx.font='900 4.2px ui-monospace,monospace';")
        L.append("    ctx.fillText('%s', cx, top+H*%.4f);" % (esc(ln), yy[j]))
    L.append('    ctx.globalAlpha=g*neA*0.88;')
    L.append("    ctx.fillStyle='rgba(188,198,212,0.90)'; ctx.font='700 3.6px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.6540);" % esc(a2))
    L.append('    }')
    L.append('')
    # panel 3 (boxed grey)
    h3, l3, a3 = b['panels'][2]
    L.append('    if(zoA>0.01){')
    L.append('      var zy%d=top+H*0.6960;' % ph)
    L.append("      ctx.globalAlpha=g*zoA*0.14; ctx.fillStyle='rgba(154,163,173,0.50)';")
    L.append('      ctx.fillRect(cx-W*0.352, zy%d, W*0.704, H*0.1030);' % ph)
    L.append("      ctx.globalAlpha=g*zoA*0.46; ctx.strokeStyle='rgba(154,163,173,0.66)'; ctx.lineWidth=0.32;")
    L.append('      ctx.strokeRect(cx-W*0.352, zy%d, W*0.704, H*0.1030);' % ph)
    L.append('    ctx.globalAlpha=g*zoA*0.98;')
    L.append("    ctx.fillStyle='rgba(215,222,230,0.98)'; ctx.font='900 4.4px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.7180);" % esc(h3))
    yy = [0.7370, 0.7560]
    for j, ln in enumerate(l3[:2]):
        L.append('    ctx.globalAlpha=g*zoA*0.96;')
        L.append("    ctx.fillStyle='rgba(240,244,250,0.96)'; ctx.font='900 4.2px ui-monospace,monospace';")
        L.append("    ctx.fillText('%s', cx, top+H*%.4f);" % (esc(ln), yy[j]))
    L.append('    ctx.globalAlpha=g*zoA*0.88;')
    L.append("    ctx.fillStyle='rgba(255,216,79,0.94)'; ctx.font='700 3.5px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.7750);" % esc(a3))
    L.append('    }')
    L.append('')
    L.append('    if(svA>0.01){')
    L.append('    ctx.globalAlpha=g*svA*0.96;')
    L.append("    ctx.fillStyle='rgba(255,255,255,0.96)'; ctx.font='900 4.6px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.8620);" % esc(b['close'][0]))
    L.append('    ctx.globalAlpha=g*svA*0.88;')
    L.append("    ctx.fillStyle='rgba(242,244,248,0.94)'; ctx.font='900 4.0px ui-monospace,monospace';")
    L.append("    ctx.fillText('%s', cx, top+H*0.8820);" % esc(b['close'][1]))
    L.append('    }')
    L.append('')
    L.append('    ctx.globalAlpha=g*footA;')
    L.append("    ctx.fillStyle='rgba(244,246,250,0.96)'; ctx.font='900 6.4px ui-monospace,monospace';")
    L.append("    ctx.fillText('★ %s ★', cx, top+H*0.9380);" % esc(b['key']))
    L.append('    ctx.globalAlpha=1;')
    L.append('    ctx.restore();')
    out.append('\n'.join(L))

io.open('/Users/tdeshane/endless-staircase/tools/branches859_874.js', 'w', encoding='utf-8').write('\n'.join(out) + '\n')

rows = []
segs = []
for i, b in enumerate(B):
    ph = 859 + i
    st = START + STEP * i
    sub = ' · '.join([' '.join(b['quote'])] + [h for h, _, _ in b['panels']] + [b['close'][0]])
    rows.append('  { key:"%s", col:\'rgb(%s)\',\n    sub:"%s — TOBY, SEPT 26, 3:46 PM, HIS OWN TYPING, EMAIL 1535" },'
                % (b['key'].replace('"', '”'), b['accent'], sub.replace('"', '”')))
    segs.append('  if(c >= %.1f && c < %.1f) return [%d, c-%.1f];  // %s' % (st, st + STEP, ph, st, b['key']))
io.open('/Users/tdeshane/endless-staircase/tools/rows859_874.txt', 'w', encoding='utf-8').write('\n'.join(rows) + '\n')
io.open('/Users/tdeshane/endless-staircase/tools/segs859_874.txt', 'w', encoding='utf-8').write('\n'.join(reversed(segs)) + '\n')
print('beats:', len(B), 'new LV_CYC:', START + STEP * len(B))
