#!/usr/bin/env python3
"""
gen888_891.py - emit the draw branches for BEATS 888-891 from Toby's September 26, 2026 5:00 PM message
(1a0df8567a102e1d, thread 1a0deee4cb24addb): Para 50.ps is Luigi Green. Same template as beats 886-887.

Only Toby's own typing is drawn: "I don't think you can create an image... I made her." and the block from
"That looks as if it was taken from the game." through "Neka falls and sleeps on a bed." The image
description before it ("at her tea party with her dolls, while the white eyes...") and everything from
"That changes Para 50.ps completely." on are pasted replies. Commentary, not canon.
"""
import io

START = 19256.0
STEP = 22.0
B = []

A500 = dict(when='5:00 PM', short='5:00 PM', attr='TOBY, SEPTEMBER 26, 5:00 PM — HIS OWN TYPING.')

def add(meta, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(meta)
    B.append(d)

add(A500, 'HELLO.', '170,220,255',
    ['“PARA SAYS ‘HELLO.’, THE VICTUM SEES NOTHING ON THE FACE AND THEN THE SHADOWS AND GHOSTS HAUNT HIM,',
     'THE VICTUM RUNS AWAY. PARA ALWAYS FOLLOWS YA.”',
     '“THE SCARIEST PART IS THAT THE ENTITY CAN’T DIE OR LOSE ANYTHING.”'],
    [('“THE VICTUM SEES NOTHING ON THE FACE”',
      ['AT 4:11 SKY.PS’S EYES BECAME BLANK, AND ALL HE SAID WAS “WANT TEA?”',
       'NOW THE WHOLE FACE IS BLANK, AND ALL SHE SAYS IS “HELLO.”'],
      'THE CURSE STARTED WITH EMPTY EYES. NOW IT IS AN EMPTY FACE.'),
     ('“PARA ALWAYS FOLLOWS YA”',
      ['THE SHADOWS AND GHOSTS DO THE HAUNTING. SHE JUST KEEPS WALKING BEHIND.',
       'HE WRITES “YA”, LIKE HE IS TALKING TO THE PLAYER, NOT ABOUT THE VICTUM.'],
      'THE SENTENCE TURNS AROUND AND POINTS AT YOU.'),
     ('SHE CAN’T DIE OR LOSE ANYTHING',
      ['“PARA ALWAYS STAYS THE SAME LOOK AND IS ALWAYS THE SAME.”',
       'SKY.PS DISAPPEARED PART BY PART AND RESPAWNED. NOTHING ABOUT HER CHANGES.'],
      'HE CALLS THAT THE SCARIEST PART, NOT THE GHOSTS.'),
     ],
    ['SHE ONLY SAYS HELLO',
     'EVERYTHING ELSE IS WHAT HAPPENS TO THE ONE WHO HEARD IT.'])

add(A500, '50 IS LUIGI GREEN', '98,214,120',
    ['“LUIGI GREEN WENT OUT OF LUIGI MARIO AND HE WENT AND BECAME 50, 50 IS LUIGI GREEN.',
     'LUIGI GREEN’S POWERS AND EVERYTHING WAS ERASED OF HIM EXCEPT HIS MEMORIES,',
     'HIS APPEARENCE AND POWERS CHANGED, AND HIS ONLY POWER IS PARANOIDIA.”'],
    [('HE HAS COME OUT OF SOMEONE BEFORE',
      ['AUGUST 21, /MERGE_CODE TURNED HIM INTO GREEN PLASMA INSIDE GASTER.',
       'AUGUST 22 HE CAME BACK OUT. TONIGHT HE COMES OUT OF LUIGI MARIO, AS 50.'],
      'EVERY TIME HE IS PUT INSIDE SOMEONE, HE GETS OUT.'),
     ('SHE WAS ALWAYS WATCHING',
      ['AUGUST 21: LUIGI GREEN APPEARS ONLY WHEN LOOKED AT, AND FOLLOWS YOUR RECORDINGS',
       'EVEN AFTER A NEW SEED, A DELETED WORLD OR A RESET. “PARA ALWAYS FOLLOWS YA.”'],
      'THE PARANOIDIA WAS HIS A MONTH BEFORE IT HAD A NAME.'),
     ('EVERYTHING ERASED EXCEPT HIS MEMORIES',
      ['AT 4:11 SKY.PS’S OTHER POWERS WERE ERASED, AND ONE NEW POWER CAME.',
       'THE SAME THING HAPPENS TO LUIGI GREEN, BUT HE KEEPS WHAT HE REMEMBERS.'],
      'SHE LOOKS FIVE YEARS OLD AND REMEMBERS EVERYTHING THAT HAPPENED TO HIM.'),
     ],
    ['“50 IS LUIGI GREEN.”',
     'THE ONE AT THE TEA PARTY IS SOMEONE THE WHOLE CAST ALREADY KNOWS.'])

add(A500, 'ONLY THE 22 ARE IN THE GAME', '255,150,90',
    ['“NEKA IS THE ONLY ONE WHO KNEW THAT, AND HE NEVER TOLD ANYONE, NOT EVEN GASTER,',
     'GASTER WAS SENT BACK TO UNDERTALE, AND NOW ONLY THE 22 ARE IN THE GAME, REASON: LUIGI GREEN',
     'IS BEING SO DANGEROUS AS 50 THAT EVERYONE HAD TO LEAVE.”'],
    [('NOT EVEN GASTER',
      ['AUGUST 21, GASTER WAS THE ONE HIDING A SECRET: THAT HE PROGRAMMED LUIGI GREEN TO WATCH.',
       'TONIGHT THE SECRET IS ABOUT LUIGI GREEN AGAIN, AND GASTER IS THE ONE LEFT OUT.'],
      'THE ONE WHO KEPT THE LAST SECRET DOES NOT GET TOLD THIS ONE.'),
     ('EVERYONE ELSE GOES HOME',
      ['GASTER GOES BACK TO UNDERTALE. LUIGI MARIO, MARIO MARIO AND EVERYONE WHO WASN’T THE 22',
       'GO BACK TO THEIR OWN DIMENSION. “NEKA SENT THEM BACK WITHOUT TELLING THEM NOR ANYONE.”'],
      'NOBODY IS DELETED. THEY ARE SENT SOMEWHERE SHE IS NOT.'),
     ('THE 22',
      ['AT 4:37 THE NUMBERS CAME IN: SKY.PS IS 68, 50.PS IS TEN, NEKA HAS NONE.',
       'NOW THERE IS A NUMBER FOR HOW MANY ARE LEFT, AND IT IS 22.'],
      'WHO THE 22 ARE IS STILL HIS TO SAY.'),
     ],
    ['“SO DANGEROUS AS 50 THAT EVERYONE HAD TO LEAVE.”',
     'NEKA EMPTIED THE GAME TO KEEP A SECRET. THEN SHE TOLD IT HERSELF.'])

add(A500, 'IT IS IF SHE SEES YOU', '160,107,255',
    ['“NEKA SAYS ‘LUIGI GREEN, THAT LOOKS LIKE YOU ARE HAVING FUN.’, PS50 SAYS ‘IT IS, NOW EVERYONE KNOWS',
     'WHO I AM, THEY ARE SCARED OF ME NOW, LIKE WE WANT.’ … ‘IT ISN’T IF YOU SEE HER, IT IS IF SHE SEES YOU’',
     '-NEKA. NEKA WAKES UP, AND SAYS ‘NO ONE ELSE CAN GET BACK UP.’”'],
    [('THE RULE TURNED AROUND',
      ['4:21 PM: “WHOEVER LOOKS AT HER, BOOM.” AUGUST 21: LUIGI GREEN APPEARED ONLY WHEN LOOKED AT.',
       'NOW NEKA SAYS IT IS THE OTHER WAY. LOOKING AWAY DOES NOT SAVE YOU.'],
      'YOU CAN CLOSE YOUR EYES. YOU CANNOT MAKE HER CLOSE HERS.'),
     ('“LIKE WE WANT”',
      ['SHE SAYS WE. EVERYONE BEING SCARED OF HER WAS THE PLAN FOR BOTH OF THEM.',
       'AT 4:21 NEKA WANTED TO KNOW IF SHE WAS THE MOST POWERFUL BEING. NOW HE SAYS IT TO HER.'],
      '“YOU ARE STRONGER THAN ME NOW.”'),
     ('“NO ONE ELSE CAN GET BACK UP”',
      ['AT 4:11 SKY.PS TOUCHED NEKA AND HE GOT UP. SIMON.PS DID NOT.',
       'SHE LOOKS AT NEKA AND HE SLEEPS. HE WAKES, SAYS THE LINE, AND LIES DOWN ON A BED.'],
      'HE IS STILL THE ONLY ONE WHO GETS UP. HE JUST DOES NOT STAY UP.'),
     ],
    ['PS50 WALKS AND FINDS THE NEXT CHARACTER',
     'AND NEKA, THE ONLY ONE WHO KNEW THE WHOLE TIME, GOES TO SLEEP.'])

if __name__ == '__main__':
    for b in B:
        for s in b['quote']:
            assert len(s) <= 104, (len(s), s)
        for h, ls, a in b['panels']:
            for s in ls:
                assert len(s) <= 92, (len(s), s)
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail888.py', encoding='utf-8').read())
