#!/usr/bin/env python3
"""
gen894_897.py - emit the draw branches for BEATS 894-897 from Toby's September 26, 2026 messages
6:33 PM (1a0dfda0baea15c2) and 6:35 PM (1a0dfdbbab8be051), thread 1a0deee4cb24addb.
Same template as beats 888-893.

Only Toby's own typing is drawn. Both messages are mostly a pasted chat: the Roblox myth lists,
"You're right", "Got it", "Yes", "I was wrong" paragraphs and the "which is scarier" verdicts are the
machine's voice. Commentary, not canon. His own lines: "PS-50 is also made of corrupted code..." ,
"PS-50 is so strong it's sight would be able to kill a Goomba..." , "Answer: Neka is still tired..." ,
and "Neka is an assassin, he can slay anyone but PS-50. PS-50 gives you paranoid."
"""
import io

START = 19388.0
STEP = 22.0
B = []

A633 = dict(when='6:33 PM', short='6:33 PM', attr='TOBY, SEPTEMBER 26, 6:33 PM — HIS OWN TYPING.')
A635 = dict(when='6:35 PM', short='6:35 PM', attr='TOBY, SEPTEMBER 26, 6:35 PM — HIS OWN TYPING.')

def add(meta, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(meta)
    B.append(d)

add(A633, 'IMPOSSIBLE CODE', '255,45,181',
    ['“PS-50 IS ALSO MADE OF CORRUPTED CODE FROM SKY.PS, THE TEA, AND NEKA. AND LUIGI GREEN BECAME THE CODE.',
     'PS-50 IS UNKILLABLE BECAUSE SHE IS IMPOSSIBLE CODE, SHE HAS A CODE LAYER THAT SHE CAN EDIT,',
     'MAKING HER LITTERLY INVICIBLE. NEKA CAN’T PUT EVEN A DENT IN THAT.”'],
    [('THREE THINGS, CORRUPTED',
      ['SKY.PS, THE TEA, AND NEKA. THE TEA CAME IN AT 4:11 PM; SHE ASKED FOR A TEA PARTY AT 4:21.',
       'NOW THE TEA IS NOT SOMETHING SHE SERVES. IT IS PART OF WHAT SHE IS MADE OF.'],
      'THE TEA PARTY WAS NEVER JUST A TEA PARTY.'),
     ('LUIGI GREEN BECAME THE CODE',
      ['5:00 PM: 50.PS IS LUIGI GREEN. 5:37 PM: SHE HAS ALL HIS MEMORIES.',
       'NOW: HE DID NOT JUST GO INTO HER. HE BECAME THE CODE ITSELF.'],
      'THERE IS NO LUIGI GREEN LEFT OUTSIDE OF HER.'),
     ('A LAYER SHE CAN EDIT',
      ['ANYTHING THAT HITS HER, SHE CAN WRITE BACK OUT OF HER OWN CODE.',
       'THAT IS WHY SHE CANNOT BE KILLED. EVEN NEKA CANNOT DENT IT.'],
      'YOU CANNOT BREAK SOMETHING THAT REWRITES ITSELF.'),
     ],
    ['IMPOSSIBLE CODE',
     'SHE IS NOT HARD TO KILL. SHE IS IMPOSSIBLE TO KILL.'])

add(A633, 'NORMAL IN THE GAME', '255,64,64',
    ['“PS-50 IS SO STRONG IT’S SIGHT WOULD BE ABLE TO KILL A GOOMBA. PS-50 LOOKS AT SKY.PS, SKY.PS SEES',
     'THE LONG MOUTH AND RED EYES, BUT IN THE GAME, PS-50 IS NORMAL, BECAUSE THOSE WITH PARANOIDIA,',
     'THEIR VISION IS INFECTED CAUSING THEM TO SEE SOMETHING AND IT CAUSES HALLICULTIONS AND BLINDNESS.”'],
    [('HER SIGHT VS. A GOOMBA',
      ['TOBY’S RULE: WHATEVER TOUCHES A GOOMBA DIES, UNLESS IT LANDS ON TOP OF ITS HEAD.',
       'SHE DOES NOT HAVE TO TOUCH ONE. SHE ONLY HAS TO LOOK AT IT.'],
      'THE GOOMBA NEVER GETS A CHANCE TO BE TOUCHED.'),
     ('THE LONG MOUTH AND RED EYES',
      ['SKY.PS SEES THEM. THE GAME DOES NOT. IN THE GAME SHE IS A NORMAL LITTLE GIRL.',
       'THE CORRUPTED FACE IS IN HIS INFECTED VISION: HALLUCINATIONS, THEN BLINDNESS.'],
      'THE SCARY FACE IS SOMETHING HIS OWN EYES ARE DOING.'),
     ('WHO IS TELLING THE TRUTH?',
      ['IF YOU HAVE PARANOIDIA, YOU SEE THE MONSTER. IF YOU DO NOT, YOU SEE A KID.',
       'SO THE ONE PERSON WHO SEES WHAT IS WRONG IS THE ONE NOBODY CAN BELIEVE.'],
      'EVERYONE ELSE THINKS SHE IS FINE.'),
     ],
    ['NORMAL IN THE GAME',
     'ONLY THE PARANOID SEE HER FACE CHANGE.'])

add(A633, 'EVERYTHING SHE DID FAILED', '127,212,255',
    ['“NEKA IS STILL TIRED, (IMPOSSIBLE WITH THE OTHER CHARACTERS), NEKA CAN’T SEE. NEKA IS SLEEPING AND HE',
     'IS THE 2ND MOST POWERFUL BY FAR. PS-50 TOUCHED NEKA, NEKA DIDN’T WAKE UP. PS-50 PUT HER DOLLS ON NEKA,',
     'NEKA DIDN’T WAKE UP, EVERYTHING PS-50 DID FAILED, LIKE ALWAYS!”'],
    [('THE NIGHT ROUND',
      ['NEKA MADE IT NIGHT. EVERYONE IS ASLEEP. PS-50 WALKS UNDER THEIR BEDS.',
       'SHE LOOKS AT EACH CHARACTER, BOOM. EVERY ONE OF THEM WAKES UP PARANOID.'],
      'EVERY ONE EXCEPT NEKA.'),
     ('WHY NEKA STAYS ASLEEP',
      ['5:13 PM: “SLEEPING FOREVER ON HIS BED.” NOW THE REASON: HE IS TIRED AND HE CAN’T SEE.',
       'HER POWER WORKS THROUGH SIGHT. HE HAS NONE LEFT FOR IT TO GET INTO.'],
      'THE ONE WHO CANNOT SEE HER IS THE ONE SHE CANNOT REACH.'),
     ('TOUCH, THEN DOLLS',
      ['SHE TOUCHED HIM. NOTHING. SHE PUT HER DOLLS ON HIM. NOTHING.',
       'HE IS THE 2ND MOST POWERFUL BY FAR, AND ASLEEP HE STILL OUTLASTS EVERYTHING SHE TRIES.'],
      '“LIKE ALWAYS.”'),
     ],
    ['EVERYTHING SHE DID FAILED',
     'SHE CAN WAKE EVERYONE IN THE HOUSE EXCEPT HIM.'])

add(A635, 'ANYONE BUT PS-50', '255,216,79',
    ['“NEKA IS AN ASSASSIN, HE CAN SLAY ANYONE BUT PS-50. PS-50 GIVES YOU PARANOID. WHICH IS SCARIER?”',
     '',
     ''],
    [('THE ASSASSIN',
      ['NEKA CAN SLAY ANYONE IN THE GAME.',
       'THE ONE EXCEPTION IS HER, BECAUSE SHE IS IMPOSSIBLE CODE.'],
      'ONE NAME IS MISSING FROM HIS LIST.'),
     ('TWO KINDS OF SCARY',
      ['NEKA ENDS IT. PS-50 MAKES YOU LIVE THROUGH IT:',
       'THE BLUR, THE BLACKOUT, AND THEN NOT TRUSTING WHAT YOU SEE.'],
      'ONE TAKES YOUR LIFE. THE OTHER TAKES YOUR EYES.'),
     ('AND RIGHT NOW',
      ['THE ASSASSIN IS ASLEEP ON HIS BED AND CAN’T SEE.',
       'THE ONE HE CANNOT SLAY IS AWAKE, WALKING UNDER THE BEDS.'],
      'TOBY LEFT THE QUESTION OPEN. SO DOES THE GAME.'),
     ],
    ['ANYONE BUT PS-50',
     'WHICH IS SCARIER?'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail894.py', encoding='utf-8').read())
