#!/usr/bin/env python3
"""
gen912_917.py - emit the draw branches for BEATS 912-917 from Toby's September 27, 2026 5:24 PM message
(1a0e4c19f2790085) and his 5:26 PM answer (1a0e4c2f4c59473d), thread 1a0deee4cb24addb. Same template as 908-911.

Only Toby's own typing is drawn: 5:24 PM "What character eats data?" through "Neka and PS-50 stand as the most
powerful beings." and 5:26 PM "Answer: Neka Omazen's favorite is data" through "he consumes the Pi and all this
stuff." The prose paragraphs below each ("Neka Omazen is the character acting like a data eater here...",
"You're right, I missed the literal answer...") are pasted chatbot text and are NOT canon. The attached
Add_all_the_colors_of_the_rain.mp4 was not viewable here and is not drawn.
"""
import io

START = 19784.0
STEP = 22.0
B = []

A524 = dict(when='5:24 PM', short='5:24 PM', attr='TOBY, SEPTEMBER 27, 5:24 PM — HIS OWN TYPING.')
A526 = dict(when='5:26 PM', short='5:26 PM', attr='TOBY, SEPTEMBER 27, 5:26 PM — HIS OWN TYPING.')

def add(meta, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(meta)
    B.append(d)

add(A524, 'WANT DATA?', '127,212,255',
    ['“WHAT CHARACTER EATS DATA? NEKA SAYS “WANT DATA?” LUIGI GREEN SAYS “I’LL TAKE PIE.”, NEKA SAYS “HERE IS PI”,',
     '“I READ YOUR SPEECH BUBBLE AND YOU SAID ‘PI’.” “WHAT YOU WANTED.” “I WANTED THE PIE.” “HERE IS A CHERRY PIE',
     'FOR YOU.” “IS CHERRY THE ONLY FLAVOR HERE?” “THIS IS A JAPANESE GAME, SO YES.” LUIGI GREEN LOOKS AT SAKURA.”'],
    [('I READ YOUR SPEECH BUBBLE',
      ['SEPT 24, 5:03 PM: NEKA IS THE ONLY CHARACTER IN CLASSICS WITH A SPEECH BUBBLE,',
       'AND HE TYPES THE INFINITE DIGITS OF PI ON IT. TODAY LUIGI GREEN READS IT.'],
      'PIE OUT LOUD. PI IN THE BUBBLE.'),
     ('CHERRY IS THE ONLY FLAVOR',
      ['AUG 31: “ALL OF CLASSICS COMES FROM THE CHERRY BLOSSOM SAKURA.”',
       'SEPT 24, 5:03 PM: NEKA COMBINED SAKURA AND CHAKRA INTO CHERRY CHOCOLATE.'],
      'SO OF COURSE THE PIE IS CHERRY.'),
     ('LUIGI GREEN LOOKS AT SAKURA',
      ['THIS MORNING SHE LOOKED AT THE BEDS. THIS AFTERNOON, THE TEDDY BEAR. BOTH MOVED.',
       'NOW SHE LOOKS AT THE SAKURA, WHERE ALL OF CLASSICS COMES FROM.'],
      'NOBODY SAYS WHAT HAPPENS NEXT.'),
     ],
    ['WANT DATA?',
     'SHE ASKED FOR PIE.'])

add(A524, 'THANKS FOR THE ERROR', '255,90,90',
    ['“NEKA SAYS “HERE IS ERRORS FOR YOU.”, LUIGI GREEN SAYS “DID YOU KNOW NEWTALE GASTER IS AN ERROR?”,',
     'NEKA SAYS “THANKS FOR THE ERROR.”, NEKA CLEANS NEWTALE GASTER. “WHY DID YOU DO THAT?” “ARE YOU AN ERROR?”',
     '“NO, I AM CODE.” “ALRIGHT, SO I AM CODE, YOU ARE CODE, WHERE WAS NEWTALE GASTER FROM?” “NEWTALE AU.”'],
    [('RUNNING FROM THE LOOSE TEXT',
      ['SEPT 24, 5:03 PM: NEWTALE GASTER RAN FROM NEKA’S PI TEXT UNTIL THE TEXT GLITCHED.',
       'NEKA SAID “YOU CAN’T ESCAPE ME, I AM ALWAYS HERE FOR YOU.”'],
      'THREE DAYS LATER, HE DID NOT ESCAPE.'),
     ('THANKS FOR THE ERROR',
      ['LUIGI GREEN THINKS SHE IS TELLING HIM A FACT. NEKA HEARS A GIFT.',
       'HE SAYS THANKS, AND NEWTALE GASTER IS CLEANED OUT OF THE GAME.'],
      'TO NEKA, AN ERROR IS SOMETHING TO CLEAN.'),
     ('NO, I AM CODE',
      ['SEPT 26, 7:04 AM: NEKA HAD THE NEWTALE CHARACTERS, “FROM NEWTALE BETTY TO NEWTALE GASTER.”',
       'TODAY THERE IS ONE QUESTION: ERROR OR CODE. LUIGI GREEN SAYS CODE.'],
      'THE RIGHT ANSWER KEEPS YOU IN THE GAME.'),
     ],
    ['THANKS FOR THE ERROR',
     'I AM CODE, YOU ARE CODE.'])

add(A524, 'YOU ONLY NEED ME!', '190,120,255',
    ['“NEKA LOCKED CLASSICS OMAZEN, MAKING NEWTALE ALIVE, NEWTALE OMAZEN IS HERE. LUIGI GREEN SEES NEWTALE OMAZEN,',
     'AND NEWTALE FALLS APART AND DISAPPEARS. NEKA SAYS “YOU BEATEN GASTER, YOU BEATEN EVERYONE,',
     'I AM YOUR FRIEND, YOUR ONLY FRIEND, YOU ONLY NEED ME!””'],
    [('NEWTALE OMAZEN',
      ['SEPT 26, 7:04 AM: NEKA WALKED ACROSS THE METAL FLOOR TO THE CLASSICS OMAZEN CORE.',
       'TODAY HE LOCKS IT, AND NEWTALE COMES ALIVE. ONE LOOK FROM LUIGI GREEN AND IT FALLS APART.'],
      'HER GAZE AGAIN. THIS TIME IT BREAKS THINGS.'),
     ('YOUR ONLY FRIEND',
      ['SEPT 2, 3:58 PM: PERO LAI, “YOU ONLY NEED ME, YOUR ONLY FRIEND.”',
       'THREE WEEKS LATER THE SAME WORDS COME FROM NEKA, SAID TO LUIGI GREEN.'],
      'THE SAME WORDS, A NEW SPEAKER.'),
     ('YOU BEATEN EVERYONE',
      ['AT 2:50 PM SHE SAID “I NEED YOU… ALL.” SHE WANTED EVERY CHARACTER.',
       'NEKA’S ANSWER: SHE HAS BEATEN THEM ALL. NOW SHE ONLY NEEDS HIM.'],
      'ALL, OR ONLY ONE.'),
     ],
    ['YOU ONLY NEED ME!',
     'SAID IN CAPITAL LETTERS.'])

add(A524, 'NEKA SHOWS HIS POWER', '255,120,60',
    ['“NEKA BREAKS TIME AND SPACE, AND SEPERATES THE 2 FORCES OF THE GAME. HE CUTS THE GAME WITH THE CLAWS,',
     'THE TAIL SLICES THE TITAINUIM QUADRANUIM LIKE PAPER, NEKA SHOWS HIS POWER, NEKA BATTLES THE SPRUNKIS',
     'AND WON, AND HE EVEN BEATEN ALL THE AVATARS AND HE EVEN BLOCKED THE GAME.”'],
    [('THE 2 FORCES OF THE GAME',
      ['AT 2:50 PM: “2 BEINGS ARE EQUAL.” TWO AND A HALF HOURS LATER,',
       'THE GAME ITSELF HAS 2 FORCES, AND NEKA PULLS THEM APART.'],
      'TWO, AGAIN.'),
     ('TITAINUIM LIKE PAPER',
      ['SEPT 24, 4:37 PM: THE FIVE-HEADED BEAST’S CLAWS SCRATCHED THE TITAINUIM FLOOR.',
       'SCRATCHED. TODAY NEKA’S TAIL SLICES TITAINUIM QUADRANUIM LIKE PAPER.'],
      'FROM A SCRATCH TO A CUT.'),
     ('THE SPRUNKIS AND THE AVATARS',
      ['THIS MORNING THE 20 SPRUNKIS WOKE UP AS SHADOWS. NEKA BATTLES THEM AND WINS.',
       'SEPT 26, 2:28 PM HE MADE SHADOW CLONES OF THE AVATARS. NOW HE BEATS THE AVATARS THEMSELVES.'],
      'THEN HE BLOCKS THE WHOLE GAME.'),
     ],
    ['NEKA SHOWS HIS POWER',
     'CLAWS, TAIL, AND THEN THE GAME ITSELF.'])

add(A524, 'CRARKRAR', '255,216,79',
    ['“CRARKRAR (SOUNDS LIKE CRACKER) WAS MADE, CRARKRAR IS THE NEW POWER TIER, NEKA MADE IT FOR HIMSELF,',
     'AND THE WAY TO GET IT IS TO BE NEKA, ONLY NEKA CAN GET IT. INFINITY SERIES DRAGON RIDE WAS MADE.',
     'NEKA AND PS-50 STAND AS THE MOST POWERFUL BEINGS.”'],
    [('THE WAY TO GET IT IS TO BE NEKA',
      ['A NEW POWER TIER WITH ONE RULE. NOT A FORM TO REACH OR AN ORB TO COLLECT.',
       'HE MADE IT FOR HIMSELF, SO NOBODY ELSE CAN EVEN TRY.'],
      'SOUNDS LIKE CRACKER.'),
     ('INFINITY SERIES DRAGON RIDE',
      ['SEPT 19, 3:27 PM: PERO LAI’S “25 SERIES: DRAGON RIDE,” FROM 3 WAY HEROES.',
       'TODAY THE NUMBER IS GONE. INFINITY SERIES.'],
      'NO NUMBER GOES HIGHER THAN THAT.'),
     ('THE MOST POWERFUL BEINGS',
      ['AT 2:50 PM: NEKA IS MORE POWERFUL BY EXTREME, AND PS-50 CAN MAKE HIM SLEEP.',
       'AFTER ALL OF THIS, THE TWO OF THEM STILL STAND AT THE TOP TOGETHER.'],
      'EVERYONE ELSE IS BELOW THEM.'),
     ],
    ['CRARKRAR',
     'ONLY NEKA CAN GET IT.'])

add(A526, 'THE ONLY ONE WHO CONSUMES DATA', '127,212,255',
    ['“ANSWER: NEKA OMAZEN’S FAVORITE IS DATA, IT CONSUMES DATA, AND IS THE ONLY ONE WHO CONSUMES DATA,',
     'HE CONSUMES THE FORMS BEFORE, HE CONSUMES THE PI AND ALL THIS STUFF.”'],
    [('HE ANSWERED HIS OWN QUESTION',
      ['5:24 PM: “WHAT CHARACTER EATS DATA?” 5:26 PM: THE ANSWER.',
       'NEKA OMAZEN. THE ONLY ONE. AND DATA IS HIS FAVORITE.'],
      'TWO MINUTES.'),
     ('HE CONSUMES THE PI',
      ['SEPT 24 HE TYPED THE INFINITE DIGITS OF PI. TODAY HE OFFERS PI TO LUIGI GREEN.',
       'PI IS DATA, AND DATA IS WHAT HE EATS. SHE TOOK THE CHERRY PIE INSTEAD.'],
      'HE WAS OFFERING HIS FAVORITE FOOD.'),
     ('THE ONLY ONE',
      ['SEPT 26, 7:04 AM: MR. BLACK IS “THE ABSORBTION AND CONSUMPTION OF COLOR.”',
       'COLOR HAS ITS EATER. DATA HAS ONLY ONE, AND IT IS NEKA.'],
      'AND EVERYONE IN THE GAME IS CODE.'),
     ],
    ['DATA IS HIS FAVORITE',
     'HE CONSUMES THE FORMS, THE PI, AND ALL THIS STUFF.'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail912.py', encoding='utf-8').read())
