#!/usr/bin/env python3
"""
gen963.py - emit the draw branches for BEATS 963-967 from Toby's October 1, 2026 messages,
thread 1a0deee4cb24addb. Same template as 933-962 (emit_tail933.py).

  4:44 PM  1a0f93615fed5bb4  -> 963 (The short-nosed mask), 964 (LIKE ALWAYS!)
  4:48 PM  1a0f9399beb0638f  -> 965 (You are mine)
  4:49 PM  1a0f93b22d4c587e  -> 966 (The Mega Star)
  4:58 PM  1a0f94341266ac42  -> NO BEAT ("Create PS-50 and the Mega Star", image ask)
  5:02 PM  1a0f9473cbe14c50  -> 967 (The Ultimate Mass)

Only Toby's typing is canon. The italic readings under each message ("PS-50 seems to be manipulating
Neka", "Neka is drawing PS-50 under his own influence", "cosmic horror") are the chatbot's, not drawn.
Priors: Pero LAI was the Plauge Doctor (reset-era.md, Sept 16); Sept 26 "everything PS-50 did failed,
LIKE ALWAYS!" (neka-omazen-era.md); Neka named Luigi Green "Luigi Inus"; Oren's "You are mine"
(the-trigger.md, July); Error Hall replaced the Judgement Hall (error-hall.md, July 26).
"""
import io

BASE = 963
TAG = '963'
START = 20906.0
STEP = 22.0
DATE_LONG = 'October 1'
DATE_SHORT = 'OCT 1'
B = []

def meta(t):
    return dict(when=t, short=t, attr='TOBY, OCTOBER 1, %s — HIS OWN TYPING.' % t)

def add(m, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(m)
    B.append(d)

A444 = meta('4:44 PM')
A448 = meta('4:48 PM')
A449 = meta('4:49 PM')
A502 = meta('5:02 PM')

add(A444, 'THE SHORT-NOSED MASK', '170,170,185',
    ['“NEKA OMAZEN WEARS A SHORT FACED PLAUGE DOCTOR MASK THAT FEELS AND LOOKS',
     'ROUGH, AND IT BLACK COLORED. HIS EYES CAN BE SEEN, AND HE HAS BLACK COLORED',
     'GLOVES ON. HE HANGS MANY OUTFITS UP, AND HE EVEN CLEANED HIS LABATORY.”'],
    [('A SHORT NOSE',
      ['A PLAUGE DOCTOR MASK, BUT THE NOSE PART IS SHORT.',
       'NORMALLY THAT STUFF HAS A LONG NOSE. ROUGH. BLACK.'],
      'SEPT 16: PERO LAI WAS THE PLAUGE DOCTOR. THE MASK CAME BACK.'),
     ('EYES AND GLOVES',
      ['HIS EYES CAN BE SEEN THROUGH IT.',
       'BLACK COLORED GLOVES ON BOTH HANDS.'],
      'NOT A FACELESS MASK. YOU CAN STILL SEE HIM LOOKING.'),
     ('MANY OUTFITS',
      ['HE HANGS MANY OUTFITS UP.',
       'AND HE EVEN CLEANED HIS LABATORY.'],
      'THE LAB COAT IS ONE OUTFIT ON THE RACK. THERE ARE MORE.'),
     ],
    ['A SHORT BLACK MASK. EYES SHOWING.',
     'A CLEAN LAB, FOR ONCE.'])

add(A444, 'LIKE ALWAYS!', '255,90,90',
    ['“EVERYTHING EVERYONE USES FAILS LIKE ALWAYS. NEKA OMAZEN SAYS “LIKE ALWAYS!”,',
     'PS-50 LOOKS AT NEKA OMAZEN, NEKA OMAZEN’S OUTFIT CHANGES TO HIS LAB SUIT.',
     'PS-50 SAYS “NEKA, DESTROY ALL THE OTHER CHARACTERS HERE.””'],
    [('LIKE ALWAYS!',
      ['EVERYTHING EVERYONE USES FAILS.',
       'AND THIS TIME NEKA SAYS IT HIMSELF: “LIKE ALWAYS!”'],
      'SEPT 26: “EVERYTHING PS-50 DID FAILED, LIKE ALWAYS!”'),
     ('THE LAB SUIT',
      ['PS-50 LOOKS AT HIM. HIS OUTFIT CHANGES TO HIS LAB SUIT.',
       'HIS EYES LOOK AT PS-50.'],
      'HER GAZE NEVER WORKED ON HIM BEFORE. NOW HIS CLOTHES CHANGE.'),
     ('ALL THE OTHER CHARACTERS',
      ['“NEKA, DESTROY ALL THE OTHER CHARACTERS HERE.”',
       'NEKA OMAZEN DESTROYED ALL THE OTHER CHARACTERS IN BATTLE.'],
      'SHE GIVES THE ORDER. HE DOES ALL THE FIGHTING.'),
     ],
    ['EVERYONE ELSE FAILS. NEKA DOES NOT.',
     'BUT WHO IS GIVING THE ORDERS?'])

add(A448, 'YOU ARE MINE', '200,120,255',
    ['“PS-50 IS HYPNOTISING NEKA OMAZEN. LUIGI TOUCHED NEKA OMAZEN, NEKA OMAZEN',
     'TURNS AND LOOKS AT PS-50, AND A MESSAGE APPEARS IN HER MIND. “YOU ARE PS-50,',
     'YOU ARE LUIGI INUS, YOU ARE LUIGI GREEN, YOU ARE MINE, YOU ARE SAFE HERE.””'],
    [('HYPNOTISING',
      ['ANSWER: PS-50 IS HYPNOTISING NEKA OMAZEN.',
       'THE LAB SUIT, THE ORDER, THE BATTLE. IT WAS HER.'],
      'TOBY ANSWERED HIS OWN QUESTION FOUR MINUTES LATER.'),
     ('IT TURNS AROUND',
      ['LUIGI TOUCHED NEKA. NEKA TURNS AND LOOKS AT PS-50.',
       'MORE AND MORE IMAGES OF NEKA FLYING, IN HER MIND.'],
      '“DO NOT BE AFRAID OF ME, NOR ANYONE, I AM WITH YOU.”'),
     ('THREE NAMES',
      ['“YOU ARE PS-50, YOU ARE LUIGI INUS, YOU ARE LUIGI GREEN.”',
       '“I KNOW YOU FAIL ALL THE TIME, I KNOW YOU.”'],
      'LUIGI INUS IS THE NAME NEKA GAVE LUIGI GREEN.'),
     ],
    ['“DO NOT RUN, DO NOT HIDE, YOU ARE FREE.”',
     '“YOU ARE MINE, YOU ARE SAFE HERE.”'])

add(A449, 'THE MEGA STAR', '255,210,90',
    ['“PS-50 SNAPS OUT OF IT, PS-50 STANDS IN NEKA’S CREATION.',
     'PS-50 LOOKS AROUND AND SEES THAT SHE IS JUST A TINY MASS',
     'IN THE HUGE CREATION OF THE MEGA STAR.”'],
    [('SNAPS OUT OF IT',
      ['THE MESSAGE ENDS. PS-50 SNAPS OUT OF IT.',
       'SHE IS NOT WHERE SHE WAS.'],
      'SHE TRIED TO HYPNOTISE HIM. HE SHOWED HER WHERE SHE IS.'),
     ('NEKA’S CREATION',
      ['PS-50 STANDS IN NEKA’S CREATION.',
       'IT IS HUGE. IT IS CALLED THE MEGA STAR.'],
      '“YOU ARE SAFE HERE.” HERE IS INSIDE SOMETHING HE MADE.'),
     ('A TINY MASS',
      ['PS-50 LOOKS AROUND.',
       'SHE IS JUST A TINY MASS INSIDE IT.'],
      'THE ONE WHO GIVES ORDERS IS A SPECK IN HIS STAR.'),
     ],
    ['A HUGE STAR. A TINY PS-50.',
     'AND THE MEGA STAR IS THE SMALL ONE.'])

add(A502, 'THE ULTIMATE MASS', '120,230,200',
    ['“THE MEGA STAR IS WAY SMALLER THAN PRESSURE, AND PRESSURE AND CLASSICS ARE',
     'INTO THE ULTIMATE MASS. NEKA MADE IT ALL. IT IS KNOWN AS THE GRAND JUDGEMENT',
     'HALL. NEKA OMAZEN IS EVEN LARGER THAN THE ULTIMATE MASS.”'],
    [('SMALLEST TO LARGEST',
      ['MEGA STAR < PRESSURE < THE ULTIMATE MASS < NEKA OMAZEN.',
       'PRESSURE AND CLASSICS ARE BOTH INSIDE THE ULTIMATE MASS.'],
      'AND NEKA OMAZEN CAN CONSUME IT ALL.'),
     ('THE GRAND JUDGEMENT HALL',
      ['IT CONTAINS THE JUDGEMENT HALL, THE ERROR HALL,',
       'AND ALL THE HALL VERSIONS.'],
      'JULY 26 THE ERROR HALL REPLACED THE JUDGEMENT HALL. NOW BOTH ARE ROOMS IN ONE.'),
     ('EVEN EVERYTHING',
      ['MILLIONS, TRILLIONS, QUADRILLIONS, QUAQUINGAGINTALLARDS,',
       'GOOGLEPLEXES, INFINITIES. ALL FICTION. THE BARRIER. THE REALITIES.'],
      'IT ALSO CONTAINS EVEN EVERYTHING.'),
     ],
    ['NEKA MADE IT ALL.',
     'NEKA OMAZEN IS LARGER THAN ALL OF IT.'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail933.py', encoding='utf-8').read())
