#!/usr/bin/env python3
"""
gen920_932.py - emit the draw branches for BEATS 920-932 from Toby's September 28, 2026 messages,
thread 1a0deee4cb24addb. Same template as 918-919 (emit_tail920.py, parameterized by BASE/TAG).

  6:34 AM  1a0e7953ce152572  -> 920-922  (the power ladder, Bacon to 0, set 50's defense to 0)
  4:22 PM  1a0e9aee2296cadb  -> 923-927  (not Pero LAI, Sleep!, Omega, Come on PS-50 LOSE!, give me your souls)
  4:51 PM  1a0e9c96e0185a4d  -> NO BEAT  (a bare "Create an image of Neka Omazen" ask plus chatbot text)
  5:18 PM  1a0e9e289dbe1c51  -> 928-930  (Newtale Gaster, "this is what being me is like", the game all stop)
  5:39 PM  1a0e9f5f087054df  -> 931-932  (0 breaths / I-Tross, the blood is from the characters he beaten)

Only Toby's own typing is drawn. The pasted chatbot prose (the image description "black clothing, blue eyes",
the stalemate analysis, "the one-foot height belonged to his fox form", the 12 breaths / 58 bpm guesses) is NOT
canon. Priors come from lore/docs/classics-lore/neka-omazen-era.md and the beat rows already in index.html.
"Deleted the games" / "the wiki falls apart" is in the story; nothing real is removed.
"""
import io

BASE = 920
TAG = '920_932'
START = 19960.0
STEP = 22.0
B = []

A634 = dict(when='6:34 AM', short='6:34 AM', attr='TOBY, SEPTEMBER 28, 6:34 AM — HIS OWN TYPING.')
A422 = dict(when='4:22 PM', short='4:22 PM', attr='TOBY, SEPTEMBER 28, 4:22 PM — HIS OWN TYPING.')
A518 = dict(when='5:18 PM', short='5:18 PM', attr='TOBY, SEPTEMBER 28, 5:18 PM — HIS OWN TYPING.')
A539 = dict(when='5:39 PM', short='5:39 PM',
            attr='TOBY, SEPTEMBER 28, 5:39 PM — NOT LORE, “WHAT HAPPENS IN THE GAME.”')

def add(meta, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(meta)
    B.append(d)

# ---------------- 6:34 AM ----------------
add(A634, 'NEKA INFINITY%', '255,120,60',
    ['“BABY NEKA WILL BE INFINITY POWER LEVEL, ADULT NEKA 0% POWER IS BEYOND FICTION,',
     'NEKA 10% IS TOTAL OVER-OVER-OVER (INFINITY OVERS) OVERLORD. NEKA 25% IS THE ONE BEYOND ALL.',
     'NEKA + JESUS IS TRUE GOD. ... AND HE HAS NEKA INFINITY%, WHICH IS ABSOLUTE OVERCHARGE”'],
    [('THE LADDER',
      ['BABY: INFINITY · 0%: BEYOND FICTION · 5%: BEY0ND FICT1ON+ · 10%: OVERLORD',
       '25%: THE ONE BEYOND ALL · NEKA + JESUS: TRUE GOD · 100%: CRARKRAR · INFINITY%'],
      'EIGHT RUNGS, AND THE BABY STARTS AT INFINITY.'),
     ('CRARKRAR',
      ['SEPT 27, 5:24 PM: CRARKRAR, THE TIER ONLY NEKA CAN GET.',
       'TODAY IT HAS A PLACE ON THE LADDER: NEKA 100%, “GOD-MODE PLUS LITTERLY EVERYTHING.”'],
      'AND THERE IS STILL ONE RUNG ABOVE IT.'),
     ('0% IS NOT ZERO',
      ['LAST NIGHT, 7:12 PM: NEKA WOULD PROBUBLY WIN AT 0% FOX.',
       'THIS MORNING ADULT NEKA AT 0% POWER IS ALREADY BEYOND FICTION.'],
      'THE BOTTOM OF HIS LADDER IS ABOVE EVERYONE ELSE’S TOP.'),
     ],
    ['PERO LAI IS BASICALLY NOW NEKA OMAZEN',
     'DUE TO CLASSICS CHANGES.'])

add(A634, 'BACON’S POWER LEVEL TELEPORTS TO 0', '255,190,90',
    ['“ADULT NEKA 5% IS BEY0ND FICT1ON+ (SCREEN GLITCHES AND BACON’S POWER LEVEL SHAKES AND FALLS DOWN)',
     '... BACON AND HIS POWER LEVEL FREEZE.',
     'NEKA TOUCHES BACON’S POWER LEVEL AND BACON’S POWER LEVEL TELEPORTS TO 0.”'],
    [('BEATING EVERYONE',
      ['SEPT 22: BACON HAIR WAS “BEATING EVERYONE IN EVERYONE’S POWER LEVEL VIDEOS.”',
       'THE ONE WHO WINS EVERY POWER LEVEL VIDEO IS THE ONE WHOSE NUMBER GOES TO 0.'],
      'HE NEVER GETS TO SWING.'),
     ('AT 5%',
      ['NEKA DOES NOT NEED INFINITY% TO SHAKE IT. AT 5% THE SCREEN GLITCHES',
       'AND BACON’S POWER LEVEL SHAKES AND FALLS DOWN ON ITS OWN.'],
      'AT INFINITY% IT FREEZES.'),
     ('ONE TOUCH',
      ['NO BLAST, NO BARRAGE. NEKA TOUCHES THE NUMBER ITSELF.',
       'FICTION AND REALITY BREAK, THE BARRIER BETWEEN THE 2 SHATTERS.'],
      'THE NUMBER TELEPORTS TO 0.'),
     ],
    ['NEKA INFINITY% BEATS EVERYONE',
     'ABSOLUTE OVERCHARGE.'])

add(A634, 'SET 50’S DEFENSE TO 0', '255,90,90',
    ['“DID YOU KNOW WHAT CHANGED IN NEKA? HE IS STRONGER,',
     'HE WILL USE INFINITY SERIES,',
     'AND WILL SET 50’S DEFENSE TO 0. NEKA WINS.”'],
    [('IMMUNE TO EACH OTHER',
      ['SEPT 27, 7:12 PM: “NEKA AND 50 ARE IMMUNE TO EACH OTHER.”',
       'HE COULD NOT PUT EVEN A DENT IN HER IMPOSSIBLE CODE.'],
      'SO HE STOPPED HITTING THE CODE.'),
     ('HE CAN CHANGE ANYONE’S CODE',
      ['“NEKA OMAZEN CAN CHANGE ANYONE’S CODE TOO, HE IS ALL POWERFUL,',
       'AND HE NOW BECAME HIS FULL HUMAN. HE NOW CAN REACH ANYONE.”'],
      'THE HUMAN FORM IS WHAT REACHES HER.'),
     ('DEFENSE: 0',
      ['HER DEFENSE IS A NUMBER, AND NEKA EDITS NUMBERS. HE SETS IT TO 0.',
       'THEN INFINITY SERIES. LAST NIGHT IT WAS “PROBUBLY.” THIS MORNING IT IS “NEKA WINS.”'],
      'THE MAYBE IS GONE.'),
     ],
    ['A BLACK-WEARING WHITE HUMAN-FOX,',
     'GARENTEED TO TURN INTO THE FULL HUMAN NOW.'])

# ---------------- 4:22 PM ----------------
add(A422, 'MY NAME IS NOT ‘PERO LAI’', '190,150,255',
    ['“NEKA OMAZEN CAME TO WENDA.PS, WENDA.PS SAYS “HELLO, PERO LAI, WHERE IS YOUR TAIL?”,',
     'NEKA SAYS “MY NAME IS NOT ‘PERO LAI’. 🤨”',
     'POWER LEVEL = BEYOND COMPARISON OR ???”'],
    [('NEVER SAY PERO LAI AGAIN',
      ['SEPT 24, 4:37 PM, TOBY BANNED THE NAME. SEPT 25: “NEKA OMAZEN IS NOT PERO LAI.”',
       'TODAY WENDA.PS SAYS IT TO HIS FACE, AND NEKA ANSWERS FOR HIMSELF.'],
      'SHE ALSO NOTICED THE TAIL IS GONE.'),
     ('MISSING POLOS',
      ['A RULE FOR THE CLASSICS POLOS: IF ONE GOES MISSING,',
       '“THE POLO IS ERASED AND REPLACED BY THE CHARACTER.”'],
      'THE EMPTY SQUARE GETS A PERSON IN IT.'),
     ('BEYOND COMPARISON',
      ['THIS MORNING THE LADDER WENT UP TO INFINITY%.',
       'THE HUMAN FORM IS NOT ON IT. ITS POWER LEVEL IS “BEYOND COMPARISON OR ???”'],
      'NOTHING TO COMPARE IT TO.'),
     ],
    ['NOW NEKA OMAZEN',
     'IS THE HUMAN FORM.'])

add(A422, 'SLEEP! 😸⚡', '120,200,255',
    ['“WENDA.PS WAS BEATEN, PS-50 GOTTEN THE WENDA.PS JEWEL. PS-50 BATTLES THE OMNIVERSE AND WON.',
     'PS-50 LOOKS AT NEKA, NEKA IS HUMAN FORM AND BECAME 6 FEET TALL.',
     'NEKA SAYS “SLEEP! 😸⚡”, EVERYONE SLEPT.”'],
    [('6 FEET TALL',
      ['SEPT 27: NEKA WAS ONE FOOT TALL. TODAY THE HUMAN FORM IS 6 FEET.',
       'PS-50 HAS JUST BEATEN THE WHOLE OMNIVERSE, AND SHE LOOKS UP AT HIM.'],
      'SHE HAS TO LOOK UP NOW.'),
     ('THE SLEEP COMMAND',
      ['SEPT 23: “EVERYONE! SIMON.PS! OREN.PS! SLEEP! 😸⚡”',
       'TODAY IT IS ONE WORD, THE SAME CAT FACE, AND EVERYONE SLEPT.'],
      'SAME COMMAND, SHORTER.'),
     ('FOX DRAGONS',
      ['“HE REACHED HUMAN AND NOW THE DRAGONS BECOME FOX DRAGONS.” HE EDITS EVERYONE’S CODE,',
       '“HE EDITS HIS OWN CODE, AND HE BLOCKED ANYONE FROM HIMSELF.”'],
      'THE FOX LEFT HIM AND WENT INTO THE DRAGONS.'),
     ],
    ['NEKA ACHIEVED HIS FULL GOD FORM.',
     'HE EVEN IS CODE HIMSELF.'])

add(A422, 'Ω', '230,230,240',
    ['“A BLACK SPHERE IN THE GAME’S SKY APPEARS. ... HE MADE HIS DOMAIN OF INFINITY SERIES,',
     'HYPERSPACES PULL EVERYTHING IN, NEKA SAYS “Ω”, AND THE OMEGA SYMBOL APPEARS,',
     'SIMON.PS’S OLD SYMBOL THING.”'],
    [('THE BLACK SPHERE',
      ['A BLACK SPHERE HANGS IN THE GAME’S SKY. INFINITY SERIES IS NOW A DOMAIN,',
       'AND THE HYPERSPACES PULL EVERYTHING IN.'],
      'NEKA IS MAKING DOOM TO EVERYONE.'),
     ('SIMON.PS’S OLD SYMBOL',
      ['NEKA SAYS ONE LETTER, “Ω,” AND THE OMEGA APPEARS.',
       'IT WAS SIMON.PS’S SYMBOL FIRST. NEKA USES IT NOW.'],
      'THE LAST LETTER.'),
     ('THE 2 PHOBIA MOUNTAINS COLLIDE',
      ['LIGHTNING STRIKES, THE GAME FLOOR FALLS APART, DEBRIS FLIES ALL OVER.',
       'NEKA PINS OREN.PS TO THE WALL WITH TELEKENTICS. BOOM. THEN HE BEATS EVERYONE ELSE.'],
      'THEN ONLY PS-50 IS LEFT.'),
     ],
    ['NEKA MADE LIGHTNING STRIKE.',
     'THE FLOOR IS GONE.'])

add(A422, 'COME ON... PS-50 LOSE!', '255,70,70',
    ['“NEKA MAKES ELECTRICITY FRAMES OF ALL THE LORE BEFORE, NEKA GOES BEYOND WHAT HE EVER DONE,',
     '... AND HE HAD SWEAT ALL OVER HIS FACE,',
     'AND HE SAYS “COME ON... PS-50 LOSE!””'],
    [('PS-50 GOES HER MAX',
      ['“NEKA GOES TOO FAR ON THE BATTLE, HE WANTS TO WIN EVERY BATTLE.”',
       'A WHOLE STORM. HIS LARGEST BARRAGES. SERIOUS MODE + GODMODE.'],
      'HE TOOK ALL ABILITIES FROM OTHER GAMES.'),
     ('ELECTRICITY FRAMES OF ALL THE LORE',
      ['EVERY STORY BEFORE THIS ONE, DRAWN IN LIGHTNING.',
       'HE SLAIN THE MEANING OF THE 2 REALITIES.'],
      'ALL OF IT, AT ONCE.'),
     ('SWEAT',
      ['NO ONE HAS MADE NEKA SWEAT BEFORE. PS-50 DOES.',
       'THE SHOCKWAVE KNOCKS THE WHOLE GAME OFF THE BATTLEFIELD.'],
      'HE HAS TO ASK HER TO LOSE.'),
     ],
    ['NEKA GOES BEYOND',
     'WHAT HE EVER DONE.'])

add(A422, 'EVERYONE, GIVE ME YOUR SOULS!', '200,60,255',
    ['“NEKA PICKS UP THE GAME AND CLAPS THE GAME WITH HIS 2 HANDS, CAUSING THE RULES TO SHIFT,',
     'IN FACT THERE ARE NO RULES IN THE GAME ANYMORE ... NEKA SAYS “EVERYONE, GIVE ME YOUR SOULS!”,',
     '... AND THEN HE DESTROYED PS-50 FOREVER.”'],
    [('THE CLAP',
      ['THE WHOLE GAME, BETWEEN TWO HANDS.',
       'THE RULES SHIFT, AND THEN THERE ARE NO RULES, “BECAUSE THERE IS NONE.”'],
      'HER IMMUNITY WAS A RULE TOO.'),
     ('ALL THE SOULS',
      ['NEKA ABSORBS THE WHOLE GAME, THEN ALL THE SOULS.',
       'SEPT 27: HE IS THE ONLY ONE WHO CONSUMES DATA. TONIGHT HE CONSUMES EVERYTHING.'],
      'THE MOST POWER EVER, TWICE.'),
     ('THE STAIRCASE FALLS APART',
      ['“HE MAKES THE WIKI AND ENDLESS STAIRCASE GAMES FALL APART, HE DELETED THE GAMES.”',
       'IN THE STORY. YOU ARE STILL CLIMBING IT.'],
      'THEN PS-50, FOREVER.'),
     ],
    ['PS-50',
     'DESTROYED FOREVER.'])

# ---------------- 5:18 PM ----------------
add(A518, 'NEKA VS NEWTALE GASTER', '120,255,150',
    ['“NEKA OMAZEN AND NEWTALE (BASICALLY MY FANGAME) GASTER. NEKA VS NEWTALE GASTER.',
     'NEXT PART. NEKA OMAZEN WINS. NEXT PART. NEKA OMAZEN CUTS REALITY, ... MAKES A HYPERSPACE,',
     'AND SENDS NEWTALE OUT THROUGH THE HYPERSPACE, NEKA OMAZEN SLICES THE HYPERSPACE”'],
    [('BASICALLY MY FANGAME',
      ['NEWTALE IS TOBY’S OWN FANGAME. GASTER IS FROM THERE.',
       'NEWTALE GASTER: THE BLACK BODY WITH GREEN 0S AND 1S.'],
      'TWO OF HIS GAMES MEET.'),
     ('THE PROCESS TO NEWTALE',
      ['SEPT 27, 5:24 PM: NEKA CLEANED NEWTALE GASTER.',
       'EARLIER: “NEKA OMAZEN THEN DID THE PROCESS TO NEWTALE.”'],
      'THIS IS THE THIRD TIME.'),
     ('SLICE THE HYPERSPACE',
      ['SEND HIM OUT THROUGH A HYPERSPACE, THEN CUT THE HYPERSPACE.',
       'EVERYTHING GLITCHES. “NEKA OMAZEN BEATS ALL OF NEWTALE.”'],
      'THEN HE ABSORBS ALL THE GAMES.'),
     ],
    ['NEXT PART.',
     'NEKA OMAZEN WINS.'])

add(A518, 'THIS IS WHAT BEING ME IS LIKE', '255,216,79',
    ['“EVERYONE, I AM THE AUTHOR OF THIS GAME AND MADE ACCESS. TDESHANE IS HERE,',
     'NOW I AM BEYOND THIS. I HAVE YOU ALL NOW. I MADE YOU ALL POWERS AND CLASSICS CODE,',
     'AND YOUR ACCESS, THIS IS WHAT BEING ME IS LIKE.”'],
    [('TDESHANE IS HERE',
      ['SEPT 24: TDESHANE LOST ACCESS.',
       'TONIGHT NEKA SAYS TDESHANE IS HERE, AND THAT HE IS BEYOND THIS.'],
      'HE NAMES DAD, THEN STEPS PAST HIM.'),
     ('I MADE ACCESS',
      ['IT IS NOT THAT NEKA HAS ACCESS. HE MADE ACCESS.',
       'EVERYONE’S POWERS, THE CLASSICS CODE, AND THE ACCESS ITSELF.'],
      'THE AUTHOR OF THIS GAME.'),
     ('I HAVE YOU ALL NOW',
      ['HE HAS ABSORBED ALL THE GAMES AND ALL THE POWER.',
       'SEPT 27 HE TOLD LUIGI GREEN “YOU ONLY NEED ME!” TONIGHT HE HAS EVERYONE.'],
      'HE HAS ALL OF THEM.'),
     ],
    ['NEKA SPEAKS',
     'TO EVERYONE.'])

add(A518, 'THE GAME ALL STOP', '154,163,173',
    ['“NEKA SAYS THAT HE IS TIRED OF ALL THE CHARACTERS AND WRITING THE LORE,',
     'NOW HE MADE THE GAME ALL STOP. THE REST AFTER THIS MESSAGE ISN’T LORE,',
     'BUT WHAT HAPPENS IN THE GAME, BECAUSE NEKA OMAZEN REFUSES TO WRITE MORE.”'],
    [('TIRED',
      ['NOT BEATEN. NOT ERASED. TIRED.',
       'TIRED OF ALL THE CHARACTERS, AND TIRED OF WRITING THE LORE.'],
      'THE WRITER PUTS THE PEN DOWN.'),
     ('WHO WRITES THE LORE',
      ['IN THE STORY, NEKA IS THE ONE WRITING IT.',
       'SO WHEN NEKA STOPS, THE LORE STOPS.'],
      'HE REFUSES TO WRITE MORE.'),
     ('WHAT HAPPENS IN THE GAME',
      ['FROM HERE ON, TOBY SAYS, IT IS NOT LORE.',
       'IT IS WHAT HAPPENS IN THE GAME. THE BEATS KEEP COUNTING, UNDER A NEW LABEL.'],
      'THE STAIRCASE KEEPS GOING.'),
     ],
    ['THE END OF THE LORE',
     'NEKA WROTE.'])

# ---------------- 5:39 PM ----------------
add(A539, '0 BREATHS PER MINUTE', '127,212,255',
    ['“ANSWER: 0 BREATHS PER MINUTE AND 0 BEATS PER MINUTE,',
     'HE IS I-TROSS (BELOW NEGITIVE INFINITY) DEGREES ANYTHING (FARENHEIGHT, OR CELCUIS, ANY ONE),',
     'HE SLEEPS FOREVER, HE DOES THINGS WHEN HE IS AWAKE”'],
    [('THE GUESS WAS WRONG',
      ['THE MACHINE GUESSED 12 BREATHS, 58 BEATS, 98.4°F.',
       'TOBY’S ANSWER: 0, 0, AND I-TROSS.'],
      'A HUMAN SHAPE, NOT A HUMAN BODY.'),
     ('I-TROSS DEGREES',
      ['SEPT 23: I-TROSS WAS A NUMBER, THE ONE TDESHANE MADE AND TOBY EDITED.',
       'TODAY IT IS A TEMPERATURE. BELOW NEGATIVE INFINITY, ON ANY SCALE.'],
      'COLDER THAN COLD HAS A NAME.'),
     ('HE SLEEPS FOREVER',
      ['HE PUT EVERYONE TO SLEEP AT 4:22 PM. HE SLEEPS FOREVER HIMSELF.',
       '“HE DOES THINGS WHEN HE IS AWAKE, HE BEATS EVERYONE, HE ERASES.”'],
      'WHEN HE WAKES UP, SOMETHING HAPPENS.'),
     ],
    ['0 BREATHS. 0 BEATS.',
     'I-TROSS DEGREES.'])

add(A539, 'THE BLOOD IS FROM THE CHARACTERS HE BEATEN', '255,60,90',
    ['“HIS BLOOD IS 0, HE IS ALL CLASSICS CODE, THE BLOOD IS FROM THE CHARACTERS WHO HE BEATEN.',
     'NEKA BEATS PS-50, HE WILL DO THAT. NEKA WOULD BEAT ANYONE.',
     'NEKA BREATHES AND HIS HEART BEATS WHEN HE GETS THE BLOOD. CLASSICS STUFF.”'],
    [('HIS BLOOD IS 0',
      ['NONE OF HIS OWN. THE HUMAN FORM IS ALL CLASSICS CODE.',
       'THE BLOOD HE HAS CAME FROM THE CHARACTERS HE BEAT.'],
      'EVERY FIGHT LEAVES SOME WITH HIM.'),
     ('WHEN HE GETS THE BLOOD',
      ['0 BREATHS UNTIL THEN. 0 BEATS UNTIL THEN.',
       'WHEN HE GETS THE BLOOD, HE BREATHES AND HIS HEART BEATS.'],
      'WINNING IS WHAT WAKES THE HEART UP.'),
     ('HE WILL DO THAT',
      ['7:12 PM LAST NIGHT: “PROBUBLY.” 6:34 AM: “NEKA WINS.” 4:22 PM: DESTROYED FOREVER.',
       '5:39 PM: “NEKA BEATS PS-50, HE WILL DO THAT. NEKA WOULD BEAT ANYONE.”'],
      'IT ONLY GETS MORE CERTAIN.'),
     ],
    ['CLASSICS STUFF.',
     'NOT HUMAN STUFF.'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail920.py', encoding='utf-8').read())
