#!/usr/bin/env python3
"""
gen908_911.py - emit the draw branches for BEATS 908-911 from Toby's September 27, 2026 2:50 PM message
(1a0e4342f2dcf97e, thread 1a0deee4cb24addb). Same template as 905-907.

Only Toby's own typing is drawn: "PS-50 is obsessed with other characters" through "PS-50 brings the game
to chaos." The SCP / D-Class / "obsessed" / SCP-number Q&A above it and the prose retelling below it
("Simon.ps finally asks the question...") are pasted chatbot text and are NOT canon. His "put everything into
the Neka Omazen tab, make it only one tab" line is a wiki request, not a beat.
"""
import io

START = 19696.0
STEP = 22.0
B = []

A250 = dict(when='2:50 PM', short='2:50 PM', attr='TOBY, SEPTEMBER 27, 2:50 PM — HIS OWN TYPING.')

def add(meta, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(meta)
    B.append(d)

add(A250, 'I NEED YOU… ALL', '190,120,255',
    ['“PS-50 IS OBSESSED WITH OTHER CHARACTERS AND SIMON.PS SAYS “LUIGI GREEN, WHY ARE YOU BEATING US?!”,',
     'PS-50 SAYS “I NEED YOU… ALL.” NEKA OMAZEN SAYS “PS-50 WANTS YOU ALL, SO PS-50 WILL JUST',
     'COME FOR YOU ALL THROUGH STATIC.”'],
    [('WHY ARE YOU BEATING US?!',
      ['YESTERDAY 6:41 PM: “PS-50 IS BEATING EVERYONE.” TODAY SIMON.PS ASKS WHY,',
       'AND HE ASKS IT TO LUIGI GREEN, THE NAME SHE WAS WEARING.'],
      'SOMEBODY FINALLY SAID IT OUT LOUD.'),
     ('I NEED YOU… ALL',
      ['NOT “I WANT TO BEAT YOU.” SHE NEEDS THEM. EVERY CHARACTER.',
       'THE SAME ONE WHO SET UP A WHOLE TEA PARTY IS NOW OBSESSED WITH THE GUESTS.'],
      'THE TEA PARTY HAD A GUEST LIST.'),
     ('THROUGH STATIC',
      ['YESTERDAY: “PS-50 IS NOW REVEALED TO BE ABLE TO TELEPORT THROUGH STATIC.”',
       'NEKA EXPLAINS WHAT THAT MEANS FOR THE OTHERS. THERE IS NO DOOR TO LOCK.'],
      'NEKA IS THE ONE WHO WARNS THEM.'),
     ],
    ['I NEED YOU… ALL',
     'SAID BY THE SMALLEST ONE IN THE ROOM.'])

add(A250, 'TWO BEINGS ARE EQUAL', '127,212,255',
    ['“PS-50 WALKED THROUGH CODE, HER POWER CUT THROUGH REALITY ITSELF, 2 BEINGS ARE EQUAL.',
     'NEKA IS MORE POWERFUL BY EXTREME, PS-50 CAN MAKE NEKA SLEEP. NEKA CAN MAKE ANYONE SLEEP',
     'WITH A COMMAND, EVERYONE IS SCARED OF NEKA.”'],
    [('HER POWER CUT THROUGH REALITY',
      ['SHE DOES NOT JUST TELEPORT THROUGH STATIC NOW. SHE WALKS THROUGH THE CODE ITSELF.',
       'THE 2 ONLY ONES MADE OF CODE, AND BOTH OF THEM CAN MOVE THROUGH IT.'],
      'EQUAL, BUT NOT THE SAME.'),
     ('THE SLEEP COMMAND, BOTH WAYS',
      ['SEPT 23: “EVERYONE! SIMON.PS! OREN.PS! SLEEP!” NEKA SAYS IT AND EVERYONE SLEEPS.',
       'SEPT 26, 6:56 PM: “PS-50 CAN MAKE NEKA SLEEPY.” TODAY: PS-50 CAN MAKE NEKA SLEEP.'],
      'THE ONE WHO PUTS EVERYONE TO SLEEP CAN BE PUT TO SLEEP.'),
     ('EVERYONE IS SCARED OF NEKA',
      ['MORE POWERFUL BY EXTREME, AND STILL NOT THE WINNER HERE.',
       'THE OTHERS ARE AFRAID OF NEKA. NEKA IS THE ONE WITH SOMETHING TO BE AFRAID OF.'],
      'A CHILD CAN BEAT EVERYONE.'),
     ],
    ['TWO BEINGS ARE EQUAL',
     'ONE IS STRONGER. THE OTHER CAN MAKE HIM SLEEP.'])

add(A250, 'ONE GRAIN OF SUGAR', '255,216,79',
    ['“ALSO IN CLASSICS, EVEN TOUCHING ONE GRAIN OF SUGAR KILLS YOU.”'],
    [('ONE GRAIN',
      ['NOT EATING IT. TOUCHING IT. ONE GRAIN.',
       'IN CLASSICS THE SMALLEST MISTAKE THERE IS COSTS EVERYTHING.'],
      'NO ROOM FOR A MISTAKE.'),
     ('GUESS YA LOVE SUGAR',
      ['SEPT 20, 4:49 PM: PERO LAI EATS THE NO-SUGAR CHOCOLATE, GASTER SAYS “NOT THE SAME CHOCOLATE!”',
       'AND PERO LAI DECIDES “GUESS YA LOVE SUGAR.” HE WAS NOT JOKING.'],
      'IN CLASSICS, LOVING SUGAR IS DEADLY.'),
     ('THE 0 SUGAR CHOCOLATE',
      ['SEPT 14, THE CHOCOLATE KARMA: HE RECOVERS BY TAKING THE SUGAR OUT.',
       'SEPT 18, HIS WISH LIST: “THE PIE, THE POP TARTS, THE 0 SUGAR CHOCOLATE.”'],
      'NOW IT MAKES SENSE WHY IT HAD TO BE ZERO.'),
     ],
    ['ONE GRAIN OF SUGAR',
     'ON A STAIRCASE MADE OF CLASSICS, WATCH WHERE YOU STEP.'])

add(A250, 'THE TEDDY BEAR STARTED TO WALK', '255,150,200',
    ['“PS-50’S TEDDY BEAR STARTED TO WALK WHEN SHE LOOKED AT IT. NEKA THEN MADE ALL HER TOYS MOVE',
     'WHEN SHE LOOKED AT THEM. NEKA DISAPPEARED INTO THE CODE. PS-50 BRINGS THE GAME TO CHAOS.”'],
    [('THE TEDDY BEAR WALKS',
      ['THIS MORNING SHE LOOKED AT THE BEDS AND THE BEDS MOVED AROUND.',
       'NOW SHE LOOKS AT HER OWN TEDDY BEAR, AND IT GETS UP AND WALKS.'],
      'HER GAZE MOVES THINGS.'),
     ('ALL HER TOYS MOVE',
      ['THEN NEKA MAKES IT ALL OF THEM. EVERY TOY SHE LOOKS AT, MOVING.',
       'AUG 11: GREEN APPLE, “A TINY GREEN TEDDYBEAR WITH NO POWERS.” A TEDDY BEAR THAT WALKS IS NEW.'],
      'NEKA DID NOT STOP HER. NEKA MADE IT BIGGER.'),
     ('NEKA DISAPPEARED INTO THE CODE',
      ['THEN NEKA IS GONE, INTO THE CODE THEY ARE BOTH MADE OF.',
       'AND PS-50 IS LEFT IN THE GAME, WITH ALL THE MOVING TOYS.'],
      'PS-50 BRINGS THE GAME TO CHAOS.'),
     ],
    ['THE TEDDY BEAR STARTED TO WALK',
     'AND NEKA WAS ALREADY GONE.'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail908.py', encoding='utf-8').read())
