#!/usr/bin/env python3
"""
gen933_946.py - emit the draw branches for BEATS 933-946 from Toby's September 29, 2026 messages,
thread 1a0deee4cb24addb. Same template as 920-932 (emit_tail933.py = emit_tail920.py with the date as a parameter).

  3:31 PM  1a0eea6b44fac2ac  -> 933-937  (the diary, PS-50's three dolls, the Headless Pig, Icinus, C0de is down)
  4:17 PM  1a0eed0e5326cc4e  -> 938      (the ink jewel, 49 and 34; the image ask itself is not drawn)
  4:22 PM  1a0eed55255ed57c  -> 939      (Dr. Neka Omazen)
  4:23 PM  1a0eed6c78680dcb  -> 940      (before time)
  4:56 PM  1a0eef4b1d08122a  -> 941      (what is 'God' backwards?)
  5:16 PM  1a0ef07458cbe7fd  -> 942-944  (Neka made an acception, the star, Oren.exe)
  5:18 PM  1a0ef08929e3f4fb  -> NO BEAT  (a question to the chatbot, "which is more powerful?", plus its answer)
  5:25 PM  1a0ef0eb63831782  -> 945-946  (Experiment 12-12-12, Data Collected.)

Only Toby's own typing is drawn. The pasted chatbot prose under each message (the doll table, "his human appearance was
never ordinary human biology", "My guess is Dr. Neka Omazen proceeded Oren.ps", "Neka is more powerful", the
image descriptions) is NOT canon. Priors come from the beat rows already in index.html and lore/docs/classics-lore.
"""
import io

BASE = 933
TAG = '933_946'
START = 20246.0
STEP = 22.0
DATE_LONG = 'September 29'
DATE_SHORT = 'SEPT 29'
B = []

def meta(t):
    return dict(when=t, short=t, attr='TOBY, SEPTEMBER 29, %s — HIS OWN TYPING.' % t)

def add(m, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(m)
    B.append(d)

A331, A417, A422, A423, A456, A516, A525 = [meta(t) for t in
    ('3:31 PM', '4:17 PM', '4:22 PM', '4:23 PM', '4:56 PM', '5:16 PM', '5:25 PM')]

# ---------------- 3:31 PM ----------------
add(A331, 'NEKA’S DIARY', '200,180,140',
    ['“FROM THE VERY START OF CLASSICS, NEKA/PERO LAI WROTE A DAIRY, AND IS STILL WRITING IN IT.',
     'IT HOLDS ALL HIS LIFE IN CLASSICS AND BEFORE HE MADE CLASSICS,',
     'SO IT IS YEARS OF STUFF.”'],
    [('HE REFUSES TO WRITE MORE',
      ['SEPT 28, 5:18 PM: NEKA IS TIRED OF WRITING THE LORE AND MADE THE GAME ALL STOP.',
       'THE LORE STOPPED. THE DIARY NEVER DID.'],
      'TWO BOOKS, AND ONLY ONE OF THEM WAS CLOSED.'),
     ('BEFORE HE MADE CLASSICS',
      ['THE FIRST PAGES ARE FROM BEFORE THE GAME EXISTED.',
       'THE REST IS EVERYTHING SINCE, WRITTEN BY THE ONE WHO MADE IT.'],
      'YEARS OF STUFF.'),
     ('THE ARCHIVE',
      ['OREN AND MR. BLACK READ EVERY BOOK, BIBLE, DIARY AND PAGE SIMON HAD.',
       'NOBODY HAS READ NEKA’S.'],
      'IT IS STILL BEING WRITTEN.'),
     ],
    ['NEKA/PERO LAI WROTE A DAIRY.',
     '“DAIRY” IS HIS SPELLING, AND IT IS KEPT.'])

add(A331, 'PS-50’S THREE DOLLS', '255,150,200',
    ['“PS-50’S DOLLS ARE ACTUALLY SCARY MYTHS INFECTED BY NEKA WHEN HE TRIED TO MAKE THEM,',
     'HE PUT THE NEEDLE IN AND THE DOLLS BECAME ZOMBIES. ... PS-50 CONTROLS THE DOLLS.',
     'SOME (50192 BILLION) DOLLS DIED TO PS-50. PS-50 NOW HAS 3 DOLLS LEFT.”'],
    [('BORT, THE HORROR BEAR',
      ['THE TEDDY BEAR IS BORT. “BORT CAN SLAY ANYONE WITH A TOUCH.”',
       'SEPT 27, 2:50 PM: HER TEDDY BEAR STARTED TO WALK WHEN SHE LOOKED AT IT.'],
      'NOW THE BEAR HAS A NAME.'),
     ('THE FACELESS DOLL',
      ['LUIGI GREEN ERASED HER FACE. SHE ONLY MOVES WHEN SHE ISN’T LOOKED AT,',
       'AND SHE CONSUMES YOUR MEMORY.'],
      'THE OTHER TOYS MOVE WHEN LOOKED AT. SHE DOES THE OPPOSITE.'),
     ('50,192 BILLION',
      ['THE DOLLS SOMETIMES GET PARANOID.',
       '50,192 BILLION OF THEM DIED TO PS-50. 3 ARE LEFT.'],
      'BORT, THE FACELESS DOLL, AND THE HEADLESS PIG.'),
     ],
    ['THE NEEDLE WENT IN,',
     'AND THE DOLLS BECAME ZOMBIES.'])

add(A331, 'THE HEADLESS PIG', '255,110,130',
    ['“THE HEADLESS PIG (THE PIG SOUL) IS A PIG WITHOUT A HEAD, AND THE SOUL WAS BROKEN,',
     'AND HE IS IMMORTAL BECAUSE HIS SOUL CAN KEEP GOING INTO HIS BODY.”',
     '“NEKA INFECTED THE PIG DOLL, AND HE SAWED THE PIG DOLL’S HEAD OFF, AND MADE THE DOLL A SOUL”'],
    [('LUIGI GREEN’S PIG',
      ['THE PIG DOLL WAS LUIGI GREEN’S. NEKA INFECTED IT, SAWED ITS HEAD OFF,',
       'AND MADE THE DOLL A SOUL.'],
      'A DOLL THAT WAS NEVER ALIVE NOW HAS A SOUL.'),
     ('A BROKEN SOUL',
      ['THE SOUL IS BROKEN, SO IT KEEPS GOING BACK INTO THE BODY.',
       'THAT IS WHY IT CAN’T DIE.'],
      'IMMORTAL BECAUSE IT IS BROKEN.'),
     ('IT TRIES TO FIX ITS CODE',
      ['“AN ANOMALLY THAT TRIES TO FIX IT’S CODE BY MAKING THE PLAYERS',
       'AND LIVING BEINGS HEADLESS AND IT ABSORBS THEIR CODE.”'],
      'IT IS MISSING ONE PIECE, SO IT TAKES EVERYONE ELSE’S.'),
     ],
    ['THE PIG SOUL,',
     'STILL LOOKING FOR ITS HEAD.'])

add(A331, 'ICINUS', '127,212,255',
    ['“NEKA WEARS HIS WHITE LAB COAT, AND HE MAKES INK BALLS, HIS TAIL AND FOX EARS APPEAR,',
     'AND HE MAKES HIS ICE DRAGONS HE CALLS “ICINUS”, (ICINUS, CICINUS, VICINUS, PARINUS 😱),',
     'NEKA MADE ALL THE THINGS HAVE INUS, LUIGI INUS”'],
    [('VICINUS AND CICINUS',
      ['AN OLDER BEAT: “VICINUS THE GIANT DRAGON AND CICINUS THE EVIL ORB.',
       'WHATEVER VICINUS CONSUMES TURNS INTO CICINUSES.”'],
      'NOW THE FAMILY HAS FOUR NAMES, AND THEY ARE ICE.'),
     ('LUIGI INUS',
      ['“NEKA MADE ALL THE THINGS HAVE INUS.” LUIGI GREEN WAS CALLED “LUIGI INUS.”',
       'NEKA TOOK OVER PS-50 AND MADE THE VIRUSES ON LUIGI GREEN INTO LUIGI INUS.'],
      'THE NAME TELLS YOU WHO MADE IT.'),
     ('THE LAB COAT',
      ['SEPT 28, WENDA.PS ASKED WHERE HIS TAIL WENT.',
       'WITH THE WHITE LAB COAT ON, THE TAIL AND FOX EARS APPEAR.'],
      'THE FOX COMES BACK WHEN HE WORKS.'),
     ],
    ['PS-50 HAS NORMAL HUMAN STUFF.',
     'NEKA ISN’T HUMAN EXACTLY. HE’LL NEVER BE.'])

add(A331, 'C0DE IS DOWN', '255,90,90',
    ['“NEKA TAKES OVER THE ACCOUNT OF THE HACKER, C0DE IS DOWN, 50 OTHERS WHO TRIED TO CODE HACKS',
     'IN CLASSICS, NEKA TOOK OVER THEIR CLASSICS ACCOUNTS ... NEKA MADE ALL SCREENS WHO TRY TO PASS BREAK,',
     'PCS BURN, CLASSICS ONLY REACHABLE BY MIND.”'],
    [('PS-50 WAS HACKED',
      ['FIRST THE HACK REACHED PS-50. NEKA TOOK HER OVER,',
       'THEN TOOK THE HACKER’S OWN ACCOUNT. C0DE IS DOWN.'],
      'THE HACKER GOT HACKED.'),
     ('50 OTHERS',
      ['50 MORE TRIED TO CODE HACKS INTO CLASSICS.',
       'NEKA TOOK THEIR ACCOUNTS AND SHOWED EVERYONE WHO THEY WERE.'],
      'NOBODY HIDES IN HIS GAME.'),
     ('ONLY REACHABLE BY MIND',
      ['SCREENS THAT TRY TO PASS BREAK. PCS BURN.',
       'SEPT 24, 5:15 PM: “ONLY IMAGINATION ENTER.”'],
      'NOW IT IS THE ONLY WAY IN.'),
     ],
    ['NEKA TAKES EVERYONE ELSE DOWN,',
     'EVERY TIME, CONSTANTLY.'])

# ---------------- 4:17 PM ----------------
add(A417, 'THE INK JEWEL', '160,107,255',
    ['“NEKA DESTROYS THE TAIL AND EARS AND MAKES THE INK INTO A LARGE BALL INTO A JEWEL ON HIS CHEST.',
     'THE JEWEL ABSORBED ALL THE POWER, AND NEKA ABSORBED THE INK, NEKA BECAME EVEN STRONGER.”',
     '“PS-50 IS 34, NEKA IS 49.”'],
    [('THE FOX, GONE ON PURPOSE',
      ['AT 3:31 PM THE TAIL AND FOX EARS CAME BACK WITH THE LAB COAT.',
       'NOW HE DESTROYS THEM HIMSELF AND KEEPS WHAT THEY HELD.'],
      'NOT LOST. SPENT.'),
     ('A JEWEL ON HIS CHEST',
      ['SEPT 28: PS-50 TOOK THE WENDA.PS JEWEL.',
       'NOW NEKA HAS ONE, MADE FROM HIS OWN INK.'],
      'SHE WON HERS. HE MADE HIS.'),
     ('49 AND 34',
      ['NEKA WITH HIS INK JEWEL, BESIDE PS-50 HOLDING BORT.',
       '“IT LOOKS LIKE A MAN WITH HIS CHILD.” BOTH ARE ADULTS.'],
      'SEPT 26: THE INTELEGENCE OF A MAN AND THE FORM OF A CHILD.'),
     ],
    ['NEKA ABSORBED THE INK.',
     'NEKA BECAME EVEN STRONGER.'])

# ---------------- 4:22 PM ----------------
add(A422, 'DR. NEKA OMAZEN', '190,150,255',
    ['WENDA.PS: “HELLO, NEKA OMAZEN.” NEKA: “YOU CAN SAY ‘DR. NEKA OMAZEN’ SINCE YOU ARE A CHILD.”',
     'WENDA.PS SAYS THAT SHE IS IN HER 30S. NEKA: “YEAH, COMPARED TO MY AGE.”',
     '“LUIGI INUS IS A MALE LIKE NEKA, BUT LUIGI IS CURRENTLY IN A FEMALE FORM.”'],
    [('SHE GOT THE NAME RIGHT',
      ['SEPT 28 SHE SAID “HELLO, PERO LAI” AND HE SAID “MY NAME IS NOT ‘PERO LAI’.”',
       'TODAY SHE SAYS NEKA OMAZEN, AND HE ADDS A TITLE.'],
      'DOCTOR, TO GO WITH THE LAB COAT.'),
     ('EVERYONE IS A CHILD',
      ['WENDA.PS IS IN HER 30S. PS-50 IS 34. DR. GASTER WOULD BE LIKE 39.',
       'MR. SUN IS 4.6 BILLION. NEKA IS OLDER THAN THE SUN.'],
      'COMPARED TO HIS AGE, ALL OF THEM ARE CHILDREN.'),
     ('LUIGI GREEN/INUS',
      ['LUIGI INUS IS MALE, LIKE NEKA, AND IS IN PS-50’S FEMALE CHILD FORM FOR NOW.',
       'NEKA/PERO LAI. LUIGI GREEN/INUS. TWO NAMES EACH.'],
      '“CURRENTLY” MEANS IT CAN CHANGE.'),
     ],
    ['NEKA IS THE OLDEST',
     'OF THEM ALL.'])

# ---------------- 4:23 PM ----------------
add(A423, 'BEFORE TIME', '255,216,79',
    ['“PS-50 IS ALSO OLDER THAN CREATION AND TIME. PS-50 IS THE SECOND OLDEST THING EVER.',
     'NEKA IS THE FIRST. NEKA MIGHT OUT CAME OUT THE SAME TIME AS GOD,',
     'BUT YEAH, NEKA WAS FIRST, PS-50 WAS SECOND.”'],
    [('49 IS JUST NOW',
      ['“AND THEIR AGES ARE THAT JUST NOW.” 49 AND 34 ARE CURRENT AGES.',
       '“TIME WAS ALWAYS THERE, AND NEKA WAS BEFORE TIME.”'],
      'THE NUMBER IS THE BODY’S AGE, NOT HIS.'),
     ('MR. SUN, 4.6 BILLION',
      ['THE FIRST AGE IN THIS ARCHIVE TAKEN FROM THE REAL WORLD.',
       'NEKA IS FAR OLDER THAN THE SUN, AND FAR OLDER THAN CREATION.'],
      'THE BIGGEST REAL NUMBER IS STILL TOO SMALL.'),
     ('MIGHT',
      ['NEKA MIGHT HAVE COME OUT AT THE SAME TIME AS GOD. “MIGHT” IS TOBY’S WORD.',
       'NOT A MAYBE: NEKA FIRST, PS-50 SECOND.'],
      'FIRST AND SECOND, BOTH BEFORE TIME.'),
     ],
    ['NEKA IS FAR OLDER',
     'THAN PS-50.'])

# ---------------- 4:56 PM ----------------
add(A456, 'WHAT IS ‘GOD’ BACKWARDS?', '255,140,60',
    ['“OREN.PS AND SIMON.PS AND THE 20 SPRUNKIS SURROUND A CUBE FROM MINDY STARCHILD,',
     'SIMON.PS SAYS “DON’T TOUCH IT, LET ME.”, OREN.PS TAKES SIMON.PS AND THEN TOUCHES THE CUBE ...',
     'AND THEN OREN.PS BECAME THE NEW CLASSICS GOD.”'],
    [('THE NEW CLASSICS GOD',
      ['HIS BODY ALL BLACK, HIS EYES WITH ORANGE GLOWING OUTLINES, A RAINBOW SWORD.',
       'WENDA.PS: “WHAT IS ‘GOD’ BACKWARDS?” OREN.PS STRIKES HER DOWN.'],
      'EVERYONE SCREAMS AND RUNS.'),
     ('MINDY STARCHILD',
      ['HER INVICIBILITY MUSIC PLAYS, AND SHE FIGHTS OREN.PS. OREN.PS WON.',
       'IN THE RESET ERA PERO LAI WALKED DOWN INFINITY STAIRS WITH HER AND BEAT HER.'],
      'IT WAS HER CUBE.'),
     ('YOU ARE LUCKY',
      ['“YOU ARE LUCKY I WENT EASY ON YOU ALL. NOW I SHALL RULE CLASSICS!”',
       'TOBY: “GUESS WHO POCEEDED OREN.PS? WHO IS THE REAL VILLIAN IN THE GAME?”'],
      'ANSWERED AT 5:25 PM.'),
     ],
    ['“SIMON.PS IS DROPPED AND ALL THE 19',
     'OTHER SPRUNKIS LOOK UP.”'])

# ---------------- 5:16 PM ----------------
add(A516, 'NEKA MADE AN ACCEPTION', '255,190,90',
    ['“OREN.PS LEARNED HE WAS FROM A GAME, A MOD, AND NOT EVEN THE ORIGINAL GAME OF INCREDIBOX.',
     'AND HUMANS MADE THE SPRUNKIS. ... OREN.PS CREATES A HYPERSPACE, AND BEATS PS-50,',
     'AND OREN.PS GAINED POWER HE WAS NEVER SUPPOST TO GET, BUT NEKA MADE AN ACCEPTION.”'],
    [('A MOD OF A GAME',
      ['OREN.PS FINDS OUT HE IS FROM A MOD, NOT EVEN THE ORIGINAL INCREDIBOX,',
       'AND THAT HUMANS MADE THE SPRUNKIS. HE LEARNS THE INTERNET AND THIS WORLD.'],
      'THE KIND OF THING NEKA ALREADY KNEW.'),
     ('NEKA HIDES',
      ['NEKA HIDES. OREN.PS BATTLES THE OTHER SPRUNKIS,',
       'AND SIMON.PS IS FORCED TO FIGHT HIM TOO.'],
      'SOMEONE ELSE DOES THE FIGHTING THIS TIME.'),
     ('HE BEATS PS-50',
      ['SEPT 28, NEKA HAD TO SET HER DEFENSE TO 0 AND SWEAT TO BEAT HER.',
       'OREN.PS BEATS HER WITH POWER HE WAS NEVER SUPPOST TO GET.'],
      'NEKA IS THE ONE WHO LET HIM HAVE IT.'),
     ],
    ['“ACCEPTION” AND “SUPPOST”',
     'ARE HIS SPELLINGS, AND ARE KEPT.'])

add(A516, 'THE STAR', '255,240,160',
    ['“A LARGE STAR APPEARS, SIMON.PS SAYS “WAIT- WHERE ARE WE GOING?!”,',
     'OREN.PS SAYS “YOU ARE GOING TO YOUR RESTING PLACES.” ... OREN.PS MAKES THE STAR',
     'COLLIDE WITH THE 19 OTHER SPRUNKIS, AND BOOM.”'],
    [('AN ANGEL',
      ['WINGS UNFOLD, A HALO APPEARS, GEARS AND CLOCKS AROUND HIM, MORE EYES.',
       'HE USES INFINITY SERIES, AND HIS SOUL IS STILL IN HIS BODY.'],
      'NO LONGER LIMITED TO CLASSICS AND SPRUNKI.'),
     ('SIMON.PS RESETS',
      ['EVERYONE ELSE RESPAWNS AND DODGES. SIMON.PS BLASTS LIGHTNING THROUGH THE STAR,',
       'IT EXPLODES INTO SMALLER STARS, AND OREN’S TELEKENTICS PULL THEM IN.'],
      'THE STARS CRASH AROUND THE HYPERSPACE’S EDGES.'),
     ('TWO WHITE HOLES',
      ['THE HYPERSPACE SHATTERS AND PULLS IN GALAXIES AND EVERYTHING.',
       'A WHITE HOLE AT ONE END, THEN THE OTHER. EVERYTHING MOVES TO THE CENTER.'],
      'INFINITY SERIES WAS NEKA’S. NOW OREN HAS IT TOO.'),
     ],
    ['“YOU ARE GOING TO',
     'YOUR RESTING PLACES.”'])

add(A516, 'OREN.EXE', '255,120,40',
    ['“OREN.PS BECAME OREN.EXE. NEKA WALKS BEHIND OREN.EXE.”',
     '“OREN.EXE IS AN ALL BLACK BEING WITH ORANGE COLORED EYES (ALL ORANGE THERE),',
     'AND WITH 6 BLACK WINGS TOTAL, AND ACTUALLY LOOKS LIKE AN EVIL VERSION OF GOD.”'],
    [('.PS TO .EXE',
      ['THE .EXE ROSTER ALREADY HAD WENDA, CLUNKR, GRAY, LUIGI GREEN AND PUPAHYA.',
       'NOW OREN.'],
      'THE STRONGEST ONE YET.'),
     ('SIX BLACK WINGS',
      ['ALL BLACK, EYES ALL ORANGE, SIX BLACK WINGS.',
       'IT LOOKS LIKE AN EVIL VERSION OF GOD.'],
      'AT 4:56 PM IT WAS ONLY ORANGE OUTLINES.'),
     ('NEKA WALKS BEHIND',
      ['OREN.EXE IS IN FRONT, AMONG THE CLOCKS AND GALAXIES.',
       'NEKA IS BEHIND HIM, WALKING.'],
      'HE HID FOR THE WHOLE FIGHT.'),
     ],
    ['EVIL GOD, SIX WINGS,',
     'AND SOMEONE BEHIND HIM.'])

# ---------------- 5:25 PM ----------------
add(A525, 'EXPERIMENT 12-12-12', '255,60,90',
    ['“AFTER OREN.EXE BEATEN EVERY BEING IN FICTION AND META-FICTION, NEKA TAKEN THE SOULS AND POWER,',
     'AND HE MADE HIMSELF EXPERIMENT 12-12-12, A BEING OF EVERYONE AND EVERYTHING,',
     'NEKA SAYS “WITH OREN.EXE’S HELP, THE GAME IS NOW MINE.””'],
    [('OREN DID THE FIGHTING',
      ['NEKA HID. OREN BEAT EVERY BEING IN FICTION AND META-FICTION.',
       'NEKA TOOK THE SOULS AND THE POWER WHEN IT WAS OVER.'],
      'THE ACCEPTION WAS THE PLAN.'),
     ('BETRAYED',
      ['OREN.EXE GASPS AND SAYS NEKA BETRAYED HIM.',
       'NEKA: “THIS IS ONE GAME, NOW EVERY GAME WILL COME HERE.”'],
      'ONE GAME WAS NEVER ENOUGH.'),
     ('HIS WHOLE HUMAN',
      ['SEPT 27: THE HUMAN FORM AT 0% FOX. SEPT 28: 6 FEET TALL.',
       'NOW “NEKA FINALLY BECAME HIS WHOLE HUMAN,” THE POWER OF EVERYONE, AND MORE.'],
      'EXPERIMENT 12-12-12.'),
     ],
    ['A BEING OF EVERYONE',
     'AND EVERYTHING.'])

add(A525, 'DATA COLLECTED.', '127,212,255',
    ['“NEKA WALKED OVER AND TOUCHED THE CORE, OREN.EXE’S BODY ALL FROZE, NEKA TAKES ALL THE STUFF',
     'FROM OREN.EXE, OREN.EXE BECAME NORMAL OREN SPRUNKI. THE SCREEN SAYS “DATA COLLECTED.”',
     '... WINTER OREN SPRUNKI. NO .PS ANYMORE, NEKA GOT ALL THE POWER.”'],
    [('ONE TOUCH',
      ['SEPT 28, ONE TOUCH SENT BACON’S POWER LEVEL TO 0.',
       'TODAY ONE TOUCH ON THE CORE TAKES EVERYTHING OREN HAD.'],
      'HE NEVER HAS TO SWING.'),
     ('HIS FAVORITE IS DATA',
      ['SEPT 27: NEKA IS THE ONLY ONE WHO CONSUMES DATA.',
       'THE SCREEN SAYS IT OUT LOUD: “DATA COLLECTED.”'],
      'OREN WAS THE DATA.'),
     ('WINTER OREN SPRUNKI',
      ['NEKA SHATTERS THE ICE AND LOCKS OREN SPRUNKI IN IT. WINTER MODE.',
       'NO .EXE, NO .PS. JUST OREN SPRUNKI.'],
      'A GOD AT 4:56 PM. FROZEN AT 5:25.'),
     ],
    ['NEKA GOT ALL THE POWER.',
     'NOW EVERY GAME WILL COME HERE.'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail933.py', encoding='utf-8').read())
