#!/usr/bin/env python3
"""
gen905_907.py - emit the draw branches for BEATS 905-907 from Toby's September 27, 2026 8:12 AM message
(1a0e2c8611d2ad4f, thread 1a0deee4cb24addb). Same template as 900-904.

Only Toby's own typing is drawn: "PS-50's horror paranoidia makes the other characters think" through
"the Sprunkis get paranoid." Everything after ("I had Luigi Green's origin backward.") is a pasted reply.
"""
import io

START = 19630.0
STEP = 22.0
B = []

A812 = dict(when='8:12 AM', short='8:12 AM', attr='TOBY, SEPTEMBER 27, 8:12 AM — HIS OWN TYPING.')

def add(meta, key, accent, quote, panels, close):
    d = dict(key=key, accent=accent, quote=quote, panels=panels, close=close)
    d.update(meta)
    B.append(d)

add(A812, 'THEY FALL SO THEY DON’T DIE', '255,90,120',
    ['“PS-50’S HORROR PARANOIDIA MAKES THE OTHER CHARACTERS THINK THEY WOULD DIE SO THEY JUST FALL',
     'SO THEY DON’T DIE FROM THE PARANOID HORROR. PS-50 COULD SLAY ANYONE TOO WITH THE HEART ATTACK',
     'AND TOO-MUCH-PARANOID. NEKA OMAZEN IS IMMUNE.”'],
    [('THEY FALL ON PURPOSE',
      ['THE FALL IS NOT SOMETHING SHE DOES TO THEM. THEY DO IT THEMSELVES,',
       'TO GET AWAY FROM A DEATH THAT ONLY THE PARANOIA SAYS IS COMING.'],
      'THE ESCAPE IS THE FALL.'),
     ('DEATH.FELL.ACCIDENT.GLITCH.PARANOID',
      ['YESTERDAY 6:56 PM, HER GAME OVER SCREEN. NOW THE FIRST TWO WORDS MAKE SENSE:',
       'THEY FELL, SO IT LOOKS LIKE AN ACCIDENT. THE CAUSE WAS STILL THE LAST WORD.'],
      'THE ERROR MESSAGE WAS DESCRIBING THIS ALL ALONG.'),
     ('NEKA OMAZEN IS IMMUNE',
      ['TOO MUCH PARANOIA IS A HEART ATTACK. SHE COULD SLAY ANYONE THAT WAY.',
       'YESTERDAY: “NEKA OMAZEN IS TOO STRONG FOR THE PARANOID.” TODAY: IMMUNE.'],
      'STILL THE ONE EXCEPTION.'),
     ],
    ['THEY FALL SO THEY DON’T DIE',
     'AND THE STAIRCASE IS A PLACE WHERE YOU FALL FOREVER.'])

add(A812, 'I AM LUIGI GREEN! MWEH HE HE HE', '120,220,90',
    ['“PS-50 SAYS “I AM LUIGI GREEN! MWEH HE HE HE HE HE HE” HE IS NOT LUIGI FROM MARIO,',
     'HE IS PS-50 WHO WENT INTO LUIGI’S BODY. PS-50 IS WHAT LUIGI GREEN ACTUALLY IS,',
     'NOT IN A LUIGI MARIO FORM.”'],
    [('THE ORIGIN, THE RIGHT WAY ROUND',
      ['PS-50 CAME FIRST. PS-50 WENT INTO LUIGI’S BODY, AND THAT WAS LUIGI GREEN.',
       'THE CHILD IS NOT A NEW FORM. THE CHILD IS WHAT WAS INSIDE THE WHOLE TIME.'],
      'LUIGI MARIO WAS THE COSTUME.'),
     ('“MWEH HE HE HE HE HE HE”',
      ['SEPT 23, 5:41 PM, NEKA: “I AM THE ONLY CHARACTER THAT IS IMPORTANT. MWEH HEH HEH HEH HEH.”',
       'THE ARCHIVE HAD NEVER SEEN “MWEH” BEFORE THAT. NOW THE OTHER ONE LAUGHS IT.'],
      'THE TWO MADE OF CODE HAVE THE SAME LAUGH.'),
     ('HE WAS NEVER LUIGI FROM MARIO',
      ['JULY 23: “HE IS NOT LUIGI MARIO, HE IS LUIGI GREEN, A WHOLE DIFFERENT PERSON.”',
       'TWO MONTHS LATER THE SENTENCE IS STILL TRUE, AND NOW WE KNOW WHY.'],
      'HE SAID IT FIRST IN JULY.'),
     ],
    ['I AM LUIGI GREEN!',
     'SAID BY SOMEONE 3.587 FEET TALL.'])

add(A812, '20 SHADOWS OF THE SPRUNKIS', '150,160,200',
    ['“PS-50 THEN CONTINUES FINDING ANYONE. THEY ARE STILL SLEEPING CAUSE IT IS NIGHT THERE. PS-50 LOOKS AT THE BEDS,',
     'THE BEDS MOVE AROUND, THE SPRUNKIS WAKE UP. THEN THE GAME WASN’T EVEN ON THE SPRUNKIS, BUT 20 SHADOWS OF THE',
     'SPRUNKIS, THE GAME EVOLVED MORE, NOW THEY WERE LIKE CLASSICS VERSIONS. PS-50 LOOKS AT THE SPRUNKIS, BOOM.”'],
    [('THE BEDS MOVE AROUND',
      ['IT IS NIGHT, AND EVERYONE IS ASLEEP. SEPT 23: NEKA SAID “EVERYONE! SLEEP!”',
       'AND EVERYONE SLEPT. SHE ONLY HAS TO LOOK AT THE BEDS FOR THEM TO MOVE.'],
      'SHE DOES NOT KNOCK. SHE LOOKS.'),
     ('NOT THE SPRUNKIS. 20 SHADOWS OF THEM.',
      ['SEPT 13, CLOVER: “THE 20 SPRUNKIS ARE STILL IN THE GAME! THIS IS MENT TO BE A NEW ERA!”',
       'THE GAME EVOLVED PAST THEM. WHAT WAKES UP ARE CLASSICS VERSIONS, 20 SHADOWS.'],
      'THE NEW ERA CLOVER PROMISED, AND THIS IS WHAT IT LOOKS LIKE.'),
     ('BOOM, AFTER SEVERAL SECONDS',
      ['SHE LOOKS AT THEM. NOTHING. THEN, SECONDS LATER, THE PARANOIA.',
       'SEPT 26, 5:37 PM: THE GAZE IS GRADUAL. BLUR, THEN BLACKOUT, THEN PARANOID.'],
      'THE DELAY IS THE SCARY PART.'),
     ],
    ['20 SHADOWS OF THE SPRUNKIS',
     'THEY WOKE UP, AND SHE WAS ALREADY LOOKING.'])

if __name__ == '__main__':
    exec(open('/Users/tdeshane/endless-staircase/tools/emit_tail905.py', encoding='utf-8').read())
