#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the beat 364-368 canvas blocks for index.html, following the beat-363 template."""

def block(b):
    ph      = b['ph']
    c0      = b['c0']
    c1      = c0 + 22.0
    A, B, C = b['pal']          # three accent colours: col1, col2, col3
    Amid    = b['palr']         # rgba triples for the same three, no alpha
    o  = []
    w  = o.append
    w("  } else if(ph===%d){" % ph)
    for ln in b['comment']:
        w("    // " + ln)
    w("    // c in [%.1f,%.1f). Palette: %s" % (c0, c1, b['palnote']))
    w("    const dt = c - %.1f;" % c0)
    w("    const pul = 0.60+0.40*Math.abs(Math.sin(c*2.5));")
    w("    const nameA=Math.max(0,Math.min(1,(dt-0.4)/1.2));")
    w("    const qtA  =Math.max(0,Math.min(1,(dt-1.4)/1.4));")
    w("    const jbA  =Math.max(0,Math.min(1,(dt-4.6)/1.6));")
    w("    const btA  =Math.max(0,Math.min(1,(dt-7.6)/1.6));")
    w("    const bndA =Math.max(0,Math.min(1,(dt-10.4)/1.6));")
    w("    const insA =Math.max(0,Math.min(1,(dt-12.6)/1.4));")
    w("    const footA=Math.max(0,Math.min(1,(dt-18.0)/1.6));")
    w("    ctx.fillStyle='rgba(4,3,7,0.99)'; ctx.fillRect(0,top,W,H);")
    w("    ctx.save(); ctx.beginPath(); ctx.rect(0,top,W,H); ctx.clip();")
    w("")
    w("    // --- background ---")
    w("    const bgA=Math.max(0,Math.min(1,(dt-0.8)/2.2));")
    w("    const clsY=top+H*0.352;")
    w("    const SIDES=[['%s','%s','rgba(%s,0.86)'],['%s','%s','rgba(%s,0.84)']];"
      % (b['ring'][0][0], b['ring'][0][1], Amid[0], b['ring'][1][0], b['ring'][1][1], Amid[1]))
    w("    for(let k=0;k<8;k++){")
    w("      const ang=c*0.17+k*(Math.PI*2/8);")
    w("      const rx=cx+Math.cos(ang)*W*0.256, ry=clsY+Math.sin(ang)*H*0.104;")
    w("      const sd=SIDES[k%2];")
    w("      ctx.globalAlpha=g*bgA*0.032*(0.45+0.55*Math.abs(Math.sin(c*0.7+k)));")
    w("      ctx.fillStyle=sd[2]; ctx.textAlign='center';")
    w("      ctx.font='900 2.6px ui-monospace,monospace';")
    w("      ctx.fillText(sd[0], rx, ry);")
    w("      ctx.globalAlpha=g*bgA*0.022;")
    w("      ctx.fillStyle='rgba(184,186,194,0.80)'; ctx.font='700 2.0px ui-monospace,monospace';")
    w("      ctx.fillText(sd[1], rx, ry+H*0.016);")
    w("    }")
    w("    ctx.globalAlpha=g*bgA*0.026;")
    w("    ctx.strokeStyle='rgba(%s,0.94)'; ctx.lineWidth=0.8;" % Amid[0])
    w("    ctx.setLineDash([4,4]);")
    w("    ctx.beginPath(); ctx.ellipse(cx, clsY, W*0.256, H*0.104, 0, 0, Math.PI*2); ctx.stroke();")
    w("    ctx.setLineDash([]);")
    w("    // the quote box")
    w("    const spW=W*0.600, spX=cx-spW/2, spY=clsY-H*0.150, spH=H*0.056;")
    w("    ctx.globalAlpha=g*bgA*0.030;")
    w("    ctx.strokeStyle='rgba(%s,0.94)'; ctx.lineWidth=0.9; ctx.strokeRect(spX,spY,spW,spH);" % Amid[0])
    w("    ctx.globalAlpha=g*bgA*0.024; ctx.textAlign='left';")
    w("    ctx.fillStyle='rgba(%s,0.94)'; ctx.font='700 1.8px ui-monospace,monospace';" % Amid[0])
    w("    ctx.fillText(\"%s\", spX+spW*0.024, spY+spH*0.260);" % b['qdate'])
    w("    ctx.textAlign='center';")
    w("    ctx.globalAlpha=g*bgA*0.034;")
    w("    ctx.fillStyle='rgba(236,240,246,0.92)'; ctx.font='900 2.8px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", cx, spY+spH*0.600);" % b['quote'][0])
    w("    ctx.fillStyle='rgba(216,220,228,0.94)';")
    w("    ctx.fillText(\"%s\", cx, spY+spH*0.910);" % b['quote'][1])
    w("    // the drawn emblem")
    w("    const emX=cx-W*0.158, emY=clsY+H*0.004, emR=W*0.042;")
    w("    ctx.globalAlpha=g*bgA*0.034;")
    w("    ctx.strokeStyle='rgba(%s,0.92)'; ctx.lineWidth=1.3;" % Amid[0])
    w("    ctx.beginPath(); ctx.arc(emX, emY, emR, -Math.PI/2, Math.PI/2); ctx.stroke();")
    w("    ctx.strokeStyle='rgba(%s,0.92)';" % Amid[1])
    w("    ctx.beginPath(); ctx.arc(emX, emY, emR, Math.PI/2, Math.PI*1.5); ctx.stroke();")
    w("    ctx.globalAlpha=g*bgA*0.026;")
    w("    ctx.strokeStyle='rgba(%s,0.86)'; ctx.lineWidth=0.9;" % Amid[2])
    w("    ctx.setLineDash([2,3]);")
    w("    ctx.beginPath(); ctx.moveTo(emX, emY-emR*1.24); ctx.lineTo(emX, emY+emR*1.24); ctx.stroke();")
    w("    ctx.setLineDash([]);")
    w("    ctx.globalAlpha=g*bgA*0.028; ctx.textAlign='right';")
    w("    ctx.fillStyle='rgba(%s,0.90)'; ctx.font='900 2.0px ui-monospace,monospace';" % Amid[1])
    w("    ctx.fillText(\"%s\", emX-emR*1.30, emY+H*0.004);" % b['emblem'][1])
    w("    ctx.textAlign='left';")
    w("    ctx.fillStyle='rgba(%s,0.90)';" % Amid[0])
    w("    ctx.fillText(\"%s\", emX+emR*1.30, emY+H*0.004);" % b['emblem'][0])
    w("    ctx.textAlign='center';")
    w("    ctx.globalAlpha=g*bgA*0.030*(0.55+0.45*pul);")
    w("    ctx.fillStyle='rgba(%s,0.90)'; ctx.font='900 2.1px ui-monospace,monospace';" % Amid[2])
    w("    ctx.fillText(\"%s\", emX, emY+emR*1.62);" % b['emblem'][2])
    w("    ctx.globalAlpha=g*bgA*0.018;")
    w("    ctx.fillStyle='rgba(154,156,164,0.78)'; ctx.font='700 1.6px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", emX, emY+emR*2.00);" % b['emblem'][3])
    w("    // the two-column ledger, centre-right")
    w("    const gvX=cx+W*0.136, gvY=clsY-H*0.040;")
    w("    ctx.globalAlpha=g*bgA*0.026; ctx.textAlign='center';")
    w("    ctx.fillStyle='rgba(200,204,212,0.86)'; ctx.font='900 2.0px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", gvX, gvY-H*0.016);" % b['ledger'][0])
    w("    const GV=[['%s','%s','%s',-0.062],['%s','%s','%s',0.062]];"
      % (b['ledger'][1][0], b['ledger'][1][1], A, b['ledger'][2][0], b['ledger'][2][1], B))
    w("    for(let k=0;k<GV.length;k++){")
    w("      const bx=gvX+W*GV[k][3];")
    w("      ctx.globalAlpha=g*bgA*0.026;")
    w("      ctx.strokeStyle=GV[k][2]; ctx.lineWidth=1.0;")
    w("      ctx.strokeRect(bx-W*0.058, gvY-H*0.010, W*0.116, H*0.030);")
    w("      ctx.globalAlpha=g*bgA*0.030;")
    w("      ctx.fillStyle=GV[k][2]; ctx.font='900 2.1px ui-monospace,monospace';")
    w("      ctx.fillText(GV[k][0], bx, gvY+H*0.001);")
    w("      ctx.globalAlpha=g*bgA*0.022;")
    w("      ctx.fillStyle='rgba(206,208,214,0.84)'; ctx.font='700 1.6px ui-monospace,monospace';")
    w("      ctx.fillText(GV[k][1], bx, gvY+H*0.015);")
    w("    }")
    w("    ctx.globalAlpha=g*bgA*0.028;")
    w("    ctx.fillStyle='rgba(236,240,246,0.90)'; ctx.font='900 2.2px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", gvX, gvY+H*0.040);" % b['ledger'][3])
    w("    ctx.globalAlpha=g*bgA*0.018;")
    w("    ctx.fillStyle='rgba(154,156,164,0.78)'; ctx.font='700 1.6px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", gvX, gvY+H*0.055);" % b['ledger'][4])
    w("    // the two drawn figures")
    w("    const fgY=clsY+H*0.082;")
    w("    const FG=[['%s','%s',-0.130,'rgba(%s,0.86)'],['%s','%s',0.130,'rgba(%s,0.90)']];"
      % (b['figs'][0][0], b['figs'][0][1], Amid[1], b['figs'][1][0], b['figs'][1][1], Amid[0]))
    w("    for(let k=0;k<FG.length;k++){")
    w("      const fx=cx+W*FG[k][2];")
    w("      ctx.globalAlpha=g*bgA*0.026;")
    w("      ctx.strokeStyle=FG[k][3]; ctx.lineWidth=0.9;")
    w("      ctx.beginPath(); ctx.arc(fx, fgY-H*0.014, W*0.013, 0, Math.PI*2); ctx.stroke();")
    w("      ctx.beginPath(); ctx.moveTo(fx, fgY-H*0.001); ctx.lineTo(fx, fgY+H*0.020); ctx.stroke();")
    w("      ctx.beginPath(); ctx.moveTo(fx-W*0.016, fgY+H*0.006); ctx.lineTo(fx+W*0.016, fgY+H*0.006); ctx.stroke();")
    w("      ctx.globalAlpha=g*bgA*0.026; ctx.textAlign='center';")
    w("      ctx.fillStyle=FG[k][3]; ctx.font='900 2.0px ui-monospace,monospace';")
    w("      ctx.fillText(FG[k][0], fx, fgY+H*0.034);")
    w("      ctx.globalAlpha=g*bgA*0.016;")
    w("      ctx.fillStyle='rgba(184,186,194,0.76)'; ctx.font='700 1.5px ui-monospace,monospace';")
    w("      ctx.fillText(FG[k][1], fx, fgY+H*0.047);")
    w("    }")
    w("    ctx.globalAlpha=g*bgA*0.052; ctx.textAlign='center';")
    w("    ctx.fillStyle='rgba(236,240,246,0.86)'; ctx.font='900 3.2px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", cx, clsY-H*0.192);" % b['head'][0])
    w("    ctx.globalAlpha=g*bgA*0.036;")
    w("    ctx.fillStyle='rgba(184,186,194,0.82)'; ctx.font='700 2.4px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", cx, clsY-H*0.174);" % b['head'][1])
    w("    ctx.globalAlpha=g*bgA*0.048;")
    w("    ctx.strokeStyle='rgba(%s,0.94)'; ctx.lineWidth=1.1;" % Amid[0])
    w("    ctx.strokeRect(cx-W*0.320, clsY+H*0.150, W*0.640, H*0.034);")
    w("    ctx.globalAlpha=g*bgA*0.046; ctx.textAlign='center';")
    w("    ctx.fillStyle='rgba(%s,0.94)'; ctx.font='900 3.4px ui-monospace,monospace';" % Amid[0])
    w("    ctx.fillText(\"%s\", cx, clsY+H*0.173);" % b['head'][2])
    w("    ctx.globalAlpha=g*bgA*0.040; ctx.textAlign='center';")
    w("    ctx.fillStyle='rgba(236,240,246,0.88)'; ctx.font='900 3.0px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", cx, clsY+H*0.208);" % b['head'][3])
    w("    for(let k=0;k<4;k++){")
    w("      const ty=top+H*(0.225+0.19*k)+Math.sin(c*0.4+k)*H*0.008;")
    w("      ctx.globalAlpha=g*0.016*(0.5+0.5*Math.abs(Math.sin(c*0.7+k*1.3)));")
    w("      ctx.fillStyle='rgba(%s,0.94)'; ctx.textAlign='center';" % Amid[0])
    w("      ctx.font='900 5.6px ui-monospace,monospace';")
    w("      ctx.fillText(\"%s\", cx, ty);" % b['title'])
    w("    }")
    w("    ctx.globalAlpha=1;")
    w("")
    w("    // --- title ---")
    w("    ctx.textAlign='center'; ctx.globalAlpha=g*nameA;")
    w("    ctx.fillStyle='rgba(%s,0.94)'; ctx.font='900 11px ui-monospace,monospace';" % Amid[0])
    w("    ctx.fillText(\"%s\", cx, top+H*0.098);" % b['title'])
    w("    ctx.fillStyle='rgba(236,234,226,0.85)'; ctx.font='700 4.2px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", cx, top+H*0.131);" % b['sub'])
    w("    ctx.globalAlpha=1;")
    w("")
    w("    const colT=top+H*0.158, colH=H*0.382;")
    w("")
    # ----- columns
    cols = [
        dict(var='qtA',  x='W*0.020', bg='rgba(7,6,3,0.96)',  t0=2.0, step=0.26, cl=3.8, letter='q'),
        dict(var='jbA',  x='W*0.352', bg='rgba(5,3,8,0.96)',  t0=5.0, step=0.26, cl=6.6, letter='j'),
        dict(var='btA',  x='W*0.684', bg='rgba(6,3,3,0.96)',  t0=8.0, step=0.30, cl=9.8, letter='t'),
    ]
    for ci, cf in enumerate(cols):
        col = b['cols'][ci]
        acc = Amid[ci]
        w("    // --- column %d ---" % (ci+1))
        w("    if(%s>0.01){" % cf['var'])
        w("      const bx0=%s, bw=W*0.296;" % cf['x'])
        w("      ctx.globalAlpha=g*%s;" % cf['var'])
        w("      ctx.fillStyle='%s'; ctx.fillRect(bx0,colT,bw,colH);" % cf['bg'])
        w("      ctx.strokeStyle='rgba(%s,0.95)'; ctx.lineWidth=1.4; ctx.strokeRect(bx0,colT,bw,colH);" % acc)
        w("      ctx.textAlign='center';")
        w("      ctx.fillStyle='rgba(%s,0.95)'; ctx.font='900 4.4px ui-monospace,monospace';" % acc)
        w("      ctx.fillText(\"%s\", bx0+bw/2, colT+H*0.032);" % col['head'])
        w("      ctx.fillStyle='rgba(184,186,194,0.72)'; ctx.font='700 2.0px ui-monospace,monospace';")
        w("      ctx.fillText(\"%s\", bx0+bw/2, colT+H*0.049);" % col['sub'])
        w("      const %sRows=[" % cf['letter'])
        for r in col['rows']:
            w("        ['%s', '%s', '%s']," % (r[0], r[1], r[2]))
        w("      ];")
        w("      for(let k=0;k<%sRows.length;k++){" % cf['letter'])
        w("        const ka=Math.max(0,Math.min(1,(dt-%.1f-k*%.2f)/0.9)); if(ka<=0.01) continue;" % (cf['t0'], cf['step']))
        w("        const ry=colT+H*0.074+k*H*0.027;")
        w("        ctx.globalAlpha=g*%s*ka; ctx.textAlign='left';" % cf['var'])
        w("        ctx.fillStyle=%sRows[k][2]; ctx.font='900 2.3px ui-monospace,monospace';" % cf['letter'])
        w("        ctx.fillText(%sRows[k][0], bx0+bw*0.050, ry);" % cf['letter'])
        w("        ctx.fillStyle='rgba(206,208,214,0.84)'; ctx.font='700 1.7px ui-monospace,monospace';")
        w("        ctx.fillText('· '+%sRows[k][1], bx0+bw*0.330, ry+H*0.014);" % cf['letter'])
        w("      }")
        w("      const %s2=Math.max(0,Math.min(1,(dt-%.1f)/1.0));" % (cf['letter'], cf['cl']))
        w("      if(%s2>0.01){" % cf['letter'])
        w("        ctx.globalAlpha=g*%s*%s2; ctx.textAlign='center';" % (cf['var'], cf['letter']))
        w("        ctx.fillStyle='rgba(154,156,164,0.80)'; ctx.font='700 2.5px ui-monospace,monospace';")
        w("        ctx.fillText(\"%s\", bx0+bw/2, colT+colH*0.555);" % col['close'][0])
        w("        ctx.fillStyle='rgba(%s,0.95)'; ctx.font='900 2.3px ui-monospace,monospace';" % acc)
        w("        ctx.fillText(\"%s\", bx0+bw/2, colT+colH*0.625);" % col['close'][1])
        w("        ctx.fillStyle='rgba(206,208,214,0.82)'; ctx.font='700 2.2px ui-monospace,monospace';")
        w("        ctx.fillText(\"%s\", bx0+bw/2, colT+colH*0.690);" % col['close'][2])
        w("        ctx.fillStyle='rgba(236,240,246,0.94)'; ctx.font='900 2.2px ui-monospace,monospace';")
        w("        ctx.fillText(\"%s\", bx0+bw/2, colT+colH*0.750);" % col['close'][3])
        w("      }")
        w("      ctx.globalAlpha=1;")
        w("    }")
        w("")
    # ----- band
    w("    // --- band ---")
    w("    const tbY=top+H*0.560, tbH=H*0.248, tbX=W*0.020, tbW=W*0.960;")
    w("    ctx.globalAlpha=g*Math.max(bndA,insA);")
    w("    ctx.fillStyle='rgba(4,3,7,0.99)'; ctx.fillRect(tbX,tbY,tbW,tbH);")
    w("    ctx.lineWidth=2.0; ctx.strokeStyle=`rgba(%s,${(0.36+0.30*pul)*g})`; ctx.strokeRect(tbX,tbY,tbW,tbH);" % Amid[0])
    w("    ctx.globalAlpha=1;")
    w("    if(bndA>0.01){")
    w("      ctx.globalAlpha=g*bndA; ctx.textAlign='left';")
    w("      ctx.fillStyle='rgba(240,240,236,0.92)'; ctx.font='900 3.4px ui-monospace,monospace';")
    w("      ctx.fillText(\"%s\", tbX+12, tbY+tbH*0.140);" % b['band']['head'])
    w("      const MK=[")
    for r in b['band']['rows']:
        w("        ['%s','%s','%s',%d]," % (r[0], r[1], r[2], r[3]))
    w("      ];")
    w("      const gx4=tbX+tbW*0.030, gy=tbY+tbH*0.320, rh2=tbH*0.155;")
    w("      const litN=Math.floor(c*0.85)%MK.length;")
    w("      for(let r=0;r<MK.length;r++){")
    w("        const ka=Math.max(0,Math.min(1,(dt-11.0-r*0.20)/0.8)); if(ka<=0.01) continue;")
    w("        const ry=gy+r*rh2, on=(r===litN), key=(MK[r][3]===1);")
    w("        ctx.globalAlpha=g*bndA*ka*(on?(0.20+0.12*pul):0.06);")
    w("        ctx.fillStyle=key?'%s':'%s'; ctx.fillRect(gx4, ry-tbH*0.058, tbW*0.560, tbH*0.104);" % (C, A))
    w("        ctx.globalAlpha=g*bndA*ka*(on?1:0.55); ctx.textAlign='left';")
    w("        ctx.fillStyle=key?'%s':'%s';" % (C, A))
    w("        ctx.font=`900 ${on?2.5:2.2}px ui-monospace,monospace`;")
    w("        ctx.fillText(MK[r][0], gx4+tbW*0.012, ry);")
    w("        ctx.fillStyle='rgba(228,230,234,0.86)'; ctx.font='700 1.9px ui-monospace,monospace';")
    w("        ctx.fillText(MK[r][1], gx4+tbW*0.100, ry);")
    w("        ctx.fillStyle='rgba(154,156,164,0.76)'; ctx.font='700 1.9px ui-monospace,monospace';")
    w("        ctx.fillText(MK[r][2], gx4+tbW*0.320, ry);")
    w("      }")
    w("      const m2=Math.max(0,Math.min(1,(dt-12.0)/1.0));")
    w("      if(m2>0.01){")
    w("        ctx.globalAlpha=g*bndA*m2; ctx.textAlign='left';")
    w("        ctx.fillStyle='rgba(236,240,246,0.86)'; ctx.font='700 2.2px ui-monospace,monospace';")
    w("        ctx.fillText(\"%s\", tbX+12, tbY+tbH*0.945);" % b['band']['close'])
    w("      }")
    w("      ctx.globalAlpha=1;")
    w("    }")
    # ----- inset
    w("    if(insA>0.01){")
    w("      const oX=tbX+tbW*0.600, oW=tbW*0.375, oY=tbY+tbH*0.100, oH=tbH*0.760;")
    w("      ctx.globalAlpha=g*insA;")
    w("      ctx.fillStyle='rgba(4,4,4,0.96)'; ctx.fillRect(oX,oY,oW,oH);")
    w("      ctx.strokeStyle='rgba(%s,0.94)'; ctx.lineWidth=0.9; ctx.strokeRect(oX,oY,oW,oH);" % Amid[1])
    w("      ctx.textAlign='center';")
    w("      ctx.fillStyle='rgba(236,240,246,0.90)'; ctx.font='900 2.8px ui-monospace,monospace';")
    w("      ctx.fillText('%s', oX+oW/2, oY+oH*0.150);" % b['inset']['head'])
    w("      const VR=[")
    for r in b['inset']['rows']:
        w("        ['%s','%s','%s']," % (r[0], r[1], r[2]))
    w("      ];")
    w("      const fi=Math.floor(c*0.7)%4, Vw=VR[fi];")
    w("      ctx.globalAlpha=g*insA;")
    w("      ctx.fillStyle=Vw[2]; ctx.font='900 2.5px ui-monospace,monospace';")
    w("      ctx.fillText(Vw[0], oX+oW/2, oY+oH*0.390);")
    w("      ctx.fillStyle='rgba(206,208,214,0.84)'; ctx.font='700 1.9px ui-monospace,monospace';")
    w("      ctx.fillText(Vw[1], oX+oW/2, oY+oH*0.550);")
    w("      ctx.fillStyle=(fi===3)?'rgba(%s,0.94)':'rgba(154,156,164,0.78)';" % Amid[1])
    w("      ctx.font='900 2.2px ui-monospace,monospace';")
    w("      ctx.fillText((fi===3)?'%s':'%s', oX+oW/2, oY+oH*0.700);" % (b['inset']['flag'], b['inset']['idle']))
    w("      ctx.fillStyle='rgba(200,204,212,0.86)'; ctx.font='700 2.3px ui-monospace,monospace';")
    w("      ctx.fillText('%s', oX+oW/2, oY+oH*0.850);" % b['inset']['close'][0])
    w("      ctx.fillText('%s', oX+oW/2, oY+oH*0.960);" % b['inset']['close'][1])
    w("      ctx.globalAlpha=1;")
    w("    }")
    w("")
    # ----- strip
    w("    // --- the strip ---")
    w("    const strip%d=[" % ph)
    for s in b['strip']:
        w("      ['%s','%s','%s']," % (s[0], s[1], s[2]))
    w("    ];")
    w("    for(let k=0;k<strip%d.length;k++){" % ph)
    w("      const ka=Math.max(0,Math.min(1,(dt-15.0-k*0.35)/1.1));")
    w("      if(ka<=0.01) continue;")
    w("      ctx.globalAlpha=g*ka;")
    w("      const sxw=W*0.306, sx0=W*0.020+k*(sxw+W*0.014), sy0=top+H*0.828, syh=H*0.050;")
    w("      ctx.fillStyle='rgba(4,3,7,0.99)'; ctx.fillRect(sx0,sy0,sxw,syh);")
    w("      ctx.strokeStyle=strip%d[k][2]; ctx.lineWidth=0.8; ctx.globalAlpha=g*ka*0.65; ctx.strokeRect(sx0,sy0,sxw,syh);" % ph)
    w("      ctx.globalAlpha=g*ka; ctx.textAlign='center';")
    w("      ctx.fillStyle=strip%d[k][2]; ctx.font='900 2.6px ui-monospace,monospace';" % ph)
    w("      ctx.fillText(strip%d[k][0], sx0+sxw/2, sy0+syh*0.42);" % ph)
    w("      ctx.fillStyle='rgba(200,204,212,0.80)'; ctx.font='700 2.2px ui-monospace,monospace';")
    w("      ctx.fillText(strip%d[k][1], sx0+sxw/2, sy0+syh*0.80);" % ph)
    w("    }")
    w("    ctx.globalAlpha=1;")
    w("")
    # ----- footer
    w("    // --- footer ---")
    w("    ctx.textAlign='center';")
    w("    ctx.globalAlpha=g*Math.max(0,Math.min(1,(dt-16.6)/0.9));")
    w("    ctx.fillStyle=`rgba(236,234,226,${0.82+0.18*pul})`; ctx.font='900 5.0px ui-monospace,monospace';")
    w("    ctx.fillText(\"%s\", cx, top+H*0.899);" % b['foot'][0])
    w("    ctx.globalAlpha=g*footA;")
    w("    ctx.fillStyle='rgba(%s,0.94)'; ctx.font='900 5.4px ui-monospace,monospace';" % Amid[0])
    w("    ctx.fillText(\"%s\", cx, top+H*0.932);" % b['foot'][1])
    w("    ctx.globalAlpha=1;")
    w("    ctx.restore();   // close the beat clip opened at the top of this block")
    return "\n".join(o)
